.gitignore
setup.py

Uses docstrings for setup.py documentation and adds a couple entries to .gitignore.

Use docstrings and ignore egg-info.

---

devloperstartup.md

This version includes specifications for a ghdata.cfg file that points to a read only database at the University of Missouri. This enables developers to get started with code without having to configure the msr database locally (which is a fairly large file.).

Added developer startup instructions for basic developer access

---

README.md

Make the reference to the LICENSE file to a link in order to make the readme easier to navigate via GitHub's GUI.

README.md LICENSE link

---

.gitignore
Makefile

I spoke to @sgoggins about `make install-dev` on Linux. I only have the first change so far, but there are 2 more outstanding issues I want to address.
The first is installing it in a Python venv. In this case the venv takes over pip for one version of python, but `make install-dev` tries to install dependencies for both Python 2 & 3. Should this be addressed via separate build targets for Python 2 & 3 or is there a way of determining if python is running inside venv.
The second issue is `npm install -g apidoc brunch yarn`. This command requires root permission to run, which should be avoided ideally. My current solution is to omit the `-g` flag, installing the modules locally, but they don't appear on the path and can't be run as easily. I don't have an elegant solution for that …

Make updates for Linux

---

augur/datasources/githubapi/githubapi.py

Implemented the following metrics:
- **Code Commits:** This implementation returns the number of code commits per day.
- **Contributors:** This implementation returns a list of contributors along with their respective contributions to a project.

Implement metrics in githubapi

---

docs/python/source/dev-guide/2-install.rst
frontend/public/docs/dev-guide/2-install.html

In [dev-guide 2.3](http://augur.augurlabs.io/static/docs/dev-guide/2-install.html#augur-installation-instructions), there is a typo about granting privileges. 
The original one in [dev-guide](https://github.com/chaoss/augur/blob/master/docs/python/source/dev-guide/2-install.rst) is:
`GRANT ALL PRIVILEDGES ON augur.* TO 'augur'@'localhost';`
However, It should be:
`GRANT ALL PRIVILEGES ON augur.* TO 'augur'@'localhost';`

fix typo in dev-guide

---

augur/datasources/augur_db/augur_db.py

Implemented '[code_changes](https://github.com/chaoss/wg-evolution/blob/master/metrics/Code_Changes.md)' metric with the following optional parameters:
- period: 
- Specifies the periodicity. 
- Can be set to 'day', 'week', 'month' or 'year'. 
- Defaults to 'day'
- begin_date: 
- Specifies the beginning date. 
- Possible values: '2018', '2018-05', '2019-05-01', ..., ' 2017-03-02 05:34:19'
- Defaults to '1970-1-1 0:0:0'
- end_date:
- Specifies the ending date.
- Possible values: '2018', '2018-05', '2019-05-01', ..., ' 2017-03-02 05:34:19'
- Defaults to the current date and time
**Example Output:**
`ag.code_changes('augur', period='year')`
|         | commit_date           | count  |
| ------------- |:-------------:| -----:|
| 0      | 2017-01-01 00:00:00+00:00 |   1525 |
| 1      | …

Implement 'code_changes' metric

---

augur/datasources/augur_db/augur_db.py
augur/datasources/augur_db/routes.py
augur/server.py

- Refactored the 'code_changes' metric to accept `repo_group_id` and `repo_id` instead of `repo_url`
- Added the following routes:
- `repo-groups/:repo_group_id/code-changes` : This route returns the output for the metric 'code_changes' for a repo group with the given `repo_group_id`.
- `repo-groups/<repo_group_id>/repo/<repo_id>/code-changes` : This route returns the output for the metric 'code_changes' about a repo with a given `repo_id` within a repo group with the given `repo_group_id`.
**Suggestion:** Adding routes requires writing a lot of repeating code. I suggest we create a utility function for adding routes. Something similar to `addMetric` and `addTimeseries` functions.
**Update:** Added helper functions for simplifying the creation of API endpoints. They are
- …

Refactor and add routes for evolution metrics

---

augur/datasources/augur_db/augur_db.py
augur/datasources/augur_db/routes.py
augur/datasources/augur_db/test_augur_db.py
frontend/app/Augur.js
frontend/app/AugurAPI.js
frontend/app/components/DownloadedReposCard.vue

In the frontend,  function `Repo(repo)` called to construct repo. 
https://github.com/chaoss/augur/blob/d2ba1806c8f510d5ea122d510cdb0322dc3f6da7/frontend/app/Augur.js#L70-L71
But `repo_group_id` and `repo_id` are not always passed, it usually only commit `girurl` or `githuburl` by Vuex. For example:
https://github.com/chaoss/augur/blob/d2ba1806c8f510d5ea122d510cdb0322dc3f6da7/frontend/app/Augur.js#L219-L222
I added a new function in function `Repo` to fetch `repo_group_id` and `repo_id`. It will query `repo_group_id` and `repo_id` from `augur_db` by `owner` and `name`.

Initial repo_group_id and repo_id when Repo construct

---

augur/datasources/facade/routes.py

Remove the Facade Legacy API endpoints from api-docs.

Dev: Remove Facade Legacy endpoints from api-docs

---

augur/datasources/augur_db/augur_db.py
augur/datasources/augur_db/routes.py
augur/datasources/augur_db/test_augur_db.py
augur/datasources/augur_db/test_augur_db_routes.py

- Refactored time series metric implementations to return a 'date' field
- Added & updated augur_db tests (both `test_augur_db.py` & `test_augur_db_routes.py`

stable demo: Added & updated augur_db tests & refactor metric implementations

---

augur/datasources/augur_db/augur_db.py
augur/datasources/augur_db/routes.py
augur/datasources/augur_db/test_augur_db.py
augur/datasources/augur_db/test_augur_db_routes.py

Refactored the following metric implementations to include 'repo_name':
- issues-first-time-closed
- issues-first-time-opened
- pull-requests-merge-contributor-new
- pull_requests_merge_contributor_new
- contributors-new
- contributors
- issues-open-age
- sub_projects
- issues_first_time_closed
- contributors_new
- issues_open_age
- issues_closed_resolution_duration
- issues_maintainer_response_duration
Add metric 
- issue response time

Dev: Refactored the following metric implementations to include 'repo_name'

---

workers/gh_repo_info_worker/LICENSE
workers/gh_repo_info_worker/README.rst
workers/gh_repo_info_worker/gh_repo_info_worker/__init__.py
workers/gh_repo_info_worker/gh_repo_info_worker/runtime.py
workers/gh_repo_info_worker/gh_repo_info_worker/worker.py
workers/gh_repo_info_worker/tests/test_sample.py

Added a GitHub Repo Info Worker that fetches data such as forks, stargazers, watchers, etc. for the `repo_info` table.
A few things to note about this version of the worker:
- It hasn't been integrated as Augur as of yet.
- It's more of a stand-alone python script.
- It fetches repo info for all repos listed in the `repo` table. That is you cannot specify which repo you want to run it for
**Note:** I've marked this PR as draft as I'm working on implementing a few metrics for fork count, watchers, etc. i.e. metrics that can be implemented from the data in `repo_info`

dev: Add GitHub Repo Info Worker

---

augur/datasources/augur_db/augur_db.py
augur/datasources/augur_db/routes.py
augur/datasources/augur_db/test_augur_db.py
augur/datasources/augur_db/test_augur_db_routes.py
workers/gh_repo_info_worker/gh_repo_info_worker/worker.py

- Fixed a few unit tests
- Fixed a few data collection bugs in Repo Info Worker
- Added the following metrics:
- **Forks:** Returns a time series of forks
- **Fork Count:** Returns the latest fork count
**Update:**
- Added test for 'get_repos_for_dosocs' endpoint
- Added the following metrics:
- **Stars:**  Returns a time series of stars
- **Stars Count:** Returns the latest stars count
- **Watchers:** Returns a time series of watchers
- **Watchers Count:** Returns a time series of watchers count

dev: Bug fixes in Repo Info Worker & Metric implementations

---

augur/datasources/augur_db/augur_db.py
augur/datasources/augur_db/routes.py
augur/datasources/augur_db/test_augur_db.py
augur/datasources/augur_db/test_augur_db_routes.py

Implement four Facade Metrics in new schema`augur_db`: 
- annual-commit-count-ranked-by-new-repo-in-repo-group
- annual-commit-count-ranked-by-repo-in-repo-group' 
- annual-lines-of-code-count-ranked-by-repo-in-repo-group
- annual-lines-of-code-count-ranked-by-new-repo-in-repo-group

Implement Facade metrics in augur_db database 

---

workers/gh_repo_info_worker/gh_repo_info_worker/runtime.py
workers/gh_repo_info_worker/gh_repo_info_worker/worker.py

In this version of the gh_repo_info_worker the worker connects to the broker and can receive tasks.
You can run the worker using the command `python -m gh_repo_info_worker.runtime` while in the `workers/gh_repo_info_worker` directory.
To send a task to this worker send a `POST` request to the endpoint `/task` with the following json data:
```{
"job_type": "UPDATE",
"models": [
"repo_info"
],
"given": {
"git_url": "https://github.com/rails/rails-dom-testing.git"
}
}
```
The `git_url` field specifies the git repository you want to run the worker on.

Make gh_repo_info_worker compatible with broker

---

augur/datasources/augur_db/routes.py
augur/datasources/downloads/routes.py
augur/datasources/ghtorrent/routes.py
augur/datasources/githubapi/routes.py
augur/datasources/librariesio/routes.py
workers/gh_repo_info_worker/README.rst
workers/gh_repo_info_worker/setup.py

Added a `setup.py` to `gh_repo_info_worker`
This allows you to install the worker and run it by invoking the command `repo_info_worker`
Updated API docs. Moved all legacy API endpoints to the bottom of the sidebar

Add setup.py to gh_repo_info_worker & API Docs update

---

workers/gh_pr_worker/.gitignore
workers/gh_pr_worker/LICENSE
workers/gh_pr_worker/README.rst
workers/gh_pr_worker/gh_pr_worker/__init__.py
workers/gh_pr_worker/gh_pr_worker/runtime.py
workers/gh_pr_worker/gh_pr_worker/worker.py
workers/gh_pr_worker/setup.py
workers/gh_pr_worker/tests/test_sample.py
workers/gh_pr_worker/tox.ini

Add a PR worker. Currently, it only adds data to the pull_requests table.

Add Pull Request Worker

---

docs/setup/installing-augur.md

Change Installing instruction  for Mac OS X. 
Run `pgsql` by ` pgsql postgres` instead of `sudo -u postgres psql`
Reference:  https://wiki.postgresql.org/wiki/Homebrew

update doc installing-augur.md

---

augur/datasources/augur_db/augur_db.py
augur/datasources/augur_db/routes.py
workers/gh_pr_worker/gh_pr_worker/worker.py

Implemented the following pull request metrics:
- **Reviews:** Time series of the number of new reviews or pull requests opened within a certain period.
- **Reviews-Accepted:** Time series of the number of accepted reviews or pull requests opened within a certain period.
- **Reviews-Declined:** Time series of the number of declined reviews or pull requests opened within a certain period.
- **Review-Duration:** Time since a review/pull request is proposed until it is accepted.
Pull Request worker bug fixes & minor changes
- Add `repo_id` in pull request records
- Set default `cntrb_id` in pr_events to 1
- Removed error handling for debugging [Temporary]

PR metric implementations & PR worker bug fixes

---

workers/pull_request_worker/pull_request_worker/runtime.py
workers/pull_request_worker/pull_request_worker/worker.py
workers/repo_info_worker/repo_info_worker/runtime.py
workers/repo_info_worker/repo_info_worker/worker.py

Repo Info Worker:
- Added error handling
- Improved logging
- Port can be set in augur.config.json
PR Worker:
- Added error handling
- Port can be set in augur.config.json

Fixes & minor changes to Repo Info Worker & PR Worker

---

augur/datasources/augur_db/augur_db.py

Fixes an issue with commit counting when there is more than one commit on a day, and there is more than one file committed, and there are empty commit records that do not specify files (i.e., merged pull requests, etc.).

Dev patch 2

---

augur/datasources/augur_db/augur_db.py
augur/datasources/augur_db/routes.py
augur/datasources/augur_db/test_augur_db.py
augur/datasources/augur_db/test_augur_db_routes.py
frontend/src/Augur.ts
frontend/src/AugurAPI.ts
frontend/src/components/charts/CountBlock.vue
frontend/src/components/charts/LicenseTable.vue
frontend/src/components/charts/LineChart.vue
frontend/src/components/charts/PieChart.vue
frontend/src/components/common/CompareControl.vue
frontend/src/components/layout/MainSidebar/MainSidebar.vue
frontend/src/router.ts
frontend/src/store/modules/common/actions.ts
frontend/src/store/modules/common/mutations.ts
frontend/src/store/modules/compare/actions.ts
frontend/src/store/modules/compare/getters.ts
frontend/src/store/modules/compare/mutations.ts
frontend/src/styles/augur.styl
frontend/src/views/Dashboard.vue
frontend/src/views/RepoOverview.vue
frontend/src/views/Repos.vue
frontend/src/views/RiskMetrics.vue

- Front End
- fix style error 
- Use repo_name instead url in the router 
- Router for Repo comparison 
URL Example: `http://localhost:8080/repo/Apache/storm-site/comparedTo/Comcast%2Fhadoop,Comcast%2Fcaniuse,Risk%20Workign%20Group%2Fopenbsd,Risk%20Workign%20Group%2Fboringssl/` 
- Risk Metric 
- refactor license-count
- refactor license-coverage
- refactor license-declared 
- add test for all endpoints in risk metric 
- Add four visualization of risk metrics

Frontend Router and Risk Metric Implemntation

---

Makefile
util/make-config.py

Created a script that allows you to interactively create `augur.config.json`. To run the script execute the following command 
```
make config
```

Added script to create augur.config.json

---

frontend/src/Augur.ts
frontend/src/components/charts/CountBlock.vue
frontend/src/components/charts/LicenseTable.vue
frontend/src/components/charts/LineChart.vue
frontend/src/views/Repos.vue
frontend/src/views/RiskMetrics.vue

- Fix risk page in new API endpoints cache structure  
- use url as key instead of `Repo.toString`

Fix Risk page

---

workers/repo_info_worker/repo_info_worker/worker.py

Should fix #377 
On carefully going through the log (https://pastebin.com/pE71B71R), I realized that the worker was trying to go to sleep but couldn't calculate the sleeping time, consequently, raising an exception  (See line no 522 onwards).
Since the `datetime` module is imported as `from datetime import datetime`, changing `datetime.datetime.now()` to `datetime.now()` and `datetime.datetime.fromtimestamp` to `datetime.fromtimestamp` should allow the worker to calculate the sleeping time and fix this problem.
Also, there was a typo [line no: 376] that was raising an exception while the worker tried to handle the previous exception.
This PR fixes all these typos and should allow the worker to go to sleep when the rate limit exceeds.

Repo Info Worker: Fix rate limit exceeded error

---

frontend/src/components/ReposInGroup.vue
frontend/src/components/common/CompareControl.vue
frontend/src/views/Repos.vue

I found some columns that should have been deleted on the comparison bar + repo listings. This PR should take care of that.

Remove comparison options button / noise

---

workers/pull_request_worker/pull_request_worker/worker.py

Fixes bug that causes the PR worker task to fail when inserting PR metadata with null users. Fixes #404 

Fix bug that causes task failure when inserting PR meta data

---

workers/repo_info_worker/repo_info_worker/worker.py

Made changes to Repo Info Worker to use Github API v4 to calculate commit count instead of making 3 REST API calls to calculate commits

Repo Info Worker: Count commits using Github API v4

---

augur/cli/db.py

Users now have the ability to create new repo groups in the database specified in their config file. 
This can be done by using the command `augur db add_repo_groups /path/to/repo_groups.csv` where `repo_groups.csv` is a valid `.csv` file with the following format:
```
<repo_group_id>,<repo_group_name>
...
```
Where `<repo_group_id>` is the desired ID of the new repo group, and `<repo_group_name>` is the desired name of the new repo group. 
Each pair of values should be on its own line (indicated by the `...`), without quotes, and there should be no column headers. An example of a valid file follows:
```
20,Apache Camel
21,Apache DeltaSpike
22,Apache Qpid
23,Apache Tomcat
```
There is also a new helper command `augur db get_repo_groups` which will retrieve information about the repo …

Add ability to create new repo groups from CLI

---

util/scripts/control/augurkill.sh

We discovered earlier today that without checking for the presence
of a virtual environment, if Augur is installed globally, then the
augur util kill command will kill all process controlled by the current
user.
This patch adds a check for the presence of a virtual environment before
running the augur util kill command.
Signed-off-by: Carter Landis <ccarterlandis@gmail.com>

 Update augur util kill to check for venv

---

frontend/src/components/charts/OsiCard.vue

This adds data similar to PR #469 where the user can view the licenses that are, and are not, approved by OSI.
Listed below is the result of clicking the "approved" licenses.

Link to OSI approved license lists

---

augur/metrics/repo_meta/repo_meta.py
frontend/src/components/charts/CiiTable.vue
frontend/src/views/RiskMetrics.vue

This helps the CII metric follow the new database structure. It is basic for now but will eventually have more features.
ALSO, PLEASE NOTE: The database is not full right now. It only had a few matching repositories, so it won't show everything. Cloudstack is a working one.

CII back-to-basics

---

augur/metrics/commit/commit.py

It was counting the total commits, not the number of committers. This API call only affected the risk page.

fixed a committer counting issues in the API. 

---

scripts/install/install.sh
scripts/install/setup_db.sh

I forgot that the DB setup script is interactive, so redirecting the output to a file doesn't work. Whoops!

Remove stdout redirect from DB setup script

---

Makefile
augur/cli/configure.py
augur/cli/util.py
augur/server.py
database-compose.yml
docker-compose.yml
schema/generate/5-seed-data.sql
schema/generate/8-schema_update_10.sql
schema/generate/9-schema_update_11_pr_commits.sql
scripts/control/kill.sh
scripts/control/processes.sh
scripts/control/status.sh
util/docker/backend/Dockerfile
util/docker/backend/install_packages.sh
workers/facade_worker/facade_worker/facade01config.py
workers/facade_worker/facade_worker/facade03analyzecommit.py
workers/facade_worker/facade_worker/runtime.py
workers/github_worker/github_worker/runtime.py
workers/insight_worker/insight_worker/runtime.py
workers/insight_worker/insight_worker/worker.py
workers/linux_badge_worker/linux_badge_worker/runtime.py
workers/metric_status_worker/metric_status_worker/runtime.py
workers/pull_request_worker/pull_request_worker/runtime.py
workers/repo_info_worker/repo_info_worker/runtime.py
workers/value_worker/value_worker/runtime.py

This PR introduces some new features and fixes intended to help stabilize Augur and prepare for the upcoming release. 
- Workers now use the newly renamed `name` key under the `Database` section of the config
- `backend` Docker image refactored to ensure workers are installed correctly
- Deprecated plugin status check removed from metrics API health check endpoint
- Required Git dependency was added to backend Docker image
- `insight_worker` has been refactored to dynamically discover the metrics API
- `augur util status` is a new command that will display the last 20 lines of the log files, or display all the files with `less` if passed the `--interactive` flag
- The default `facade_repo_directory` setting has been updated to `/augur/repos` for the Docker image (regular users will always …

Stabilization

---

augur/cli/util.py

This PR fixes a bug in `augur util list` and `augur util kill` wherein they would discover processes in ALL virtual environments, not just the one that was currently active.

Fix process control commands incorrect process discovery

---

test/api/test_util_routes.py

To enforce DRY principles, moved the repetitive code to a common function. It also promotes code reusability.

Moving the repetitive tests to a common function (DRY)

---

README.md

The current link is broken. I'm proposing a link to https://oss-augur.readthedocs.io/en/master/getting-started/installation.html#data-collection based on my limited understanding of Augur. Please let me know if it's aligned the intention of that section.

Fix data collection link

---

augur/cli/configure.py
docs/source/getting-started/collecting-data.rst
util/docker/docker.config.json

Release worker was previosly missing in the configuration and not enabled
Resolves #736

Add config for release worker

---

workers/repo_info_worker/repo_info_worker/worker.py

This fixes a bug from #721 with wrong number of parameters for `get_repo_data`.
Resolves #737

Fix repo_info_worker for forked data

---

tests/test_helpers.py
workers/worker_base.py

Added a few unit tests for the base worker. Also added the `@staticmethod` decorators to `check_duplicates` &  `dump_queue` as they're more related to the Worker class rather than the object! [they do not utilize any variable from the __init__ method, therefore they are worker agnostic]
Signed-off-by: mrsaicharan1 <saicharan.reddy1@gmail.com>

Added unit tests for worker methods

---

setup.py

Fixes a bug that causes the `test_issue_duration` unit test to fail on 3.6 due to new behavior in Pandas.

Revert pandas version to v1.0.5

---

augur/metrics/release.py
workers/release_worker/release_worker.py

This change checks for and adds tags to the `releases` table when they
are used instead of actual GitHub releases. It also adds metrics for
tag_only releases
Requires #893 to be merged first.

Add tag_only releases to the release worker

---

Makefile
augur/cli/run.py
augur/cli/util.py
docs/source/getting-started/command-line-interface/util.rst

At somepoint in the summer, a patch was introduced that introduced a 15 second wait time to the `augur util kill` command that occured after the first attempt to gracefully stop the process with `SIGTERM`, after which it would attempt to kill all the process with `SIGKILL`. While this fallback makes sense, it in inadvertently introduced this artifical 15 second wait time to the startup of the main server. This was due to poor design during the initial implementation, which copied code blocks that should have been refactored. The 15 second delay was added to both of these code blocks, one of which was used in `augur run`, thus causing the slowdown.
This was fixed by refactoring out the copied code blocks to a singular underlying method call, removing the 15 second wait altogether, and …

Fix Augur process control commands

---

augur/cli/configure.py
augur/cli/run.py
augur/config.py
augur/logging.py
docs/source/development-guide/installation.rst
docs/source/getting-started/collecting-data.rst
metadata.py
scripts/install/config.sh
scripts/install/install.sh

Currently, on all branches, using `augur configure generate` (the augur lib command to create a config file) behaves in an undesirable way if installed using `make install`. The issue is that after running `augur configure generate`, if you used `make install` to install Augur, your config file is not written to root of your cloned source code directory. It is instead written to the `site-packages/augur/` folder that lives with your Python binary inside your virtualenv folder. The reason that it writes to this location is due to how I implemented the config generation script. The script uses a package-level variable called `ROOT_AUGUR_DIRECTORY` to determine the location of the root of the file currently that is currently running; when installed in non-editable mode (without using the …

Update default config file location

---

docs/source/getting-started/installation.rst
scripts/install/api_key.sh
scripts/install/backend.sh
scripts/install/checks.sh
scripts/install/config.sh
scripts/install/frontend.sh
scripts/install/install.sh

This patch:
- updates the installation process to write the all logs (including errors) to both `stdout` and to the `logs/` directory
- hides user input when entering their database password during the installation process
- adds a warning in the documentation to not use `sudo` when running or installing Augur

Update installation logging for clarity

---

augur/cli/db.py

Like the title says. Takes a GitHub org name, and (blindly, without dupe checking) creates a repo group with the same name. It then inserts all the repos from GitHub into that repo group.

Add ability to create repo groupgs from GH orgs on the CLI

---

schema/create_schema.sql
schema/generate/24-schema_update_26.sql

Adds the tags to the schema creation, which was missed during testing because a new contributor didn't know to include that in the patch.

Dev release schema patch

---

docs/source/index.rst

Includes the proposed changes from #940 that were not implemented because the PR was merged prematurely.

Restructure maintainer & contributor list

---

workers/gitlab_issues_worker/gitlab_issues_worker.py

Augur repo id was being used to make a request through the gitlab API while the gitlab project id was to be used. Used the methods in base worker class to fetch the correct id of project using the git_url given.

Bug fixes in gitlab issue worker

---

augur/config.py
augur/housekeeper.py

This change updates the Augur database in case and org or repository
change their name. Then the old url redirects to the new one, but was
still visible in the database and UI.
To run the feature, add the followng to the `"Housekeeper"` section
of the `augur.config.json`:
```
"update_redirects": {
"switch": 1,
"repo_group_id": 0
},
```

Update repo and organization redirects

---

workers/gitlab_issues_worker/gitlab_issues_worker.py

For the Issue _worker problem 
```
File "/Users/gogginsS/github/chaoss/augur-dev/workers/gitlab_issues_worker/gitlab_issues_worker.py", line 51, in gitlab_issues_model
url_encoded_format_project_address = quote(owner + '/' + repo, safe='')
NameError: name 'quote' is not defined
```
I found out that we did not import ` quote ` from ` urllib.parse `   
So I just added the import Statement and I believe it should work.

Issue_worker ' quote ' issue 

---

augur/routes/pull_request_reports.py

1. Removed the lines that created the 'average_days_between_responses' and 'average_hours_between_responses' columns out of the data manipulation that happens after the massive query and into the specific endpoint that uses those columns since only one endpoint uses them, and it is easier to error check within one endpoint whether the time data is null. 
2. Added group_by paramater to 'average_commits_per_PR' which can take 'year' or 'month' as a paramater. 
3. Filtered columns so that each endpoints dataframe only has the columns needed for that endpoint.

PR Report Changes

---

README.md

This is really just one character I removed.
Signed-off-by: Christoph Görn <goern@redhat.com>

fix a typo in a link

---

docker-compose.yml

Current docker image is now hosted on augurlabs' dockerhub page.

Change source of where docker pulls images back to expected hosting site

---

workers/pull_request_worker/pull_request_worker.py
workers/worker_git_integration.py

I made it so that the pull request worker can stagger its insertion into the database when paginating through pull requests.

Paginate endpoint can now stagger insertions to insert a certain amount at a time to the database.

---

workers/github_worker/github_worker.py
workers/worker_persistance.py

This should get rid of the 'bigint' conversion errors thrown by psycopg2. I was not able to replicate the issue after these changes.

Added error handling for a type error caused when the Github Worker tries to bulk insert. 

---

augur/cli/db.py
augur/housekeeper.py
augur/platform_connector.py
workers/worker_base.py
workers/worker_persistance.py

Automatically add repos to org
This change allows automatic updates of newly added repositories.
The housekeeper does those updates, but one can run them manually as well
with `augur db update-org-repositories <org>`
In order to run housekeeper job, ad the following config 
to `augur.config.json`:
```
{
"delay": 1000000,
"given": [
"github_url"
],
"model": "update_org_repositories",
"repo_group_id": <your_repo_group_id>
}
```
Resolves #914

Automatically add repos to org

---

util/docker/backend/Dockerfile

Needed a backslash after installing postgresql client. Added.

docker patch

---

scripts/docker/install-go.sh
scripts/install/workers.sh
util/docker/backend/Dockerfile

The containers run Debian 10 which is great except Debian's go package is very out of date. I decided to install it with a bash script instead of apt and it works fine now. The issue had to do with it breaking the scorecard build.

Fixed Go Breaking the Docker Build 

---

workers/github_worker/github_worker.py
workers/pull_request_worker/pull_request_worker.py
workers/worker_git_integration.py

Andrew and I rewrote enrich_cntrb_id to be more readable by using more for loops instead of complicated table merges. In the future it might be wise to refactor this method out into its own worker class complete with a queue. Presently, we have had issues with more than one worker using this method at a time and causing collisions (i.e. pr worker thinks a contributor wasn't in the database but the GitHub worker inserts that contributor right after the check so the pr worker inserts a duplicate and throws an integrity error.) The main errors this branch can throw now have to do with integrity violations in the bulk inserts for other models not related to enrich_cntrb_id.

Andrew and I spent a lot of time rewriting enrich_cntrb_id to be more maintainable and stop duplicate inserts.

---

workers/github_worker/github_worker.py
workers/pull_request_worker/pull_request_worker.py

Fixed edge case with bulk insertions. I didn't make the bug happen but my changes in the bulk insert made it happen way more often. The insertion method checks to see if source_issues['all'] isn't empty but not if source_issues['insert'] is empty. So when it tried to enrich_cntrb_id source_issues['insert'] was empty causing a ValueError.

Fixed edge case causing ValueErrors

---

workers/worker_git_integration.py

Different types of data have different identifiers so now if the source data doesn't have a user.id the method will instead use the user.node_id to determine whether or not the user is in the contributors table. We can't just check one key for all of them either since some data doesn't have a user.node_id and some data doesn't have a user.id.

Added support for alternate identifiers for source data when enriching contributor.

---

docs/source/rest-api/spec.yml

The documentation for the committers indicated that the endpoint should be called with http://localhost:5000/api/unstable/repo-groups/1/Committers but the correct url is http://localhost:5000/api/unstable/repo-groups/1/committers. The only difference being the c in committers

Fix typo in docs

---

workers/worker_git_integration.py

Quick patch to queries of API endpoints related to contributor data. Two fields were added including full name and last activity date for contributor enrichment and query GitHub contributors. 

Patch api data to quickly grab full name and recent activity data from GitHub endpoints.

---

docs/source/deployment/nginx-configuration.rst
docs/source/getting-started/frontend.rst

Added more details in the documentation. First, more detail in the "Augur's Frontend" section so new users don't get confused which directory to run npm commands in. Second, in the "Web Server Configuration" section making the directories more general. Additionally, lines 130 & 140 were a bit obscure on whether they needed to be replaced as well.
Signed-off-by: Sean Brennan <brennansean6@gmail.com>

Added more specificity and detail to the documentation

---

augur/routes/util.py
docs/source/rest-api/spec.yml

1. Fixed typos in the urls for several endpoints
2. The url was different in the docs than the code, but I thought the url in the docs made more sense so I changed the endpoint url to match what the docs had
3. Organized spec.yml by the Chaoss working groups, so all the endpoints in the each working group are all together in the file
4. Then within each working group in the docs I grouped the similar endpoints together rather than grouping all the repo group endpoints and all the repo endpoints together

Api Docs Fixes

---

workers/worker_persistance.py

I added an if statement that checks if the nested column has already been inserted. 
The error was happening because it was trying to add two json fields that are nested in the user field. So the first one ran fine and got all the user fields, but when it tried to add the second one it already had those fields added so it errored. Therefore we needed an if statement to check if the column has already been inserted, and if it has we need to continue

Fix _add_nested_columns method

---

workers/github_worker/github_worker.py
workers/worker_git_integration.py

1. Fixed a float not iterable error in the Github worker, which was caused by accessing the wrong json item in the response from the api. We were previously accessing the `assignee` field when we needed to be accessing the `assignees` field
2.  I also commented out or removed some unneeded code in the enrich_cntrb_id method located in the worker_git_integration.py file

Fix float not iterable error in GitHub worker

---

workers/facade_worker/contributor_interfaceable/contributor_interface.py
workers/worker_git_integration.py

The facade worker now uses the commit sha to attempt to resolve commit emails to contributors  before anything else. Also other smaller changes to log statements and minor refactors to make more readable.

Isaac commit resolution

---

workers/pull_request_worker/pull_request_worker.py

1. Remove unneeded `pass` keywords from pr worker. 
The `pass` keyword is used as a placeholder for future code, so in these use cases they were not doing anything

Remove pass from pr worker

---

workers/worker_base.py

1. Made a small change to an if else block which makes it more readable
The old version had two chains of if else blocks using python's syntax, which I found very difficult to read, so I changed it to 1 more traditional if else block
Essentially I took 2 if else chains using python syntax to 1 more traditional if else block

Small change to worker_base.py

---

workers/deps_libyear_worker/deps_libyear_worker.py
workers/deps_worker/deps_worker.py
workers/github_worker/github_worker.py
workers/pull_request_worker/review_model_outfactor.py
workers/worker_git_integration.py
workers/worker_persistance.py

1. Changed all traceback logging to the print_traceback method, instead of using the same three lines of code all over the place.
2. Moved print_traceback method to worker_persistance.py
3. Added documentation for print_traceback method

Add print traceback method to all workers

---

workers/worker_persistance.py

1. Remove the `table_pkey` param because it is unneeded. The `table_pkey` is obtained in the `get_relevant_columns` method so it does not need to be passed in as a parameter.
2. Add docstring to `organize_needed_data` method

Add docstring to organize_needed_data

---

workers/message_insights_worker/setup.py

1. There was an error in the setup.py for the message insights worker that said `tensorflow==2.8.0rc0`, which needs to be `tensorflow==2.8.0`.
This typo was causing `make rebuild-dev` and `make install-dev` to both error when they made it to the message_insights_worker installation.

CRITICAL: Tensorflow version casuing installation error

---

workers/github_worker/github_worker.py

1. Removed code used to test the `print_traceback` method. 
The code was there to force an exception to see if the `print_traceback` method was working correctly.

Remove code that was used to test print_traceback method

---

workers/worker_git_integration.py

Many of the workers have shown in the logs that they connected to the broker twice. While it hasn't seemed to cause any issues, it does not need to be happening. I figured out that the method call for a worker to connect to the broker was being made in the `__init__` method of the `Worker` class and the `WorkerGitInterfaceable` class. And since the `WorkerGitInterfaceable` class inherits from the `Worker` class, any time the `WorkerGitInterfaceable` class is instantiated, the broker is connected to twice. With a worker this happens because most of them inherit from `WorkerGitInterfaceable`. As additional proof that this is the issue, you can see that workers (facade worker) that inherit from just the `Worker` class don't have the issue, but workers (github_worker, pr_worker, …

Fix Workers Connecting to Broker Twice

---

README.md
docs/source/getting-started/installation.rst
docs/source/quick-start.rst

Docs typos fix

---

workers/facade_worker/contributor_interfaceable/contributor_interface.py
workers/worker_git_integration.py

A number of changes were made to the facade worker to speed up the contributor interface's commit resolution logic including removing the special rate limit for that section as well as some shortcuts to avoid unnecessary API calls. 
Now the facade worker ignores commit data if it has been found to be unresolved in the past, in the future it might be beneficial to process this data after the fact. 
The worker also checks the contributor table for logins before trying to get the login from endpoints now.

Changes to speed up facade commit contributor resolution

---

docs/source/quick-start.rst

Changed a few details in the configuration instructions under quickstart to overcome recent changes in pypi and NPM.

Documentation Update

---

augurface/src/store/UtilModule.js

The patch un-hardcode the use of http, that was found while working on augurface deployment for augur.osci.io.

Add https support to augurface

---

docs/source/quick-start.rst
metadata.py
schema/create_schema.sql
schema/generate/95-schema_update_97.sql
schema/generate/96-schema_update_98.sql

Specifically, we found 80 duplicate issues in a corpora of 2.8 million, 93 duplicates in a corpora of 3.9 million pull requests, and 7 repo_labor duplicates in a corpora of 7.8 million 
The workers have duplicate protection logic with a rare failure scenario that is prevented by the addition of the unique keys in this schema modification script.

In rare cases, when running multiple workers, duplicate entries were created for some objects

---

metadata.py
schema/generate/95-schema_update_97.sql
schema/generate/96-schema_update_98.sql

Depending on the postgres deployment, schema update's 97 and 98 were not deploying without error. This patch fixes the error on postgres deployments where they were failing.

Automation Schema Change - Added Schema Explicitly

---

.github/workflows/build_docker.yml

Seems I messed up the tagging because I didn't test fully. I would still need to do some test before it should be merged (eg, tag a release on my fork and see how it goes, etc). 
Once that's done, there is also a setting to offer packages that need to be turned on, so people can use the docker image to deploy.

Correctly tag the images

---

docs/source/getting-started/installation.rst

Signed-off-by: Diana Mukhanova <diananova2508@gmail.com>
I want to document an issue that I experienced on my MacOS during installation that I think others will find helpful as well. After running `make install`, my build failed and I found this error in gunicorn.log:
```
[ERROR] Connection in use: ('0.0.0.0', 5000) 
```
The problem is that port 5000 is being used by another process. I tried the common commands for killing the process:
```
sudo lsof -i :<PortNumber>
kill -9 <PID>
```
This didn't work and after searching a bit online I found a[ solution ](https://medium.com/pythonistas/port-5000-already-in-use-macos-monterey-issue-d86b02edd36c). Turns out MacOS uses 5000 port for Airplay Receiver, so I had to manually change the settings.

Document MacOS issue during installation

---

CONTRIBUTING.md

Signed-off-by: Biki-das <bikid475@gmail.com>
Most beginner Contributors usually fail to setup upstream and later face merge conflict issue just due to not setting up of the upstream, i wrote a easy to follow instruction which would help them to keep their repo sync in with the original repository

Contributing.md -Added instruction for setting up the upstream for the repo

---

augur/config.py
workers/insight_worker/insight_worker.py

Signed-off-by: Biki-das <bikid475@gmail.com>
Dictionary expression binds the same key multiple times. This may lead to unintentional behaviour as the key will always map the last value provided to it. It is recommended to have unique keys.

Fix:Removed duplicate dictionary keys

---

CONTRIBUTING.md

Signed-off-by: kunlefash  <kunlefashmayop@gmail.com>

Update contributing.md file Signed-off-by: kunlefash

---

workers/deps_libyear_worker/libyear_utils.py
workers/deps_libyear_worker/npm_parser.py
workers/deps_libyear_worker/pypi_parser.py
workers/facade_worker/facade_worker/excel_generators/__init__.py

Using the literal syntax can give minor performance bumps compared to using function calls to create dict, list and tuple.
This is because here, the name dict must be looked up in the global scope in case it has been rebound. Same goes for the other two types list() and tuple().

Added literal syntax to create the data structure

---

schema/generate/100-schema_update_102.sql
setup.py
user-resolution-rate-check.sh
workers/worker_git_integration.py

Fixing Schema Script and Addressing GH API Timeout. 

---

.github/pull_request_template.md

Signed-off-by: Priya Srivastava <shivikapriya730@gmail.com>
**Current behaviour:**
The changes made in the [PR](https://github.com/chaoss/augur/pull/1745) are not functional because of the missing content in the `pr_request_template.md`in the `.github` directory. 
**Solution:**
For the pull request template to work it needs to updated in the .github directory as well. This PR updates the same.

PR template added in .github directory

---

docs/source/getting-started/collecting-data.rst
docs/source/getting-started/command-line-interface/backend.rst
docs/source/getting-started/command-line-interface/configure.rst
docs/source/getting-started/installation.rst
docs/source/getting-started/toc.rst

In this PR:
-  I attempted to make the language on the documentation more inclusive using [this tool](https://www.witty.works/)

Resolving Issue #1857; Make the texts in the doc more inclusive. 

---

frontend/package.json

For some reason (likely due to the complex web of dependencies),
newer version are failling with a typescript error. Since part of the
stack can't be update (vue-vega is 5 years old), I suspect we can't
really count on a fix there.
So in order to build the application (and containers), it has to be
fixed on the exact version for now.

Hardcode the vega version

---

util/docker/frontend/Dockerfile

While this work to build with docker, podman/buildah stop the
build to ask which image to use, preventing a build in a script.

use a fully qualified name for the container

---

docs/source/schema/regularly_used_data.rst
docs/source/schema/table_data.rst
docs/source/schema/toc.rst
docs/source/schema/unused_data.rst
docs/source/schema/used_data.rst
docs/source/schema/working_tables.rst

**In this PR, I:**
- Created the files that display the various states of the data collected by augur.
This PR fixes #1900
- There's still ton of work to be done on it, but this is the begining.

Addition of the files that display data collected by augur and their different states.

---

augur/cli/user.py

Signed-off-by: Priya Srivastava <shivikapriya730@gmail.com>
_This is work in progress_
- Progress till now: Add user <username> subcommand with admin flag (more work (access, permissions) on admin role required)
Made this PR to keep track of the progress

Add user subcommand CLI

---

augur/routes/util.py
schema/create_schema.sql
schema/generate/106-schema_update_108.sql

- The performance of the repository listing API degrades as we get over 5,000 repositories. The inclusion of materialized views, and references to those MV's from the API SQL dramatically improves performance.

Performance Update for Repository Listing API Endpoint. 

---

augur/api/gunicorn_conf.py
augur/application/cli/config.py
augur/application/config.py
augur/application/logs.py

1. Log level comes from config now, rather than using a default
2. Log directory comes from config now, rather than using a default
3. Removed old log settings that are not currently used. They may be added back in the future, but for now they are removed so they do not confuse users.

Make logs get the log level and directory from config rather than using defaults

---

augur/tasks/github/events/tasks.py
augur/tasks/github/facade_github/contributor_interfaceable/contributor_interface.py
augur/tasks/github/issues/tasks.py
augur/tasks/github/messages/tasks.py
augur/tasks/github/pull_requests/tasks.py
augur/tasks/github/util/github_paginator.py
augur/tasks/start_tasks.py

- Add patches to AugurTaskRoutine to prevent one phase's changes not being reflected in subsequent phases
- Patch contributor resolution so it can parse string data better
- Phases are now defined in python functions instead of messily through an enum. The name of the phase is the name of the function and the function just returns what you want celery to run; ezpz hopefully  
- Revert change to some tasks to take a repo_id instead of the repo_git string as it raised concerns about log readability.

Patch Augur-new's task scheduling mechanism

---

augur/tasks/github/facade_github/contributor_interfaceable/contributor_interface.py
augur/tasks/github/util/github_paginator.py

The `process_dict_response` function now returns `SUCCESS` if the dict does not contain the key `message`.
This is to handle additional cases where the GitHub API is intended to return a dict and not a list. 
For example when `https://api.github.com/users/ABrain7710` returns a dict when it succeeds not a list.
The function will still process error responses fine though because all Github errors include the `message` key.
Additionally, when GitHub returns an error indicating that an abuse mechanism has been detected we now sleep for the amount of time specified in the `Retry-After` header

Small changes to process_dict_response

---

augur/tasks/github/detect_move/tasks.py
augur/tasks/github/repo_info/tasks.py
augur/tasks/start_tasks.py

- Patch detect_github_repo_move to be called on a per-repo basis and is now executed parallel in a group
- Patch with same effect for collect_repo_info to address it lagging really far behind other tasks

Make detect_repo_move and collect_repo_info execute in a group

---

scripts/install/workers.sh

OSSF Scorecard has new Go version requirements that need to be assured. This patch takes care of that.

Updating Go and OSSF Scorecard when already installed patch

---

augur/tasks/github/util/github_paginator.py

1. Add an exception to catch the `RemoteProtocolError`
`RemoteProtocolError('peer closed connection without sending complete message body (incomplete chunked read)')`

Add exception to catch protocol error

---

augur/api/routes/user.py
augur/application/cli/config.py
augur/application/db/session.py
augur/tasks/github/util/github_random_key_auth.py
augur/tasks/util/random_key_auth.py
augur/util/repo_load_controller.py
scripts/control/rebuild.sh
scripts/install/config.sh
tests/test_tasks/test_task_utlities/test_paginators/test_github_paginator.py

1. Changed the cli options for `augur config init` to use dashes in the option names rather than underscores
2. Added a logger to the `RandomKeyAuth` class, so it can log when there are no valid keys. Before it was erroring because someone tried to log this statement using `self.error()`
3. Fixes the regex expressions in the repo load controller to allow for `.github` and `.github.io` repos
**This PR fixes**
1. Error when deleting users. The API to delete a user now deletes all the users repos in the `user_repos` table before deleting the user from the `users` table.
2. Fixed the `user/update` API. Now it returns `missing argument` if either `user` or `password` is `None`, rather than only when `user` is `None`. It also checks to make sure an email or username isn't …

Miscellaneous Fixes to Augur New

---

augur/application/db/util.py

The change fixes a spelling error were `raise Exeption` was used instead of `raise Exception`

fix: `Exeption` is not defined

---

augur/tasks/init/celery_app.py
docs/source/rest-api/spec.yml
metadata.py

- update to API docs to reflect new endpoint for repo-messages.
- Major Fix to redis/celery caching when more than 20,000 repositories are in an instance of Augur

REDIS Patch + api docs update

---

augur/tasks/data_analysis/__init__.py
augur/tasks/init/celery_app.py
augur/tasks/start_tasks.py
augur/tasks/util/worker_util.py

- Remove all use of Celery's result module to match the recent changes to Celery's settings in augur to ignore task results
- Make the task phases make more sense and be scheduled as celery tasks

Remove Uses of Celery.result

---

augur/tasks/github/releases/core.py

Checks for the author field when collecting release info to avoid accessing a null value. Also recorded in the data when the author info is completely null. 
This PR fixes #2038
- [X ] Yes, I signed my commits.

check to not subscript null value for relase info in get_release_inf

---

docker/backend/Dockerfile

The entrypoint.sh script use bash, running with podman return
Jan 09 10:12:24 augur.osci.io podman[2004482]: /usr/bin/env: 'bash': No such file or directory
Signed-off-by: Michael Scherer <misc@redhat.com>

Add bash in the container

---

docker/backend/entrypoint.sh

It seems that for a reason I can't understand (and to be fair, I am not that motivated to go deeply in that rabbit hole), the shebang do not work on podman. Removing /usr/bin/env make it work fine, and since there is almost no reason to see bash move anywhere out of /usr, I think that's safe to just remove env and directly use bash.

Hardcode bash

---

augur/tasks/git/facade_tasks.py

```
Traceback (most recent call last):
File "/home/sean/github/virtualenv/ag3/lib/python3.8/site-packages/celery/app/trace.py", line 451, in trace_task
R = retval = fun(*args, **kwargs)
File "/home/sean/github/virtualenv/ag3/lib/python3.8/site-packages/celery/app/trace.py", line 734, in __protected_call__
return self.run(*args, **kwargs)
File "/home/sean/github/ag3/augur/tasks/git/facade_tasks.py", line 315, in analyze_commits_in_parallel
if (count + 1) % int(len(queue) / 4) == 0:
ZeroDivisionError: integer division or modulo by zero
```

Fixing modulo 0 error:

---

augur/tasks/github/events/tasks.py
augur/tasks/github/releases/core.py
augur/tasks/github/releases/tasks.py

Release fix

---

augur/application/schema/alembic/versions/4_explorer_materialized_view_update.py

Refreshing materialized views, ensuring all needed are present and correct.
```
Traceback (most recent call last):
File "/home/sean/github/virtualenv/ag3/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
self.dialect.do_execute(
File "/home/sean/github/virtualenv/ag3/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
cursor.execute(statement, parameters)
psycopg2.errors.UndefinedTable: relation "augur_data.explorer_commits_and_committers_daily_count" does not exist
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/home/sean/github/virtualenv/ag3/lib/python3.8/site-packages/celery/app/trace.py", line 451, in trace_task
R = retval = fun(*args, **kwargs)
File …
```

committing materialized view to a fresh branch off of dev.

---

augur/api/server.py

This fixes this error:
```
Traceback (most recent call last):
File "/home/andrew/virtualenvs/augur_env/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
response = self.full_dispatch_request()
File "/home/andrew/virtualenvs/augur_env/lib/python3.8/site-packages/flask/app.py", line 1518, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/home/andrew/virtualenvs/augur_env/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
return cors_after_request(app.make_response(f(*args, **kwargs)))
File "/home/andrew/virtualenvs/augur_env/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
rv = self.dispatch_request()
File "/home/andrew/virtualenvs/augur_env/lib/python3.8/site-packages/flask/app.py", line 1502, …
```

Fix Server has no engine error

---

augur/tasks/git/facade_tasks.py
augur/tasks/git/util/facade_worker/facade_worker/facade07rebuildcache.py
augur/tasks/github/facade_github/tasks.py
augur/tasks/start_tasks.py

- Fix issue with facade affiliation data being collected too often
- Change to updates to commits table following contributor resolution

Dev facade fixes

---

augur/tasks/git/util/facade_worker/facade_worker/facade07rebuildcache.py
augur/tasks/start_tasks.py

- Fixes mismatched function call from git merge

Patch mismatched function call

---

scripts/docker/install-workers-deps.sh

Signed-off-by: Michael Scherer <misc@redhat.com>
My previous commit downloaded all nltk data. Upon a closer look, it seems we only need a fraction, hence this fix. 
It do not use the existing script, because 1) it is not interactive 2) it doesn't use python in the venv. The duplication is unfortunante, but I fear that fixing it would mean rewriting the whole installation workflow.

Install only the required nltk data

---

augur/tasks/data_analysis/clustering_worker/tasks.py
augur/tasks/data_analysis/contributor_breadth_worker/contributor_breadth_worker.py
augur/tasks/data_analysis/discourse_analysis/tasks.py
augur/tasks/data_analysis/insight_worker/tasks.py
augur/tasks/data_analysis/message_insights/tasks.py
augur/tasks/data_analysis/pull_request_analysis_worker/tasks.py
augur/tasks/git/facade_tasks.py
augur/tasks/git/util/facade_worker/facade_worker/__init__.py
augur/tasks/git/util/facade_worker/facade_worker/facade01config.py
augur/tasks/git/util/facade_worker/setup.py
augur/tasks/github/contributors/tasks.py
augur/tasks/github/detect_move/core.py
augur/tasks/github/detect_move/tasks.py
augur/tasks/github/events/tasks.py
augur/tasks/github/issues/tasks.py
augur/tasks/github/messages/tasks.py
augur/tasks/github/pull_requests/commits_model/core.py
augur/tasks/github/pull_requests/commits_model/tasks.py
augur/tasks/github/pull_requests/core.py
augur/tasks/github/pull_requests/files_model/core.py
augur/tasks/github/pull_requests/files_model/tasks.py
augur/tasks/github/pull_requests/tasks.py
augur/tasks/github/releases/core.py
augur/tasks/github/releases/tasks.py
augur/tasks/github/repo_info/core.py
augur/tasks/github/repo_info/tasks.py
augur/tasks/init/celery_app.py
augur/tasks/start_tasks.py
scripts/docker/install-workers-deps.sh

- The Facade task, which is used for commit counting in Augur, previously had two functions for "nuking" and "rebuilding" affiliation data inside the commit table. This is a feature no longer required, as it can be replaced with simpler logic, queries, and materialized views if needed. These were also computationally expensive tasks that added limited value. 
- Facade task version bumped to 1.3.0

Deprecating Facade Affiliations Processing

---

augur/application/cli/backend.py
augur/tasks/start_tasks.py

- Added database check to make sure that the ml tasks don't run concurrently 

Fix for ML tasks running without checking if they had been run already 

---

augur/application/cli/backend.py
augur/tasks/start_tasks.py

- Make secondary repo collection hook that schedules fewer messages at once
- Also includes fixes from https://github.com/chaoss/augur/pull/2176

Secondary collection update

---

augur/tasks/init/celery_app.py
augur/tasks/start_tasks.py

- Gave the `refresh_materialized_views` task its own schedule
- Made the task run once a day at 1am (in whatever timezone the server is in)
- I chose 1am so it doesn't slow down the database so much during regular business hours

Refresh materialized views collection frequency patch

---

augur/application/schema/alembic/versions/7_no_null_repo_path_and_repo_name.py

- Fix issue with alembic script having the wrong bind variable name for update statements
- Issue was not caught because it only happens when existing repos have null repo_path or repo_name when upgrading via alembic. 

Syntax Errors in Alembic Script

---

augur/api/server.py
augur/tasks/init/celery_app.py

- Changed workers from using a QueuePool for connections to a StaticPool. The QueuePool contained multiple connections, but this was no longer needed since each process now has its own pool. Therefore I switched each process to use a StaticPool so that each process only has one connection. Now running Augur with default configuration should use about 60 connections. There are still improvements to be made, but I decided to open a pr now since this is a solid improvement

Reduce Db connections

---

augur/tasks/github/messages/tasks.py

- Optimize gh messages collection
- It not makes 1 query to the db when processing the messages rather than 1 query per message
- It also stores the mapping data as a dictionary instead of a list so the pull_request_id or issue_id can be determined in O(1) rather than O(n) time 
- Added more logs when processing the messages
Results: Tested on a repo with 300 pages of messages and the new changes completed messages collection in 341 seconds while dev finished in 520 seconds.

Github Message Task Optimization

---

augur/tasks/github/events/tasks.py

- The processing of events now only makes 1 query to the db rather than 1 query per event.
- When collecting 300 pages (max github will return) of events it took 268 second with the new changes, and 303 seconds with dev. So a 35 second improvement, with far less queries to the database.

Small Optimization to Github Events Task

---

augur/tasks/github/pull_requests/commits_model/core.py
augur/tasks/github/util/gh_graphql_entities.py

- Pr commits was doing a upsert on a per pr basis, now it does 1 bulk upsert for the whole repo. This sped up Augur collection by around 15 seconds which isn't much, but the goal of this change was to reduce the number of database transactions
- Pr files ran into a read timeout exception 16 times during Augur's collection, which added 160 seconds to the 800 second task. I thought this was a bit strange so I looked into it and found that the timeout value of 40 seconds was not being passed to the request so the default timeout of 5 seconds was being used. After changing this there were no more timeouts, which saved 160 seconds on Augur's pr file collection. 

Pr commits and files optimization

---

augur/tasks/github/pull_requests/commits_model/core.py
augur/tasks/github/pull_requests/tasks.py
augur/tasks/start_tasks.py

`augur/tasks/github/pull_requests/commits_model/core.py", line 45, in pull_request_commits_model logger.info(f"{task_name}: Processing pr commit with hash {page_data['sha']}") TypeError: 'NoneType' object is not subscriptable`
`augur/application/db/data_parse.py", line 431, in extract_needed_contributor_data cntrb_id["user"] = contributor["id"] TypeError: 'NoneType' object is not subscriptable`
Also cleaned up augur collection monitor logs

Fix pr commits and reviews collection errors

---

augur/tasks/github/messages/tasks.py
augur/tasks/github/pull_requests/tasks.py

- Bug in github messages when the word `pull` in org or repo name
- Pr review comments was trying to process pr review comments that did not contain a pr review id. It didn't produce errors, but they shouldn't be processed at all

Fixed bugs in messages and pr review comments

---

augur/tasks/git/facade_tasks.py
augur/tasks/git/util/facade_worker/facade_worker/facade02utilitymethods.py
augur/tasks/git/util/facade_worker/facade_worker/facade04postanalysiscleanup.py
augur/tasks/git/util/facade_worker/facade_worker/facade05repofetch.py

- Defined a function called `get_absolute_repo_path` that takes the repo base dir, repo_group_id, repo_path, and repo_name and returns the absolute repo path
- This reduces the chance of defining the repo path wrong throughout the code, since everywhere should use this function to get the path

Define function to get absolute repo path

---

augur/application/db/models/augur_data.py
augur/util/repo_load_controller.py

- Repo Group ID is no longer updated when adding a repo already exists
- Add support for repos that end with `.io`
- Change Repo.insert() method to use `parse_github_repo_url` to get the repo_path and name

Fixes to adding repos from CLI

---

augur/application/cli/backend.py
augur/tasks/git/dependency_tasks/core.py
augur/tasks/git/facade_tasks.py
augur/tasks/git/util/facade_worker/facade_worker/facade05repofetch.py
augur/tasks/github/facade_github/tasks.py
augur/tasks/github/issues/tasks.py
augur/tasks/init/celery_app.py
augur/tasks/start_tasks.py
augur/tasks/util/collection_util.py

- Work towards being able to schedule a predefined load of collection by repo sizes rather than raw repo amount
- Add functions to see how large a repo is respective of its pull_requests and issues
- Split start_tasks.py into two to make it less overwhelming
- Split facade collection into two hooks. One to clone/update, one to collect data. This is done so that in the future similar metrics to the pr/issue metrics to see how large a repo is respective of its commits
- Fix issues with logic when handling dependency errors
- Add new status for facade when it is cloning and updating called 'Initializing'
- Change celery settings to work with newly split start_tasks.py
- Fix issue with sqlalchemy where 'one' was used instead of 'first'.

Changes working towards quantifying repos by their metrics to not overwhelm collection

---

augur/tasks/data_analysis/clustering_worker/setup.py
augur/tasks/data_analysis/insight_worker/setup.py
augur/tasks/data_analysis/message_insights/setup.py
augur/tasks/data_analysis/pull_request_analysis_worker/setup.py
docs/8knot.md
docs/new-install-ubuntu-20.x.md
docs/new-install-ubuntu-22.x.md
readthedocs.yml
setup.py

- Updated installation instructions, differentiating between Ubuntu 20 and 22
- Updated version of Numpy to be compatible with Python 3.8 and Python 3.10
This is being tested on Ubuntu 20 presently, and there are no apparent issues.

Ubuntu 22 and Ubuntu 20 installable Augur

---

augur/tasks/git/dependency_tasks/dependency_util/python_deps.py

Uses abstract syntax tree (AST module) of Python file instead of regex to identify python imports.
also detects submodules.

Python module imports detection patch

---

augur/tasks/git/dependency_libyear_tasks/tasks.py
augur/tasks/git/dependency_tasks/tasks.py
augur/tasks/git/facade_tasks.py
augur/tasks/github/detect_move/tasks.py
augur/tasks/github/events/tasks.py
augur/tasks/github/issues/tasks.py
augur/tasks/github/messages/tasks.py
augur/tasks/github/pull_requests/commits_model/tasks.py
augur/tasks/github/pull_requests/files_model/tasks.py
augur/tasks/github/pull_requests/tasks.py
augur/tasks/github/releases/tasks.py
augur/tasks/github/repo_info/tasks.py
augur/tasks/init/celery_app.py

- Add base classes for repo collection tasks that override the on_failure method of the Task celery class
- Change several facade related tasks to take a repo_git instead of a repo_id

Fix celery error handling to set repo's collection status to error when error encountered

---

augur/tasks/git/dependency_tasks/dependency_util/python_deps.py

Fixed issue with python dependency analysis where versions older than python 3.4 couldn't be parsed. This was because the current version of python's ast (abstract syntax tree) module only supports versions greater than or equal to 3.4. The new method used uses a simple regex to find dependencies if issues are encountered using the ast method. 

Add exception handle in dependency analysis to use regex if ast can't be used due to version 

---

augur/tasks/github/detect_move/core.py
augur/tasks/github/detect_move/tasks.py
augur/tasks/init/celery_app.py

- Fix syntax issue where detect_github_repo_move_secondary had a base task class of AugurCoreRepoCollectionTask instead of AugurSecondaryRepoCollectionTask. 
- Fix logic error where some repos would be marked as errored when a new host is found for them through a Github api endpoint

Fix wrong base class assignment and make sure repos don't get marked as errored when a new host is found

---

augur/tasks/init/celery_app.py

- Fix typo in on_failure logic. repoStatus not repoS

fix typo in on_failure logic

---

augur/application/schema/alembic/versions/12_traffic_additions.py

Inclusion of the drop sequence command for backward migration.

Test traffic into dev

---

augur/application/cli/backend.py

- Now when augur collection is told to stop it uses curl to send http requests to the local rabbitmq instance to explicitly delete the message queues that that instance was using. 
Note: for this change to do anything it requires the rabbitmq_management plugin and for the augur user to have the administrator tag otherwise behavior is unchanged. 

Fix issue with celery rabbitmq messages not getting cleared with celery_app.control.purge()

---

augur/tasks/github/releases/core.py

Fix wrong function call in releases task. Function was changed to not take a session and instead take oauth and a logger but function call was not updated appropriately. 

Fix inconsistent changes to function call 

---

augur/tasks/git/dependency_libyear_tasks/libyear_util/pypi_libyear_util.py
augur/tasks/git/dependency_libyear_tasks/libyear_util/util.py
augur/tasks/github/releases/core.py

- Fix typo similar to previous issue where methods that used to take a session now take a logger and a key_auth object instead but the change was not made correctly universally. 
- Delete unused variable in libyear logic
- Stop libyear logic from trying to parse an empty date.
- Handle issue where regex was encountering empty string. 

Dev bugfixes 

---

augur/application/db/models/augur_data.py

- Made all the repo urls that get added to the database lowercase, so that mixed casing doesn't allow duplicate repos to be added

Fix duplicate repos caused by mixed casing

---

augur/tasks/git/facade_tasks.py
augur/tasks/github/contributors/tasks.py
augur/tasks/github/facade_github/contributor_interfaceable/contributor_interface.py
augur/tasks/github/facade_github/core.py
augur/tasks/github/util/github_paginator.py
augur/tasks/start_tasks.py

- Move the grab_committers task out of the facade collection hook. This is done because it was slowing down the rest of facade collection and because the task doesn't rely on commit data. The facade collection hook should really be reserved for tasks that directly relate to facade commit data.
- Improve grab_committers task to use GithubTaskManifest instead of GithubTaskSession which is in the process of being deprecated. 
- Improve grab_committers task to use new retrieve_dict_from_endpoint method instead of request_dict_from_endpoint method which is in the process of being deprecated.
- Create retrieve_dict_from_endpoint method that is more uniform with the rest of how augur now paginates the github REST api. This method is better because it checks the validity of …

Move github contributors query outside of facade collection hook

---

augur/application/cli/_multicommand.py

- Changed the invalid command exception, so that it no longer prints out the entire stack trace when a user enters an invalid command

Remove stack trace print from invalid command output

---

augur/api/view/api.py
augur/templates/settings.j2

- Added the ability to add repos and orgs at the same time on the frontend
- Added the ability to add orgs by simply specifying the name, and repos by entering {org_name}/{repo_name}
- The text input has been changed to a text area to allow for multiline input
- The orgs and repos can be delimited by carriage returns, commas, spaces

Add orgs and repos at same time

---

augur/application/db/models/augur_data.py

- The `Repo.insert()` method takes a url to add to the repo table. Sometimes this url has a `/` at the end and sometimes it doesn't (based on what the user puts in). This means there can be a duplicate repo in the table (one with slash an one without). With this I simply added a 2 lines to remove the forward slash if it exists.

Remove '/' from end of url when inserting repo

---

augur/application/cli/backend.py

- Running `augur backend stop`, `augur backend kill` or `cntrl-C` on an instance of augur that had collection disabled was causing an error because it was trying to purge the celery queue even though celery was never started. 
- To fix this I added a check if collection is disabled when running `cntrl-C`, and for `stop` and `kill` I added a check to see if there are any celery processes running before purging the queues
This pr fixes issue #2299 

Fix celery error when augur is stopped without collection running

---

augur/application/db/data_parse.py
augur/tasks/github/messages/tasks.py
augur/tasks/github/pull_requests/tasks.py

- Fix contributor NoneType error that is shown below
`Traceback (most recent call last):
File "/home/sean/github/rh-k12/augur/tasks/github/pull_requests/tasks.py", line 242, in collect_pull_request_review_comments
contributors.append(process_github_comment_contributors(comment, tool_source, tool_version, data_source))
File "/home/sean/github/rh-k12/augur/tasks/github/messages/tasks.py", line 224, in process_github_comment_contributors
message_cntrb = extract_needed_contributor_data(message["user"], tool_source, tool_version, data_source)
File "/home/sean/github/rh-k12/augur/application/db/data_parse.py", line 431, in extract_needed_contributor_data
cntrb_id["user"] = contributor["id"]
TypeError: 'NoneType' object is not subscriptable`

Fix pr review message error

---

augur/application/db/models/augur_data.py
augur/application/db/models/augur_operations.py

- Fill the `repo_type` column in the repos table based on whether the repo is a part of org, or attached to a user
This completes this issue #1650 

Fill the repo_type column in the repos table

---

augur/application/db/models/augur_data.py
augur/tasks/github/facade_github/contributor_interfaceable/contributor_interface.py
augur/tasks/github/facade_github/tasks.py
augur/tasks/github/pull_requests/tasks.py

Update contributor resolution logic to be cleaner and more testable. Also now uses less deprecated functions overall. GithubTaskSession is no longer used now in favor of a GithubTaskManifest that passes its attributes.

Update contributor logic to be more testable and uniform

---

augur/application/db/models/augur_data.py
augur/application/db/models/augur_operations.py
augur/tasks/github/util/github_paginator.py
augur/util/repo_load_controller.py

- You can now add all of a users repos at once instead of only being add orgs.
- For example if I wanted to add all my public repos. I can now put `ABrain7710` in the text box on the frontend, hit add, and all of my public repos will be added.
- This also updates the CLI so it inserts the `repo_type` when adding repos
- The regex that parses the repo url has been changed to allow periods anywhere in the repo name. At first I thought only certain extensions were allowed at the end of repo names, but after coming across a few weird ones. I came to the conclusion that they are allowed anywhere in the repo name when I was able to create a repo with the name `a.b.c.d.e`

Add ability to add all of a users repos and update CLI with new features

---

augur/application/schema/alembic/versions/7_no_null_repo_path_and_repo_name.py

- The repo path and repo name are not correct in the seed data. I figured out that it was because the regex in the 7th migration was not capturing the repo path and repo name correctly, so I changed it to use the standard function that gets the repo owner and repo name. Then I constructed the repo path with the repo owner

Fix seed data so repo path and repo name are correct

---

augur/application/cli/backend.py
augur/tasks/init/celery_app.py

- Facade tasks should be placed in a separate pool of processes than the core tasks because a significant portion of the facade tasks do not require GitHub API calls to work. Before, the core tasks would hog all the processes because they were sleeping due to rate limit error handling.
- Create an extra celery worker to handle facade tasks along with a respective rabbitmq queue. 
- Amend function to clear rabbitmq queue to also now clear the new facade queue
- Amend celery routing to route all facade tasks to be routed to the facade worker. 

Stop facade being bottlenecked by core worker processes

---

augur/api/routes/application.py
augur/api/routes/complexity.py
augur/api/routes/config.py
augur/api/routes/contributor_reports.py
augur/api/routes/manager.py
augur/api/routes/nonstandard_metrics.py
augur/api/routes/user.py
augur/application/db/session.py
augur/tasks/git/dependency_libyear_tasks/core.py
augur/tasks/git/dependency_libyear_tasks/libyear_util/npm_libyear_utils.py
augur/tasks/git/dependency_tasks/core.py
augur/tasks/git/facade_tasks.py
augur/tasks/start_tasks.py
augur/tasks/util/collection_util.py

Several modules imported json without using it (or, in one case, imported twice).
I checked the import manually and check no usage of json was counting on implicit import. However, this was manually done, and until there is a automated testing, errors can happen.

Remove unused import of json module

---

augur/tasks/git/dependency_tasks/dependency_util/dependency_calculator.py

Handle edge case where repository finds a language file in the path listing via a regex query and is then unable to open that same file because of a *FileNotFoundError* exception. 

Handle when repo has a dependency file that cannot be found

---

augur/api/gunicorn_conf.py
augur/api/view/routes.py
augur/application/db/models/augur_operations.py
augur/templates/groups-table.j2
augur/templates/navbar.j2
augur/templates/settings.j2
augur/templates/user-group-repos-table.j2
augur/util/repo_load_controller.py

- Enable reload detection for jinja templates in gunicorn config
- Add user groups frontend view
- Fix user group view parameter smashing
- Add get_groups_info function on User class to auto-collate data
- Add search parameters to group repo count
- Update groups-table template to work with user groups
- Add groups view to navbar
- Update groups table in profile to handle new groups table page
- Update user-group-repos-table template
- Fix sorting with NULL values on repo columns
Co-authored-by: Andrew Brain <andrewbrain2019@gmail.com>
Signed-off-by: Ulincsys <28362836a@gmail.com>

Frontend groups view improvements

---

augur/tasks/git/util/facade_worker/facade_worker/repofetch.py

- When a repo failed to clone, Facade was setting the status to 'Failed Clone', but not updating the facade task id to NULL

Fix facade update that violates collection status constraint

---

augur/tasks/start_tasks.py
augur/tasks/util/collection_util.py

I kept seeing this in the logs
`2023-04-21 14:48:06 augur_collection_monitor[1466426] INFO Starting new collection on core: 7 repos        
2023-04-21 14:48:06 augur_collection_monitor[1466426] INFO Starting new collection on core: 0 repos`
and it was really confusing me because I thought the augur collection monitor was being started twice, but I couldn't figure out where it was being ran a second time. Eventually I figured out that one of these logs is how many new core repos are being started and how many old core repos are being started. So I updated the code to print which type of repos were being started.

Fix confusing log statement

---

augur/application/cli/backend.py
augur/tasks/git/facade_tasks.py
augur/tasks/start_tasks.py
augur/tasks/util/collection_util.py

Append Augur's collection hooks to update the weight after collection has finished. Core, facade, and secondary collection hooks now update the weight of the repo after they complete and populate the last_collected timestamp. 
This PR Fixes #2342

Make sure weight is updated after collection is completed for each collection hook 

---

augur/application/cli/backend.py

- The `facade_worker_process` variable was only defined if running collection, otherwise it resulted in this error
`UnboundLocalError: local variable 'facade_worker_process' referenced before assignment`.
- Also there was this typo `facade_worker_process,terminate()` which should be`facade_worker_process.terminate()`

Fix syntax errors in backend.py

---

augur/tasks/start_tasks.py

Add a restriction to repository collection when collecting old repositories; disallow repositories that have already been collected from being collected again until a day has passed since it was last collected 
This PR fixes #2349

Add a delay of a day before collecting repositories again

---

augur/tasks/git/facade_tasks.py
augur/tasks/start_tasks.py
augur/tasks/util/collection_util.py

Move facade logic to update repository via a 'git pull' when collection is scheduled instead of in the clone phase. This is to ensure that the repository is up to date prior to collecting the repository again. This is needed following the changes to how scheduling works with the weighting changes. 

Move update logic to facade collection

---

augur/tasks/start_tasks.py

- Currently facade initialization tasks are not being scheduled often enough to ensure there are always repos available to be collected by the facade collection tasks. To solve this, @IsaacMilarky and I came up with a solution that limits the number of cloning tasks and collection tasks we start based on the number of each task we start rather than just saying a specific number of repos for each can run. This is best explained with examples.
For example. 
Say there are 500 repos ready to be cloned. This is what the augur collection monitor would start each minute, assuming that all the clones finished in the minute, and the collection tasks also finished. If they didn't, then less tasks would be scheduled
1. 108 cloned 0 collected
2. 108 cloned 21 collected
3. 108 cloned …

Make facade scheduling dynamic 

---

augur/tasks/git/util/facade_worker/facade_worker/repofetch.py

Add an update query to facade to handle the case when an existing repo path is found but the repo's record shows a path of null. This way the path is always updated to the path the repo has been cloned to. 

Handle edge case facade NULL error

---

augur/tasks/start_tasks.py

- Forgot to multiply the collecting repo count by 12 when reducing the available pipe space 

Facade scheduling patch

---

augur/tasks/git/util/facade_worker/facade_worker/utilitymethods.py

- An error occurs in get_repo_commit_count when the repo is empty (.git doesn't exist)
`Traceback (most recent call last):
File "/home/sean/github/rh-k12/augur/tasks/git/util/facade_worker/facade_worker/utilitymethods.py", line 156, in get_repo_commit_count
check_commit_count_cmd = check_output(["git","--git-dir",repo_loc, "rev-list", "--count", "HEAD"])
File "/usr/lib/python3.8/subprocess.py", line 415, in check_output
return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
File "/usr/lib/python3.8/subprocess.py", line 516, in run
raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['git', '--git-dir', '/mnt/data/repopadre/25478/github.com/apache/incubator-guacamole/.git', 'rev-list', '--count', 'HEAD']' …

Fix commit count task error

---

augur/tasks/init/celery_app.py

- Set update weight task to run once a day rather than every 2 days since the weight can change a lot in 2 days
- This is something @IsaacMilarky and I discussed previously but it never got changed

Update weight scheduling to once a day

---

augur/application/cli/backend.py
augur/application/schema/alembic/versions/17_add_collection_status_constraints.py
augur/tasks/git/facade_tasks.py
augur/tasks/git/util/facade_worker/facade_worker/utilitymethods.py
augur/tasks/init/celery_app.py
augur/tasks/start_tasks.py

- Simplify facade collection scheduling by running the cloning task for all the repos that need cloning. Then scheduling the cloning task 5 minutes after all of them are finished to see if there are any new ones
Note: The facade clone task only gets one repo at a time to initialize so more than one of the task can run at the same time if a clone task is taking more than 5 minutes

Simplify facade collection process

---

augur/tasks/git/util/facade_worker/facade_worker/utilitymethods.py

- The previous solution to fix the commit count task when running on empty repos did not work. This solution checks the number of branches in the `.git` directory. If there are no branches then the repo has no commits because there is no HEAD

Fix commit count task

---

augur/tasks/git/facade_tasks.py
augur/tasks/git/util/facade_worker/facade_worker/repofetch.py

- Currently if one of the repos fails to clone the clone task errors, and the clone repos task is never scheduled again
- I added a custom exception that it raised when a clone fails, and if this error is raised, the clone repos task catches it and continues to the next repo
- I also added retry logic to the clone repos task. So if any other unpredictable errors such as network errors occur, it will retry in 5 minutes. Also these errors are logged to flower in the reties tab so we will still know if there are frequent errors happening in the task, that need to be patched

Fix bug in repo clone task

---

augur/application/config.py

- Change default collection interval to 30 seconds because we are scheduling the smallest repos first. Which means many of the smallest repos are finishing before the 60 seconds is up, which creates downtime on the celery worker process. To reduce the chance for downtime while not adding a lot of messages to the queue I reduced to frequency that we check for new repos to collect

Change default collection interval to every 30 seconds

---

augur/tasks/start_tasks.py

- Change the max number of secondary repos to 10 instead of 5 because we are scheduling the smallest repos first. Which means many of the smallest repos are before the collection monitor runs again, which creates downtime on the celery worker process. So raising the max number of repos to 10 for the secondary repo tasks will make sure more repos are being repos when the tasks are flying because they are such small repos

Increase max secondary repos to 10

---

augur/tasks/git/dependency_tasks/core.py
augur/tasks/github/util/github_api_key_handler.py

- The ossf scorecard task was using the github api located in the database config to run the scorecard process. The problem with this is that it ran that Github API key out of requests very quickly and left a bunch of scorecard tasks in the queue waiting for the API key to get more requests. Now the task gets a random API key from the list of keys and runs with that one so that no one key is overwhelmed. This also effected other Github tasks because the ossf scorecard task would run out that one Github API key before all the others, so the other Github tasks that randomly selected that key would sleep until it gets more requests.
Note: This is why we were seeing a bunch of scorecard tasks all of a sudden taking a super long time to run

Fix issue in ossf scorecard with Github API keys

---

augur/tasks/start_tasks.py

- Facade collection wasn't taking into account active repos so it was just scheduling more and more collection jobs every time the monitor ran

Fix facade collection limit

---

augur/application/cli/backend.py
augur/application/db/models/augur_operations.py
augur/application/schema/alembic/versions/17_add_collection_status_constraints.py

- The clean collection status was setting all facade statuses to `Update` if they were collecting. So I changed it so that it sets the status to `Update` if the repo hasn't been collected yet, and `Success` if the repo has been collected before. The goal of this is to reset it to the status it had before it started collecting.So if a repo is collecting and doens't have a collection date then its status was update beforehand, and if it is collecting and has a collection date it must be recollecting meaning that it had a status of 'Success' before. 
To fix this I updated the clean collection status to achieve this behavior, and I also added a check constraint to ensure that a repo is never set to update when it has a facade collection date 

Fix clean collection status

---

augur/tasks/init/celery_app.py

- The `collect_pull_request_review_comments' task is causing the secondary worker to stall. This is because it is scheduled in the core worker, but it is scheduled in the `secondary_tasks`. Essentially what happens is the secondary worker finishes all the other secondary tasks, but then the core worker is backed up with core jobs, so the `collect_pull_request_review_comments` doesn't make it through. This causes no more secondary tasks to be scheduled until the `collect_pull_request_review_comments` tasks get to the front of the core worker queue, effectively stalling the secondary worker. To fix this, I changed the `collect_pull_request_review_comments` task to be scheduled in the secondary worker.

Route pr review comments to secondary worker

---

augur/tasks/start_tasks.py

- The secondary and facade collections were being recollected based on the `core_data_last_collected` date. Instead of the `secondary_data_last_collected` and `facade_data_last_collected`

Fix scheduling of old repos

---

augur/tasks/git/facade_tasks.py

Fix issue where repos were not getting marked as failed when cloning them via git fails. 

make sure status of repo is updated when the cloning fails

---

augur/tasks/git/facade_tasks.py

Fix strange indentation in the facade analyze_commits method. I think this was caused by some weird git merge that didn't conflict but was not what we wanted. Before this change facade was working but it wasn't logging its progress correctly. 

Fix facade indentation issue

---

augur/tasks/git/facade_tasks.py

- Add error handling logic to the clone_repos method to handle errors that don't have to do with problems with running 'git clone'. 
- Add exception handle for general cases to set the repo to 'Error' when the repository can't be initialized for facade for unknown reasons.
This PR fixes #2401

Improved error handling when cloning repositories 

---

augur/api/view/api.py
augur/application/db/models/augur_operations.py
augur/tasks/github/util/github_api_key_handler.py

- I came across these issues when I saw the frontend flash that a repo was added, but it actually wasn't. The issue was that I had no valid Github API keys. To fix this issue, I made the Github API key handler raise a `NoValidKeysError` when there are no valid github api keys. This improves the case when all the Github API keys are expired or invalid, because it now raises an exception rather than just silently not working. 
- Now in the add repo and add org code it catches NoValidKeysError and returns False so the frontend shows that the repos weren't added
- I also came across an issue in the view code, where it wasn't unpacking a tuple before checking if the repo or org was added. This issue is why we were always see it flash that the repos were added even it they …

No valid Github API keys fix

---

augur/tasks/github/util/github_paginator.py

- This endpoint, `https://api.github.com/repos/{owner}/{repo}/contributors?state=all`, which is used in `grab_commiters` returns a `204 No Content` status and an empty string when there are not contributors. This was causing the response to be processed as a string, and a warning was logged because it was unable to be processed. Now if a `204 No Content` status is returned by the Github API then all an empty list is returned with a status of `Success`

Handle GitHub API 204 response

---

augur/application/cli/backend.py

- Reduce/Increase the amount of processes celery is allowed to use depending on the amount of available memory on the system. Data is gathered with psutil
- Hard cap the maximum amount of processes for each worker process to the previous default values
These changes should help to preserve some memory on systems with smaller amounts of it without hampering collection on larger memory instances. 

Scale celery memory use to system's available memory

---

augur/application/cli/backend.py
augur/application/config.py
augur/application/schema/alembic/versions/19_add_extra_celery_options_to_the_config_.py
augur/tasks/init/celery_app.py

- Add default options to the config so users can set caps on celery worker memory usage as well as how often materialized views are refreshed. 
- Default values are 7 days to refresh the materialized views and 0.25 (25%) for the virtual memory cap
- Add alembic script to handle updating existing configs to have the new options

Add config options for memory usage and frequency of refresh materialized views

---

augur/api/view/api.py
augur/application/db/models/augur_operations.py

- Updated repo group creation so it makes the repo groups always lower case
- Update add repo/org route so that it makes everything lowercase before processing them
I made both changes for double protection against incorrect casing

Repo group casing fix

---

docs/new-install.md
docs/new-install.rst

Adds some critical installation steps to `new-install.md` and `new-install.rst`:
- create an SSL connection to the database for `make install` to access
- add PostgreSQL 15+ privileges to `augur` user
- start RabbitMQ server systemd service
- address AVX instruction error when in a VM under Windows (an issue with Hyper-V)

[docs] Address missing installation details

---

augur/application/db/models/augur_data.py
augur/tasks/git/dependency_tasks/tasks.py
augur/tasks/github/repo_info/core.py
augur/tasks/github/repo_info/tasks.py
augur/tasks/init/celery_app.py
augur/tasks/start_tasks.py

- Add a new task called collect_linux_badge_info that collects the data the linux badge worker used to
- This task is in the same file as the repo_info task because it collects misc info about the repo
- The only reason it is in its own task is because it relies on both github and the CII api.
- Add an orm method to insert badge data.
Link to the old badge worker code: https://github.com/chaoss/augur/blob/old-main/workers/linux_badge_worker/linux_badge_worker.py

Add old linux badge worker functionality back to augur

---

docs/new-install.md
docs/new-install.rst

The new install guide does not actually explain most of the prompts generated in the install script. It also claims the user is expected to input their own passwords which is (a) not true and (b) cause for users' concern.
This commit explains all the prompts and removes any notion of plaintext GitHub/GitLab passwords.

[docs] Clarify prompts during `make install`

---

augur/tasks/github/facade_github/tasks.py

- Update contributor upsert to use the cntrb_id as the unique instead of the cntrb_login

Contributor upsert fix

---

augur/tasks/github/detect_move/core.py

- ping_github_for_repo_move now updates timestamp of the corresponding collection hook when a 404 happens
- This is to prevent 404 repos from showing up as much older than they actually are 

Fix timestamp not being updated when repo collection fails because of 404

---

augur/tasks/util/worker_util.py
docs/new-install.md

This fix addresses a couple of spelling typos in the docstring of the remove_duplicate_dicts function.
Background: I'm doing a research study on function comments that may be incorrect. You can find more info and a short and optional anonymous survey [here](https://forms.office.com/e/yHv4PRXM2i).
Thanks for reviewing!

Fix typos in docstring for remove_duplicate_dicts

---

augur/tasks/git/dependency_libyear_tasks/core.py

Fixed lack of uniformity in method of retrieving correct path to cloned repos in process_libyear_dependency_metrics 

Fix lack of uniformity in getting path for cloned repositories 

---

docs/source/login.rst

- add note about using AUGUR_DEV envvar to allow localhost clients (i.e. to disable SSL enforcement)
- remove Augur View and docs terminology disparity
- fix "acquired" typo
In my opinion, the SSL issue should be met with a backend change. Assuming Augur is running with HTTPS support, enforcing SSL *into* Augur is a good idea, but enforcing it *out of* Augur appears to be why localhost clients don't work. The redirect back to the user's client application at http://127.0.0.1 fails SSL enforcement silently, responding with (non-existent) temporary authorization code "undefined". Should I make a GitHub issue for this?

[docs] Clarify OAuth flow documentation

---

augur/api/routes/user.py
augur/application/db/models/augur_operations.py

Refreshing session tokens first loads the authenticated client application from a SQL query, then verifies it against the user's browser session, and finally refreshes the token. The verification step uses a simple inequality check between two `ClientApplication` objects. Because this class does not have a definition for (in)equality (i.e. the `__eq__` and `__ne__` methods are not implemented), that inequality only checks the objects' pointers/addresses*, which is guaranteed to fail. Thankfully, the `ClientApplication` class has an `id` field which matches the primary key in the associated database row. Comparing the underlying hex string values should make correct equality checks. This PR's main change is a simple implementation of `__eq__` for `ClientApplication` as …

[auth] Fix session token refresh

---

augur/tasks/git/dependency_tasks/core.py
augur/tasks/git/dependency_tasks/tasks.py

Fixed out of date method for getting absolute directory of a repository in the deps_model. Now uses the same method that facade and everything else that needs to get an absolute directory of a cloned repo should use. 

Fix old and bad method of getting absolute directory for cloned repos for the main dependency task

---

augur/tasks/github/issues/tasks.py

- Bug where the issue user's cntrb-id is assigned to all the issue assignee rows

Fix issue assignees being wrongly assigned the issue user's cntrb_id

---

augur/tasks/git/dependency_tasks/dependency_util/kotlin_deps.py
augur/tasks/git/dependency_tasks/dependency_util/rust_deps.py

Change names of rust and kotlin dependency calculator functions to be uniform with the rest of the task.

Wrong name in dependency metric modules

---

augur/application/cli/backend.py
augur/application/config.py
augur/application/schema/alembic/versions/25_unique_on_mataview.py
augur/tasks/db/refresh_materialized_views.py
augur/tasks/github/issues/tasks.py
augur/tasks/github/repo_info/core.py
augur/tasks/github/util/github_api_key_handler.py
augur/tasks/github/util/github_random_key_auth.py
augur/tasks/start_tasks.py
augur/tasks/util/random_key_auth.py
augur/tasks/util/redis_list.py

- Use of API keys was not being rotated, and so jobs were getting stuck.
- This PR fixes the glitch.
- This PR now also fixes an old issue with how the commit_count was retrieved by the repo_info task. Previously we selected a `main` branch. The new code gets the `default branch`. I have verified that where commits were getting stored in the metadata as NULL in ~25% of cases, and there are 5-10% of repos in any augur collection where `main` is not the default branch. Using the default branch always get commit_count data correctly. NO more NULL values. No more counting the "not default branch".
- This PR now also fixes the refreshability of materialized views by adding unique keys on all but one, and enabling concurrent refreshes on all but one. It also removes 3 libyear …

Updated key rotation to be more random

---

augur/application/db/models/augur_operations.py
augur/tasks/db/refresh_materialized_views.py

Various bug fixes and optimizations

Release PR

---

augur/static/css/stylesheet.css
augur/templates/settings.j2

- Include table-responsive class on table container divs
- Enables these tables to become scrollable if the content is too long

Fix tables on user settings page clipping past end of column

---

augur/tasks/github/events/tasks.py

- Added sql queries to populate issue closed contributors with issue event data
- This will not completely fix #2524 but it should get all of the closed contributors on smaller repos and a lot on larger repos

Add sql to update closed issue cntrbs with closed issue event data

---

docker/backend/Dockerfile
docker/backend/entrypoint.sh
docker/backend/init.sh

ENTRYPOINT is made to be used when the container is running one specific executable (think bash, or python) and is hard to override. However, when using the container, it is sometime needed to execute specific subcommand, such as augur db upgrade-db-version

Split ENTRYPOINT script in 2

---

augur/tasks/start_tasks.py

So the current issue is that repos are allowed to be recollected if they are more than a day old. This is causing issues in datasets where one user has the majority of the repos and there are many other users that have small amounts of repos. For example in a dataset where one user has 20000 repos and 19 other users all together have 2000 repos. In this case the single user with a lot of repos only has a 25% chance of being selected by the scheduling algorithm (in fact all users have a 25% chance). The issue is that the other 19 users have enough repos that there are always some repos that are more than 1 day old and therefore can be recollected. This results in the 20000 repos from the single user only being considered 25% of the time even if some of their repos are 3 …

Update recollection frequency

---

augur/application/db/models/augur_data.py
augur/tasks/git/facade_tasks.py
augur/tasks/git/util/facade_worker/facade_worker/analyzecommit.py
augur/tasks/git/util/facade_worker/facade_worker/facade00mainprogram.py
augur/tasks/git/util/facade_worker/facade_worker/rebuildcache.py
augur/tasks/git/util/facade_worker/facade_worker/repofetch.py
augur/tasks/git/util/facade_worker/facade_worker/utilitymethods.py

- Change trim_commits phase of facade to trim commits in bulk instead of one at a time. Before, commits were deleted one at a time.
- Change analyze_commits_in_parallel phase of facade to insert commits in bulk instead of one at a time. Before, more database transactions were used than desirable.
- Implement a stagger insert that inserts a block of facade records when the amount of objects in memory exceeds 10000. 

Use Bulk Inserts in Facade Collection Instead of Single Inserts

---

augur/tasks/github/events/tasks.py

- The issue events that are providing the issue closed cntrb for the issues table can have NULL cntrb ids. So when we retrieve the issue closed cntrb we get back NULL, and when we try to bind NULL to the update query it fails and throws an error. Now we are filtering out rows that have a NULL cntrb id since they are not useful and are causing an error
This is the error in the logs
```2023-10-18 15:34:01 linda collect_events[636720] ERROR Could not collect events for https://github.com/pentaho/pentaho-hdfs-vfs
Reason: (sqlalchemy.exc.InvalidRequestError) A value is required for bind parameter 'cntrb_id'```

Fix null cntrb id errors in issue closed cntrb update

---

augur/tasks/git/dependency_tasks/tasks.py
augur/tasks/git/facade_tasks.py
augur/tasks/github/facade_github/tasks.py

There was a syntax issue previously where some celery tasks had the wrong base class. This can happen because a task was moved and not properly updated with the right base class.

Fix Wrong Base Classes for Celery Tasks

---

augur/api/metrics/pull_request.py
docs/source/rest-api/spec.yml

- This PR is adds a `pull_requests_new` API endpoint, which aligns with the existing endpoints for issues and contributors. This new feature allows users to retrieve time series data on the number of new PRs opened within a specified time frame for a given repository. 
This PR addresses #2542 

[API] add pull_requests_new endpoint to get time series of new PRs opened

---

augur/application/db/models/augur_data.py
augur/application/db/models/augur_operations.py

- Fixed orm warnings by adding the correct back_populates on each relationship
NOTE: I thought about adding back_populates to all the relationships so we have them in the future, but I decided to keep this pr small and only add the ones that were showing warnings. I'll likely add the rest in the future

Fix orm warnings

---

augur/api/routes/dei.py
augur/api/routes/user.py
augur/api/view/api.py
augur/application/db/models/augur_data.py
augur/application/db/models/augur_operations.py
augur/tasks/frontend.py
augur/tasks/gitlab/gitlab_api_key_handler.py
augur/tasks/gitlab/gitlab_random_key_auth.py
augur/tasks/gitlab/gitlab_task_session.py
augur/tasks/util/collection_util.py
augur/util/repo_load_controller.py
tests/test_applicaton/test_db/test_models/test_augur_data/test_repo.py
tests/test_applicaton/test_db/test_models/test_augur_operations/test_user_repo.py

- Adds the ability to add Gitlab repos from the frontend. This includes changes to insert the record into the database, and changes to ensure that the Gitlab repos are ignored. The collection status record is also created, but currently the issue_pr_sum, commit_count, and weights are incorrect since that logic still needs to be implemented with the gitlab api

Implement ability to add gitlab repos from frontend

---

augur/application/cli/backend.py
augur/application/db/data_parse.py
augur/application/db/models/augur_operations.py
augur/tasks/github/pull_requests/tasks.py
augur/tasks/github/util/util.py
augur/tasks/gitlab/gitlab_api_key_handler.py
augur/tasks/gitlab/gitlab_paginator.py
augur/tasks/gitlab/issues_task.py
augur/tasks/gitlab/merge_request_task.py
augur/tasks/init/celery_app.py
augur/tasks/start_tasks.py
augur/tasks/util/collection_util.py

- Adds collection tasks for gitlab merge requests and issues. This only adds collection for the pr and issue table. I'll add collection of there metadata such as events, assignees, and other stuff later

Add gitlab merge request and issue collection

---

docs/source/getting-started/new-install.rst

This fixes the issue that the installation guide can no longer be followed verbatim.
Here is what `apt-cache` tells me on my machine:
```
$ sudo apt-cache policy firefox
firefox:
Installed: 121.0~b7+build1-0ubuntu0.22.04.1
Candidate: 1:1snap1-0ubuntu2
Version table:
1:1snap1-0ubuntu2 500
500 http://mirrors.digitalocean.com/ubuntu jammy/main amd64 Packages
*** 121.0~b7+build1-0ubuntu0.22.04.1 500
500 https://ppa.launchpadcontent.net/mozillateam/firefox-next/ubuntu jammy/main amd64 Packages
100 /var/lib/dpkg/status
```
I discovered this new version by first failing to install the said version of `firefox`. Then, when trying to first install `firefox-geckodriver`, I discovered this version.

[docs] Update firefox version to match requirement of firefox-geckodriver

---

augur/api/routes/util.py
docs/source/rest-api/spec.yml

Documentation also written for this, though I'm not 100% sure "object" is a valid type. It definitely doesn't return an array.
- Adds a utility endpoint to query a single repository. Contains much the same information as the /repos endpoint, but instead of returning an array of repositories, only one is returned. If the SQL read fails or no repository with the given ID is found, returns a 400.
I am told this functionality used to exist by using the special repo group ID 9999, and code using this feature [is still in Augur](https://github.com/chaoss/augur/blob/main/augur/tasks/data_analysis/insight_worker/tasks.py#L62), but that endpoint has been a 404 for as long as I have known Augur.
As usual, I also cleared linter warnings along the way (module-level import not at top …

[api] Add endpoint to get repo by ID

---

.github/workflows/checks.yml

- Add GitHub workflow to run reviewdog and annotate with relevant linters and checkers 
- When a PR is created into either dev or main, pylint checks are ran and annotated on that PR for review
- The only files considered are the ones that contain changes to not be overwhelming
I decided on Pylint because it's not that strict of a linter. We should consider how strict we are willing to be on linting and checking in general in the future as reviewdog supports many tools. Some good linting alternatives are listed in the readme for the [reviewdog repo](https://github.com/reviewdog/reviewdog)
We can also automatically force new PRs to follow PEP8 but that might be overkill. 

Use Reviewdog to Annotate PRs with Pylint and Spellcheck 

---

augur/tasks/github/messages/tasks.py
augur/tasks/github/releases/core.py
augur/tasks/util/worker_util.py

- Fixed none type error in messages collection fixed
- Fixed releases insert when null characters are present
- Fixed syntax error

Fix a few small collection issues

---

augur/application/db/session.py

- Fix issue where we fail to retry inserting data in smaller chunks if an error occurs during insertion. This is why we have been getting errors like this when we see database errors like this one
- I also added a 3 second sleep just in case the error is temporary
```  File "/home/sean/github/rh-k12/augur/tasks/util/worker_util.py", line 69, in <listcomp>
key = "_".join([str(x[unique]) for unique in uniques])
KeyError: 'pull_request_id'```

Fix retry insert data issue

---

.pylintrc
augur/api/view/routes.py
augur/api/view/utils.py
augur/application/db/data_parse.py
augur/tasks/github/pull_requests/tasks.py
augur/tasks/github/util/util.py
augur/tasks/gitlab/events_task.py
augur/tasks/gitlab/gitlab_api_handler.py
augur/tasks/gitlab/gitlab_api_key_handler.py
augur/tasks/gitlab/gitlab_random_key_auth.py
augur/tasks/gitlab/gitlab_task_session.py
augur/tasks/gitlab/issues_task.py
augur/tasks/gitlab/merge_request_task.py

- Added module doc-strings to data_parse.py
- Removed unneeded parameters from various methods
- Removed unused variables
- Fixed some minor import issues
- Document GitLab task structures 
- Add linting compliance to various files 

Fix Pylint Errors in Dev

---

Makefile
README.md
docker-compose-externalDB.yml
docker-compose.yml
docker/rabbitmq/Dockerfile
docker/rabbitmq/augur.conf
scripts/docker/docker-setup-database.sh
scripts/docker/docker-setup-external.sh

- adds configuration for rabbitmq within docker compose files

add rabbitmq docker configuration

---

augur/tasks/start_tasks.py

- `secondary_status` is spelled `secondary_staus` in a query string which is causing a syntax error

Fix typo in query string

---

.docker-setup.sh
Makefile
README.md
augur/api/routes/pull_request_reports.py
augur/tasks/start_tasks.py
docker-compose-externalDB.yml
docker-compose.yml
docker/backend/Dockerfile
docker/database/Dockerfile
docker/rabbitmq/Dockerfile
docker/rabbitmq/augur.conf
docs/8knot.md
docs/dev-osx-install.md
docs/new-install-ubuntu-python-3.10.md
docs/new-install.md
docs/source/docker/docker-compose.rst
docs/source/docker/getting-started.rst
docs/source/docker/quick-start.rst
docs/source/docker/toc.rst
docs/source/docker/usage.rst
docs/source/getting-started/dev-osx-install.rst
docs/source/getting-started/new-install.rst
docs/source/quick-start.rst
metadata.py
scripts/docker/docker-setup-database.sh
scripts/docker/docker-setup-external.sh

Fixed the merge conflict with the recent docker changes.

Merge Main into Dev

---

.github/workflows/auto_merge.yml

The `git commit` call in the script was causing problems with the script because GitHub actions counts any non-zero bash code as a failure condition. The `git commit` call returns a non-zero bash code because there is nothing to commit. 
Hopefully this is the last one. 

Remove Unneeded 'git commit' Call in Github Action Script Because it Returns Non-Zero Bash Code

---

augur/application/cli/db.py
augur/util/repo_load_controller.py

Allow GitLab repositories to be added to augur via the old cli interface that uses csv files.  Also patches a bug in the CLI that used deprecated syntax to add a repo group. 

Patch DB CLI to Include GitLab Logic

---

augur/application/cli/__init__.py
augur/application/cli/backend.py
augur/application/cli/config.py
augur/application/cli/db.py
augur/application/cli/user.py

- Define cli engine in database folder
- Define click decorator that automatically cleans up database engine after command completes

Handling database engines in the CLI

---

.pylintrc

Add rule in `.pylintrc` to ignore method docstring warnings. 

Disable Method Docstring Requirement for Pylint

---

augur/api/gunicorn_conf.py
augur/api/routes/dei.py
augur/api/routes/util.py
augur/api/server.py
augur/api/view/routes.py
augur/api/view/utils.py
augur/application/cli/api.py
augur/application/cli/backend.py
augur/application/cli/collection.py
augur/application/db/__init__.py
augur/application/db/lib.py
augur/application/schema/alembic/versions/18_schedule_any_old_facade_repositories_to.py
augur/tasks/data_analysis/clustering_worker/tasks.py
augur/tasks/data_analysis/insight_worker/tasks.py
augur/tasks/data_analysis/message_insights/tasks.py
augur/tasks/data_analysis/pull_request_analysis_worker/tasks.py
augur/tasks/git/dependency_libyear_tasks/core.py
augur/tasks/git/dependency_tasks/core.py
augur/tasks/git/dependency_tasks/tasks.py
augur/tasks/git/scc_value_tasks/tasks.py
augur/tasks/github/util/github_api_key_handler.py
augur/tasks/github/util/github_random_key_auth.py
augur/tasks/gitlab/gitlab_api_key_handler.py
augur/tasks/gitlab/gitlab_random_key_auth.py
augur/tasks/init/celery_app.py
augur/tasks/start_tasks.py
augur/tasks/util/collection_util.py

- Start reducing usage of AugurConfig class and start using the database library methods so that the database access logic is centralized
- Defined get_value and get_section in the database lib.py file
- Define temporary_database_engine context method for use in cases where a process needs a short-lived engine like in the celery app setup where a database engine cannot be defined when the worker processes are forked from the parent

Config usage improvements

---

augur/api/metrics/repo_meta.py

- Add an API endpoint to return the Nadia Eghbal developed project badging categorization metric
- Further information can be found here: https://project-types.github.io/
- Use Microsoft developed cutoffs for the specific project labeling 

Add 'Road's and Bridges' Style Project Labeling Endpoint to Augur

---

augur/application/cli/_multicommand.py

This change makes the CLI pass-through *all* exceptions when they occur while loading a module.
Previously, import exceptions were silenced during import of a CLI command module. Although most exceptions would have been displayed, by catching `ModuleNotFoundError`, any import errors in sub-modules would be silenced during Click imports.
The fix is to check first if the module exists using a file check, and if it does not, return None to indicate as such.

Allow exception visibility in CLI

---

augur/api/metrics/repo_meta.py
augur/application/cli/db.py

- Fix `os` module not being imported in install script for file permission purposes for `.pgpass` file
- Fix `stat` module not being present when using `stat.IWRITE` and `stat.IREAD`
- Fix SQL syntax in Nadia endpoint
- Add error handling if no contributors were found in Nadia endpoint

Fix Install Chmod Issue as Well as SQL Syntax

---

docker-compose.yml
docker/rabbitmq/Dockerfile
docker/rabbitmq/advanced.config
docker/rabbitmq/definitions.json
docker/rabbitmq/update_config.py

- Change RabbitMQ configuration scheme
- Add `definitions.json` to contain default user, password, and vhost definitions
- Add `update_config.py` to convert Docker args to RabbitMQ config items
- NOTE: RabbitMQ ignores *all* envvars if *any* config file is present
- I'm not sure if the original `augur.conf` is doing anything anymore, but there's no reason to get rid of it as of right now
- Add `update_config.py`
- Pull Docker args and check that they exist
- Compute password hash with `rabbitmqctl`
- AFAICT RabbitMQ does not support plain-text passwords in a config file
- load default `definitions.json`, update with new values and write changes
- Provide default `advanced.config`
- Previously we were creating this file with `RUN echo ...`
- Extra entries are required in …

Fix RabbitMQ config issue in Docker

---

augur/tasks/git/facade_tasks.py
augur/tasks/github/facade_github/contributor_interfaceable/contributor_interface.py

- Add error handling for strange error where the first element of a list cannot be retrieved after verifying the api says it should have elements in it
- Add exit for strange error where repo_id is null in facade 

Facade Quick Fix

---

augur/application/db/data_parse.py
augur/application/db/models/augur_data.py
augur/application/schema/alembic/versions/27_update_messages_unique.py
augur/tasks/github/messages/tasks.py
augur/tasks/github/pull_requests/tasks.py
augur/tasks/gitlab/issues_task.py
augur/tasks/gitlab/merge_request_task.py
augur/tasks/start_tasks.py

- Added contributor logic for GitLab merge requests, merge request assignees, and merge request messages
- Added messages unique key so GitLab messages can be inserted. So, this pr also includes the insertion of GitLab messages.
- Please do not merge this until dev is released to main

Add gitlab mr contributors

---

docker/rabbitmq/Dockerfile

Preparing for release and checking hot fixes.

Update dev with hot fixes

---

augur/tasks/start_tasks.py

- There was a bug where tasks that had succeeded in the past but then subsequently fail later would not be reset correctly; running into a constraint on 'date_last_collected'
- In response I have added checks to the `date_last_collected` field in order to prevent this issue
- Specifically we now check for null values in the date field and update to either `SUCCESS` or `PENDING` depending on if the field is null or not. 
- The function now should reset the task to a state where it can be run again. 

Add Check to SQL Update Statements to Avoid constraints on `date_last_collected`

---

augur/tasks/git/facade_tasks.py
augur/tasks/github/facade_github/tasks.py

Facade task error handling expects each facade task to have the repo url as the first argument passed to the task. Otherwise it can cause unintended behavior. 
To fix I altered the facade task signature to match the expected function signature and have `repo_git` as the first argument.

Fix Facade Task Signature to Take `repo_git` instead of `repo_id`

---

augur/application/db/models/augur_data.py
augur/application/db/models/augur_operations.py

- Rollback changes when a query using the session throws an exception so that the session can still be used
- Issue where frontend doesn't work because the session fails on every query
Note: I don't care if this is merged into main or dev, I just noticed that dev is the same as main and this is a small fix so I opened it into main

Rollback transaction when query throws exception

---

podman-compose.yml

- Provide a podman-compose.yml like docker-compose.yml -- to allow podman users to make use of augur
I've tested this with my local podman -- but I'm happy to accept any feedback or input / waiting period. Just wanted what works on my machine to be available to other podman users.
The changes made include updating the default DB host (from 127.0.0.1->loopback/default) and removing the `extra_hosts` declaration that causes failures for podman to boot compose installations.

add podman compose file

---

augur/application/cli/__init__.py
augur/application/cli/db.py
augur/application/db/models/augur_data.py

- more messages when loading repos
- patched edge cases where sometimes no message would occur
- rate limiting will now wait to continue loading repositories (before it would fail and continue to the next repo, making large load jobs very difficult)
- allowed for [use of a proxy](https://www.python-httpx.org/environment_variables/#http_proxy-https_proxy-all_proxy) when checking internet access (`http_proxy`/`HTTP_PROXY` is standard in many libraries, including the one in use here)
Future enhancements could include skipping validation on github until checking that a given repo is not in the database -- that's a problem for another day.

handle rate limiting and more repo load messages

---

docs/source/docker/docker.rst
docs/source/getting-started/database.rst
docs/source/getting-started/installation.rst

Fix some typos and broken links in the docs
This PR does not relate to any open issues.
N/A

Fix some typos and broken links in the docs

---

augur/tasks/github/util/github_paginator.py

- Update github ratelimit response handling based on Github API docs. 
The github docs state this ([docs link](https://docs.github.com/en/rest/using-the-rest-api/rate-limits-for-the-rest-api?apiVersion=2022-11-28#exceeding-the-rate-limit)):
If you exceed your primary rate limit, you will receive a 403 or 429 response, and the x-ratelimit-remaining header will be 0. You should not retry your request until after the time specified by the x-ratelimit-reset header.
If you exceed a secondary rate limit, you will receive a 403 or 429 response and an error message that indicates that you exceeded a secondary rate limit. If the retry-after response header is present, you should not retry your request until after that many seconds has elapsed. If the x-ratelimit-remaining header is …

Handle GitHub ratelimit responses based on Github API docs

---

augur/tasks/github/messages/tasks.py

Add full collection for messages

---

docker/rabbitmq/Dockerfile

- Provide default values for the RabbitMQ dockerfile args so it will build by default
It is still recommended to pass values for production builds via `--build-arg key=value`

Add default arg values for rabbitmq dockerfile

---

augur/api/view/augur_view.py

Add more detail to 500 page report

---

README.md
augur/application/cli/backend.py
augur/application/cli/collection.py
augur/application/cli/tasks.py
augur/tasks/git/dependency_tasks/core.py
augur/tasks/git/util/facade_worker/facade_worker/rebuildcache.py
augur/tasks/github/pull_requests/tasks.py
augur/tasks/github/util/gh_graphql_entities.py
augur/tasks/util/collection_util.py
docker/backend/Dockerfile
docker/database/Dockerfile
docker/rabbitmq/Dockerfile
metadata.py

This PR was initially created off the `main` branch as a real time patch. I tested it accordingly.

Pr file patch into MAIN

---

augur/tasks/github/pull_requests/files_model/core.py

- PR Files merge last week didn't work out perfectly. This fixes it.

PR Files Merge Issue Fix

---

augur/tasks/github/pull_requests/files_model/core.py
augur/tasks/github/pull_requests/tasks.py

- PR Review Patch
- Dependency Patch

Xdev: Final Patches for Release

---

augur/tasks/github/pull_requests/files_model/core.py
augur/tasks/github/util/gh_graphql_entities.py

do not merge

---

augur/tasks/github/pull_requests/tasks.py
augur/tasks/github/util/github_data_access.py
setup.py

- Created a more generic github data access class that can be used to paginate over a resource or get a single resource if the github endpoint returns a dict. It also handles retries with a library so that we don't have to build our own logic. It uses the `response.raise_for_status()` httpx method to ensure that an exception is thrown if a failure status code is returned (this allows us to assume that the response is successful if no exceptions occur Also the `make_request()` method throws a rate limit exception so that the caller can determine how to handle the rate limit, but the higher level methods like paginate resource and get resource handle the rate limit like the github api docs tell us to. 
I did this work to support the core recollection work, since I need a …

Improve github paginator

---

augur/api/view/server/Environment.py
augur/api/view/server/__init__.py

- Temporary patch for required import to determine the frontend config location

fix missing import error

---

augur/templates/groups-table.j2
augur/templates/login.j2
augur/templates/settings.j2

- Makes the favorite/star buttons use a pointer cursor
- Allows screen-reader users to identify buttons that were previously not visible to screen-reader software

Explicitly identify iconized buttons using role attribute

---

augur/tasks/git/facade_tasks.py
augur/tasks/github/facade_github/tasks.py

Fix Merge Error with Wrong Value Pass

Fix Merge Error

---

augur/tasks/db/refresh_materialized_views.py
augur/tasks/git/facade_tasks.py
augur/tasks/start_tasks.py

- Move the Facade affiliation refresh dm_table logic into the same place that we refresh the materialized views as per @sgoggins suggestion 
- Solves problem with logic being executed too frequently. 
Hasn't been tested quite yet. I will make it a real PR when I have tested it. 
Although feel free to test it yourself. 

Move Facade Affiliation Refresh and Rebuild to Happen After Materialized Views Refresh

---

augur/tasks/start_tasks.py

Fix ml issue

---

augur/application/db/lib.py
augur/tasks/github/issues/tasks.py
augur/tasks/github/pull_requests/tasks.py
augur/tasks/start_tasks.py

- Optimize the recollection of issues and prs
- Migrate issues task to use github_data_access since I was already changing the task

Optimize issue and pr recollection

---

augur/tasks/github/util/github_data_access.py

- The new github data access had a key manager passed to it but it was not using it to make the request, therefore the requests were being made without a github api key. This simply passes the key manager so it is provided an api key
- 

Use key manager in github data access

---

augur/tasks/github/events/tasks.py
augur/tasks/github/messages/tasks.py
augur/tasks/github/util/github_data_access.py

- Migrate messages collection to use github data access
- Migrate events collection to use github data access

Migrate messages and events to use github data access

---

scripts/install/config.sh

- Add confirmation prompt when user enters a blank line during config creation
- Re-prompt until user answers affirmatively (IE: "yes"), or enters a non-blank value
- Unify indentation of the config.sh script
This change should help to avoid entering blank values when extraneous newlines exist in standard input before execution of the config script.

Add confirmation dialog for blank input in config script

---

augur/tasks/github/issues/tasks.py

- This fixes this error
```Client error '422 Unprocessable Entity' for url 'https://api.github.com/repos/chaoss/augur/issues?state=all2024-06-08T21:20:23+00:00'```

Fix issues recollection url

---

augur/tasks/start_tasks.py
augur/tasks/util/worker_util.py

- Handle if stdout is empty when parsing it into JSON 

add empty output handle

---

.gitignore
augur/api/routes/util.py
augur/application/cli/backend.py

- Add `/api` route to get the location of the backend API
- Check that Gunicorn has actually started during `backend start` invocation
- Poll the process state every 0.5 seconds
- Make GET request to `/api` to check that service has started
- Repeat until the state of the service can be determined
**Future Work**
- Implement timeout in case Gunicorn takes too long to respond or gets stuck during startup
- Currently this waits until either the process dies or the server responds

Proper Gunicorn bringup detection

---

augur/tasks/git/dependency_tasks/core.py
augur/tasks/util/metadata_exception.py
augur/tasks/util/worker_util.py

- Currently we are logging the output when we get the json code errors in `parse_json_from_subprocess_call ` but it is impossible to find these logs in the huge log files so I added the exception so that the relevant data will show up in flower

Add metadata to json decode errors

---

augur/tasks/github/pull_requests/tasks.py

GitHub data access pr migration

---

augur/application/db/lib.py
augur/tasks/github/facade_github/contributor_interfaceable/contributor_interface.py
augur/tasks/github/facade_github/tasks.py

Make logging statements in the contributor resolution logic follow new policy: https://github.com/chaoss/augur/issues/2848
This PR fixes #2856 

Change log statements in contributor resolution to match new policy

---

augur/tasks/github/pull_requests/files_model/core.py
augur/tasks/github/repo_info/core.py
augur/tasks/github/util/github_graphql_data_access.py
augur/tasks/util/random_key_auth.py

- Create graphql equivalent to the new github data access so we can be sure that the proper exception will be thrown when an error occurs. 
- This change is in response to these `TimeoutError: No data received from endpoint.` errors in the current logic. These occur when we don't get data (None is returned) due to us returning None in places rather than throwing exceptions. The new code will help us understand why the error is occurring because it will throw an exception for any issue rather than returning None.

Refactor github graphql 

---

augur/tasks/github/messages.py
augur/tasks/github/pull_requests/tasks.py
augur/tasks/github/util/github_graphql_data_access.py

Address release bugs

---

augur/tasks/github/util/github_graphql_data_access.py

Raise exceptions on graphql errors

---

augur/tasks/github/events.py
augur/tasks/github/util/github_data_access.py

Full collect events

---

augur/application/db/data_parse.py
augur/tasks/github/events.py

Dev fixes for event collection

---

.gitignore
augur/api/view/init.py
augur/application/cli/__init__.py
augur/application/cli/_multicommand.py
augur/application/cli/api.py
augur/application/cli/backend.py
augur/application/cli/collection.py
augur/application/cli/jumpstart.py
augur/application/cli/tasks.py
augur/application/db/data_parse.py
augur/tasks/github/events.py
jumpstart/API.py
jumpstart/Client.py
jumpstart/Logging.py
jumpstart/Server.py
jumpstart/jumpstart.py
jumpstart/procman.py
jumpstart/tui.py
jumpstart/tui.tcss
jumpstart/utils.py
setup.py

Release Ready

---

augur/application/db/lib.py
augur/tasks/git/facade_tasks.py

- Right now the commits that were analyzed before the commit message table was added to the database don't have any commit message and they won't get collected because Augur considers those commits already collected and won't collect them again unless a recollection is triggered in facade for some reason. 
- The solution to this is to go back and fetch them after we analyze commits. 

Add Step to Fetch Missing Git Messages from Commits Analyzed Before Commits Message Table was Added

---

augur/api/view/api.py
augur/application/db/lib.py
augur/application/db/models/augur_data.py
augur/application/schema/alembic/versions/30_add_repo_src_id.py
augur/tasks/frontend.py
augur/tasks/github/util/github_graphql_data_access.py
augur/tasks/github/util/populate_repo_src_id.py
augur/tasks/github/util/util.py
augur/tasks/init/celery_app.py
augur/tasks/start_tasks.py

Optimize repo insertion and add repo src id

---

augur/tasks/github/events.py

Fix syntax error in sql

---

augur/tasks/git/dependency_tasks/core.py
augur/tasks/git/dependency_tasks/tasks.py

- Patch scorecard task to use correct flag
- Use .get instead of index access to dictionary
- Fix syntax error in MetadataException 
This PR fixes #2927

Scorecard Patch

---

augur/application/db/data_parse.py
augur/tasks/gitlab/issues_task.py
augur/tasks/gitlab/merge_request_task.py

Add repo_id on gitlab comments

---

augur/tasks/git/dependency_libyear_tasks/libyear_util/pypi_parser.py
augur/tasks/git/dependency_libyear_tasks/libyear_util/util.py

- Use `.get` instead of dictionary indices to avoid missing info in poetry.lock
- Make each dependency function extend the dep list instead of returning once we find the first manifest file
- Parse the path into a short string that can be more easily compared
- Parse through all found dependency manifest files and put them all in one big dictionary
I have tested locally on my repos but @sgoggins you might want to test it a bit on other repos.

Fix Libyear Parsing Function to Support More than One Dependency Manifest per Project

---

docker/backend/Dockerfile

The `curl` call to the GitHub API to get the latest release of GECKODRIVER fails intermittently. The call looks like this:
```
curl -s https://api.github.com/repos/mozilla/geckodriver/releases/latest
```
On investigation, this appears to be because GitHub itself isn't consistent it how it returns the API data - sometimes it's a nicely formatted output, eg:
```
{
"url": "https://api.github.com/repos/mozilla/geckodriver/releases/168891133",
"assets_url": "https://api.github.com/repos/mozilla/geckodriver/releases/168891133/assets",
"upload_url": "https://uploads.github.com/repos/mozilla/geckodriver/releases/168891133/assets{?name,label}",
"html_url": "https://github.com/mozilla/geckodriver/releases/tag/v0.35.0",
...
```
but sometimes it removes the newlines:
```
cat …
```

Use jq to make parsing GECKODRIVER API call reproducible

---

augur/application/db/models/augur_data.py

- Fix typo in log when rate limit is triggered when preparing to clone repos
- Fix logic where we would not retry when a rate limit is triggered when preparing to clone repos
This PR fixes #2948 

Fix Logic for `is_valid_github_repo` 

---

docker/backend/Dockerfile
scripts/docker/install-go.sh
scripts/docker/install-workers-deps.sh

This commit fixes a couple of things.
Firstly, the `install-go` script uses an ancient version of Go that conflicts with the newer version needed for SCC, so that is updated. That script also wrapped the install in a function for no apparent reason, so I simplified it.
Second, I re-enabled the SCC & Scorecard installs. These have been commented out for some time, apparently because of the Go issues. Rather than uncomment it, I copied the relevant parts from `workers.sh` because the container doesn't need checks about whether directories exist - these are guaranteed not to exist in a fresh container.
I believe this will result in working SCC and Scorecard calculations in the container now

Update Go version in Docker, and re-enable SCC/Scorecard

---

augur/application/db/data_parse.py

- Set gitlab pr closed at to the merged at date if pr closed at is not set

set closed at as merged at when closed at is missing

---

augur/tasks/git/facade_tasks.py

Merging full commit message patch

---

augur/tasks/github/messages.py
augur/tasks/start_tasks.py

- Speed up message collection by only collecting data that was updated

Only collect messages on data that was updated

---

augur/tasks/github/messages.py

Fix sql synax error

---

augur/tasks/github/events.py
augur/tasks/start_tasks.py

- Speed up github events recollection

Speed up github events recollection

---

augur/tasks/github/pull_requests/tasks.py
augur/tasks/start_tasks.py

- Speed up pr review comment recollection

Speed up pr review comment recollection

---

docker/backend/Dockerfile
docker/backend/graphical

- Copy keyman directory in Dockerfile
- Update graphical dockerfile to reflect the current build process
This PR fixes #2994 

Fix key orchestrator missing in Docker build

---

augur/tasks/github/util/github_api_key_handler.py
augur/tasks/gitlab/gitlab_api_key_handler.py

- Fixes a crash that occurs when using HTTPX with API keys that have trailing whitespace
This PR fixes #2998 

Strip whitespace from keys while loading

---

augur/application/cli/github.py

- Update `augur github api-keys` command to filter worker_oauth keys by platform
This PR fixes #3004 

Filter worker_oauth keys by platform in cli

---

augur/application/cli/backend.py
augur/tasks/frontend.py
augur/tasks/init/celery_app.py
augur/tasks/start_tasks.py
augur/util/repo_load_controller.py

- Reduce dependency on create_collection_status_record task

Reduce dependency on create_collection_status_record tasks

---

augur/tasks/github/events.py

Context: `since` is set to None when it is a full collection. The query for `thorough` events collection was always adding `since` to the query which caused it to fail
Solution: Only include `since` in the query if it is set

Hotfix since date issue in collect events task

---

augur/application/cli/backend.py
augur/application/db/lib.py
augur/tasks/github/contributors.py
augur/tasks/github/events.py
augur/tasks/github/facade_github/core.py
augur/tasks/github/facade_github/tasks.py
augur/tasks/github/issues.py
augur/tasks/github/pull_requests/core.py
augur/tasks/github/pull_requests/tasks.py
augur/tasks/gitlab/issues_task.py
augur/tasks/gitlab/merge_request_task.py
augur/tasks/init/celery_app.py
augur/tasks/start_tasks.py

Reduce deadlocks by inserting contributors in batches

---

docker/backend/Dockerfile
scripts/docker/install-golang-deps.sh
scripts/docker/install-workers-deps.sh

This change refactors the docker container for the backend to use a "builder container" pattern that attempts to help optimize the amount of disk space required to build the container
This PR contributed towards #3006 
As noted in the linked issue, this PR still refactors, but effectively removes the rust build step since there don't seem to be any dependencies written in rust.
**Testing**
Since im still trying to find ways to optimize the build, I haven't yet run a full instance of augur on my machine
TODO:

[backend] refactor docker container to builder pattern

---

augur/tasks/github/util/github_data_access.py

- Removes github api key from the pool when the github api returns a 401 reponse 

Remove key from pool when it is no longer valid

---

docker/backend/Dockerfile

This is a *really* low effort shot in the (almost) dark solution to #3053 
Having some testing would be appreciated, especially if this does anything other than fixing the issue or at least moving the error to some thing similar to a `file not found` for `scorecard` (rather than `scc`) 

adjust path that scc gets copied to

---

docs/dev-osx-install.md
docs/new-install-ubuntu-python-3.10.md
docs/new-install.md
docs/source/getting-started/dev-osx-install.rst
docs/source/getting-started/new-install.rst

- Fixed incorrect GitLab Public Access Token URL in the documentation.
- Updated the link to point to the correct resource.
**Fixes Issue**
- No related issue, this is a minor fix. 
- Please verify that the updated URL works correctly.
**Signed Commits**

[Docs] Corrected GitLab Public Access Token URL in Documentation

---

augur/application/cli/config.py
augur/application/logs.py
docker/backend/init.sh
scripts/install/config.sh

- `augur config init` now takes a parameter for the log file location
- Log file location in the docker container has been moved to /logs
- Log file "reset" step now deletes the *contents* of the log directory, not the directory itself
Related to #3107 
This is a step toward the non-root container in that it gets the log files out of a privileged location. The behavior for non-docker instances should be unchanged.

Allow log directory to be specified

---

augur/application/cli/backend.py
docker-compose.yml
docker/backend/Dockerfile
docker/keyman/Dockerfile
keyman/Orchestrator.py

- Add docker detection to key orchestrator entrypoint
- Add keyman Dockerfile
- Update backend start command to avoid starting keyman in docker
**TESTING**
Has not been tested on bare metal, will need testing to verify bare-metal functionality remains

Configure key orchestrator to run in an independent container

---

scripts/install/config.sh

Remove environment variable values from log messages to prevent sensitive information from being exposed. This change improves security by not displaying API keys and usernames in the console output.
This is particularly an issue in containerized environments (e.g., docker/kube/openshift) where the logs are preserved indefinitely and potentially shipped off-cluster.

Don't log GitHub and Gitlab credentials

---

docs/source/getting-started/using-docker.rst

- Added new information do Docker documentation
- Explains how it works when you install fresh, etc.

Updated the Docker documentation for CHAOSSCON 

---

.github/workflows/build_docker.yml

- Add keyman image and remove conditional login to GitHub Container Registry
Reopens #3193 against main. The original got closed when dev was removed.

Push the keyman container image

---

augur/api/routes/user.py
augur/application/cli/_cli_util.py
augur/application/cli/backend.py
augur/application/cli/cache.py
augur/application/cli/tasks.py
augur/tasks/init/redis_connection.py
augur/tasks/util/redis_list.py
augur/tasks/util/redis_scalar.py
keyman/KeyClient.py
keyman/Orchestrator.py
tests/test_tasks/test_task_utlities/test_key_handler/test_github_api_key_handler.py
tests/test_tasks/test_task_utlities/test_redis/test_redis_list.py

- Remove redis connection from top level so it isn't automatically created on import
#3047 

Remove redis connection from top level

---

augur/application/db/data_parse.py
augur/tasks/init/celery_app.py

- The issue #3185 shows a NoneType exception happenening when trying to retrieve the `head_sha`, so I fixed this by providing a default value of None if the diff_refs are missing or head_sha or base_sha.
- Additionally the issue pointed out that the failure handler was assuming that the first paramater to the task would be repo_git, but it this task it can't be the first paramater the celery chain is passing the mr_ids to the first param in the task. To fix this I implemented a method to search the methods parameters for the repo_git parameter. 
#3185

Gitlab Mr Metadata Improvements

---

.github/workflows/build_docker.yml

This PR adds a copy of the end to end CI job that uses podman instead of docker to ensure that any changes are compatible with both

add podman copy of the E2E test

---

scripts/control/clean.sh

- fixing `make rebuild` so it does not delete `uv.lock`
- fixes #3209

fixing make clean to preserve uv.lock

---

docker/backend/entrypoint.sh

This provides an additional method for specifying the DB connection information.
A user may now (instead of using the current `AUGUR_DB` connection string) specify the various connection string components separately: `AUGUR_DB_HOST`, `AUGUR_DB_USER`, `AUGUR_DB_PASSWORD`, `AUGUR_DB_NAME`
This change was made to support integration with the Postgres operator in Kubernetes environments. The operator handles these connection settings as separate fields within a Secret, and by allowing Augur to accept them individually, those Secret fields can be directly mapped into the Augur container.

Allow DB connection specification via components

---

augur/api/gunicorn_conf.py

This change removes a line of code from gunicorn config that performs a recursive glob operation for seemingly no purpose since the variable it assigns the results to is unused
This might help with performance somewhat, and in worst cases, helps prevent instances from accidentally self-DOS ing if they happen to store the fascade repository clones in the path of this glob (therefore looking at and processing all jinja2 files in all repositories being analyzed by augur)
This change has been deployed in prod in the Red Hat augur instance for a while without causing issues. It was put in place by previous sysadmins and has therefore been thoroughly reviewed by at least one other experienced person in addition to my searching for uses of this variable in …

limit large glob operation in gunicorn config

---

augur/application/cli/backend.py

This defaults to True to avoid infinite log growth unless explicitly opted in
To give sysadmins more control over their instances, specifically with logging policy, this PR adds a new  `AUGUR_RESET_LOGS` environment variable. If the variable is not set, it defaults to True (the current behavior).
Setting this variable to a value other than True (or one of a few common variations) signifies that the sysadmin is taking responsibility for managing logs, and augur should not reset or clear logs on startup.
If desired, I could also add a log message that says (in big scary letters) that log resetting is disabled and that the sysdmin is responsible for log management. Let me know if this would be preferable.

determine whether to reset logs via new  AUGUR_RESET_LOGS environment variable

---

augur/api/gunicorn_conf.py
augur/application/cli/collection.py
augur/application/cli/config.py

Fixes linter warnings to make one of the bots be quiet
This PR pretty much just removed unused imports and renames a couple variables to prevent shadowing

Address warnings from linter

---

docker/backend/entrypoint.sh

- This changes the test for the DB connection components to not exit with failure if AUGUR_DB can't be constructed.
Fixes #3225

Update entrypoint.sh construction of AUGUR_DB from env vars

---

augur/tasks/github/util/github_data_access.py

This may happen if requesting issues or issue comments when issues have been disabled for a repo
- added exception type for 410 Gone errors
- handle these exceptions in the request retry process so they dont throw an exception
This PR fixes #3191 

Handle 410 gone when querying github

---

augur/tasks/git/util/facade_worker/facade_worker/analyzecommit.py

This PR attempts to address the problem of analyze_commits_in_parallel hanging as mentioned in https://github.com/chaoss/augur/issues/3228
It does so by using the same `check_output` method of running git shell commands as can be seen in the rest of the `analyze_commit` function. This method of running commands has a lot more error handling capabilities than `Popen` (which was used before) and can thus fail on conditions such as a nonzero exit code, allowing the facade task to fail and therefore allowing other tasks to run in that time (while allowing us to go in and diagnose the failure) 

use check_output for git log fetching so that it can fail more easily

---

augur/tasks/github/util/github_data_access.py

- corrects a small mistake causing github API queries to not be particularly happy. 
fixes #3234 

Fix variable name in _decide_retry_policy

---

augur/application/config.py
augur/application/db/lib.py
augur/application/db/util.py
augur/application/util.py

This PR takes two identical functions found in the codebase and refactors them to both import that function from the `utils.py` file in the application module

deduplicate convert_type_of_value

---

.github/workflows/build_docker.yml
docker/empty_database/Dockerfile

I recently created https://github.com/orgs/chaoss/packages/container/package/augur_empty_database, a GHCR container containing an empty augur Database for the purposes of enabling a downstream project like 8Knot to run [CI jobs](https://github.com/oss-aspen/8Knot/pull/849) without needing to publish credentials to a publicly accessible database.
This container is a very thin wrapper around postgres 16 that ships postgres data for an empty augur db. While this intentionally violates usual docker conventions of storing postgres data in volumes, it does so to enable downstream projects to provide their CI jobs with SOMETHING to connect to in place of a real augur database for the purpose of testing.
This path was easier than attempts to create scripts that could [anonymize an …

Add dockerfile for performing an empty database build

---

augur/tasks/git/facade_tasks.py

While I haven't been certain that I can see the facade recollection issue locally, this change allowed me to successfully find `facade_task_success_util` via a flower task search in my local instance, meaning the tasks that were not running are now running again,
The thing that helped me get through this issue was this analysis from GPT5:
> I traced the facade orchestration. The issue is how the facade phase is chained: your facade_phase returns a chain that ends with a group, and then the outer routine chains the “success” util after that. In Celery, when you want to run something after a group completes, you must form a chord (e.g., group(...) | next_task). A nested chain that returns only a group won’t implicitly convert to a chord, so the subsequent …

facade: refactor facade_phase to return the group itself so that celery can properly convert things into a chord

---

augur/application/cli/github.py

This PR fixes #3251
Updated epoch_to_local_time_with_am_pm in augur/application/cli/github.py to display timezone-aware datetime for GitHub API key reset times.
Output now includes full date, time in 12-hour format with AM/PM, local timezone abbreviation, and UTC offset.
No other logic or functionality was changed.

fix(cli): display timezone in output for GitHub key expiry (#3251)

---

augur/tasks/util/collection_util.py

in looking for the facade scheduling issues, I noticed a couple structural (not functional) issues that arent directly going to solve the core problem but just help to clean up the code so its more readable when trying to debug the facade issues
1. This code path was almost entirely duplicated in two branches of an if-else chain.
2. the catch-all else block was being used for gitlab, potentially blocking any future additional sources
This essentially moves the actual "meat" of this function to below the if-else chain and extracts a couple new variables to abstract the differences between the two implementations (i.e. changing which list of phases gets used, and also printing the correct platform name in log messages)

scheduling: refactor send_messages to de-duplicate code path
