README.md

Working on the README to provide more detail. Things will have to be changed with respect to technical details. This also implies that we are checking the application against Travis.

Suggested Updates to the README

---

setup.py

Simply adding identifier to setup.py

Updated setup.py with SPDX License Identifier

---

ghdata/cli.py

Added the license that should be in every file to the `cli.py`.

Added License to the top of cli.py

---

README.md

Add reference to local environment variables in README

---

notes.md

Revert "notes edits"

---

augur.config.json

I could not find an augur.config.json file in the repository, but the dev-install guide refers to the file.
This is a default version that acts as a template for a new config.
Describe you pull request here:

Create default augur.config.json

---

augur/datasources/githubapi/routes.py

Added routes for the following metrics in `datasources.githbuapi`:
- Closed Issues
- Code Commits
- Contributors
- Opened Issues

Added routes for metrics in githubapi

---

augur/datasources/githubapi/githubapi.py
augur/datasources/githubapi/routes.py
docs/scratchpad/master-metrics-order.md

Implemented the metric "repository size" in githubapi. This implementation returns the size of the repository in KBs.

Implement repository_size in githubapi

---

augur/datasources/ghtorrent/ghtorrent.py
augur/datasources/ghtorrent/routes.py
augur/datasources/ghtorrent/test_ghtorrent.py

Implemented metrics 'Pull Request Closed' and 'Pull Request Comment Duration' in Ghtorrent.

Implemented metrics 'Pull Request Closed'  and 'Pull Request Comment Duration' in Ghtorrent

---

frontend/app/components/charts/DynamicLineChart.vue

Fix issue #259 missing dates on time-axis.

fix Missing dates on time-axis

---

augur/datasources/augur_db/augur_db.py

Implemented:
* Contributors
* New Contributors
* New Contributors of Commits
* New Contributors of Issues
* New Contributors closing Issues
* Sub-Projects

Implement Evolution Metrics in Community Growth Area 

---

augur/datasources/augur_db/augur_db.py
augur/datasources/augur_db/routes.py
augur/datasources/augur_db/test_augur_db.py

Bing0n3 dev tmp

---

augur/datasources/augur_db/augur_db.py
augur/datasources/augur_db/routes.py
augur/datasources/augur_db/test_augur_db.py

* Refactored the 'New Contributors of Issues' metric to accept repo_group_id and repo_id instead of repo_url
* add  unit testing for metric 'New Contributors of Issues'

refactor metrics and add routes

---

augur/datasources/augur_db/augur_db.py
augur/datasources/augur_db/routes.py
augur/datasources/augur_db/test_augur_db.py
augur/datasources/augur_db/test_augur_db_routes.py
frontend/app/Augur.js
frontend/app/AugurAPI.js
frontend/app/components/charts/DualLineChart.vue
frontend/app/components/charts/DynamicLineChart.vue

Add Evolution metrics and routes: 
* [Open Issue Age](https://github.com/chaoss/wg-evolution/blob/master/metrics/issues-open-age.md)
* [Closed Issue Resolution Duration](https://github.com/chaoss/wg-evolution/blob/master/metrics/issues-closed-resolution-duration.md)
Optimize Chart:
* Optimize `DualLineChart` to prevent duplicate requests to endpoints `repos/:owner/:name`

Implement evolution metrics and Optimize Chart  

---

frontend/app/Augur.js
frontend/app/components/DownloadedReposCard.vue
frontend/app/components/GitCard.vue
frontend/app/components/charts/CommitChart.vue
frontend/app/components/charts/HorizontalBarChart.vue
frontend/app/components/charts/LinesOfCodeChart.vue
frontend/app/components/charts/NormalizedStackedBarChart.vue
frontend/app/components/charts/OneDimensionalStackedBarChart.vue
frontend/app/components/charts/TickChart.vue

Optimize charts and card to prevent duplicate requests:
* GitCard
* CommitChart
* HorizontalBarChar
* LinesOfCodeChart
* NormalizedStackedBarChart
* OneDimensionalStackedBarChart
* TickChart

Optimize frontend to prevent duplicate requests

---

augur/datasources/augur_db/augur_db.py
augur/datasources/augur_db/routes.py
augur/datasources/augur_db/test_augur_db.py
augur/datasources/augur_db/test_augur_db_routes.py

- Refactored time series metric implementations to return a 'date' field
- Added & updated augur_db tests (both `test_augur_db.py` & `test_augur_db_routes.py`

dev: Added & updated augur_db tests & refactor metric implementations

---

augur/datasources/augur_db/augur_db.py
augur/datasources/augur_db/routes.py
augur/datasources/augur_db/test_augur_db_routes.py

- Moved all utility API endpoints to a Utility section in `augur_db.py`
- Added the following utility API endpoints:
- `/dosocs/repos`: Get a list of repos along with their repo_id, & path
- `/repo-groups/:repo_group_id/repos`: Get a list of all repos in the repo group specified by repo_group_id

dev: Add utility api endpoints

---

augur/datasources/augur_db/augur_db.py
augur/datasources/augur_db/routes.py

Refactored the following metric implementations to include 'repo_name':
- code_changes_lines
- issues_new
- issues_active
- issues_closed
- issue_duration
- issue_participants
- issue_backlog
- issue_throughput
- cii_best_practices_badge
- license_declared
Also updated the api-docs

dev: refactor metric implementations to include repo_name

---

augur/datasources/augur_db/augur_db.py
augur/datasources/augur_db/routes.py
augur/datasources/augur_db/test_augur_db.py
augur/datasources/augur_db/test_augur_db_routes.py
frontend/src/store/modules/common/actions.ts
frontend/src/store/modules/common/getters.ts
frontend/src/views/Dashboard.vue
frontend/src/views/Errors.vue
frontend/src/views/RepoGroups.vue
frontend/src/views/Repos.vue

- Translate Vue Component to class style component in Typescript
- Repos.vue
- RepoGroups.vue
- Fix the problem Vuex's mapAction and mapGetter not work
- **Note**: Reload Data when refresh page is still in work
- Add Risk Metric 
- CII Best Practice
- Committers
-  License Declared
-  License Coverage
- License Count

Implement Risk metrics and Translate Component in frontend 

---

augur/datasources/augur_db/augur_db.py
augur/datasources/augur_db/routes.py
augur/datasources/augur_db/test_augur_db.py
augur/datasources/augur_db/test_augur_db_routes.py

Implemented the following metrics:
- **Average Issue Resolution Time**: returns the average time taken to resolve an issue (i.e. close an issue)
- **Top Committers**: returns a list of contributors contributing N% of all commits in a repo_group or repo. (resolves #327)

Implement metrics

---

frontend/package.json
frontend/src/store/modules/common/actions.ts
frontend/src/store/modules/common/getters.ts
frontend/src/store/modules/common/mutations.ts
frontend/src/store/store.ts
frontend/src/views/RepoGroups.vue
frontend/src/views/Repos.vue

- Import new package `vuex-persistedstate`
- Store the original API call in format `cache: {getRepos: [api call result], getRepoGroups:[].....}`
- Adapt components to new state format

Persist Vuex State to local 

---

workers/gh_pr_worker/gh_pr_worker/worker.py

The worker now also gathers the following data:
- Reviewers
- Assignees
- Pull Request Meta Information [Base & Head]
- Pull Request Comments

Update Pull Request Worker

---

workers/pull_request_worker/pull_request_worker/worker.py

Bug fixes PR worker

---

augur/datasources/metrics_status/__init__.py
augur/datasources/metrics_status/metrics_status.py
augur/datasources/metrics_status/routes.py
augur/server.py
augur/util.py
workers/insight_worker/insight_worker/worker.py
workers/metric_status_worker/metric_status_worker/runtime.py
workers/metric_status_worker/metric_status_worker/worker.py
workers/metric_status_worker/setup.py

* Refactor Metric Status Worker
* Use metadata information now to determine the backend status 
* Update Metric Status Endpoint

Refactor Metric Status Worker

---

workers/repo_info_worker/repo_info_worker/worker.py

The worker now collects the following data:
- committers Count
- commit count
- issue count
- issue open
- pull request count
- pull request open
- pull request closed
- pull request merged

Repo Info Worker collects more data

---

workers/repo_info_worker/repo_info_worker/worker.py

Fix port bug in repo_info_worker

---

workers/repo_info_worker/repo_info_worker/runtime.py

Another fix for the port bug in repo_info_worker.
Signed-off-by: Parth Sharma <parth261297@gmail.com

 Fix port bug in repo_info_worker

---

util/make-config.py

Revert "update make-config.py"

---

docs/setup/installing-augur.md

Corrected small but important typo in macos instructions :)

Corrected MacOS Typo

---

augur/cli/run.py

Signed-off-by: Carter Landis <ccarterlandis@gmail.com>

Enable exit function to run during housekeeper startup

---

frontend/src/components/charts/CoverageCard.vue
frontend/src/components/charts/DownloadCard.vue
frontend/src/views/RiskMetrics.vue
util/scripts/control/killinsightworker.sh
util/scripts/install/install.sh

New SPDX Documents are currently scanning and I had to make some tweaks to the risk page to accomodate.
P.S, a good test repo for this new data is rails/rails

Accommodate DB Changes in SPDX Document Retrieval

---

frontend/src/components/charts/CoverageCard.vue
frontend/src/components/charts/DownloadCard.vue

The SPDX Documents are now loaded, but I noticed the downloads only worked with Firefox. 
I've added a hotfix which should add compatibility for all major browsers.

Hotfixes for SPDX Documents

---

frontend/src/components/charts/OsiCard.vue

Remove All Errors on Previous OSI PR

---

frontend/src/components/charts/DownloadCard.vue
persistence_schema/5-seed-data.sql

Thanks, Gabe H!
This is a one-liner that prints the SPDX Document in the correct format for viewing.

Quick Fix for JSON SPDX Document

---

augur/metrics/repo_meta/repo_meta.py
workers/linux_badge_worker/linux_badge_worker/worker.py

Under the previous implementation, the `linux_badge_worker` would break everytime the CII badging API would add new fields. This implementation switches to using the `jsonb` field type in the `repo_badging` table, and pulls only the columns we need from the result. This way, we are no longer bound to the structure of the CII badging API result.
I'm marking this as a draft pull request until we can confirm that the appropriate database schemas have been updated to accommodate this change. I've included the SQL I used to create the table with the correct structure below:
```
CREATE TABLE augur_data.repo_badging
(
badge_collection_id bigint NOT NULL DEFAULT nextval('augur_data.repo_badging_badge_collection_id_seq'::regclass),
repo_id bigint,
data jsonb,
created_at timestamp(0) without time …
```

Update badging worker to use JSON field in DB

---

workers/pull_request_worker/pull_request_worker/worker.py

The Pull Request Worker now collects data for the pull_request_repo table

Pull Request Worker now collects pull_request_repo data

---

workers/pull_request_worker/pull_request_worker/worker.py

Fixes the issue where the PR worker wouldn't add events, labels, etc. to already existing PRs in the DB.

Update PR worker

---

bdwt5/README-my-contribution.md
bdwt5/README.md
bdwt5/update_worker.py

There are instrunctions on what to edit inside of the file.

bdwt5 final semester project turn in

---

mb2kb/API Endpoints/contributor/contributor.py
mb2kb/API Endpoints/contributor/routes.py
mb2kb/API Endpoints/issue/issue.py
mb2kb/API Endpoints/issue/routes.py
mb2kb/README-my-contribution.md

SWE final project

---

jadqr4/finalOverview.md

SoftwareEngineering_Group9_FinalOverview_Contributions_JessicaDean

Contributions Overview

---

mrh4hd/README-my-contribution.md
mrh4hd/api-endpoints/README.md.txt
mrh4hd/api-endpoints/commit/__init__.py
mrh4hd/api-endpoints/commit/commit.py
mrh4hd/api-endpoints/commit/routes.py
mrh4hd/api-endpoints/commit/test_commit_functions.py
mrh4hd/api-endpoints/commit/test_commit_routes.py
mrh4hd/api-endpoints/contributor/__init__.py
mrh4hd/api-endpoints/contributor/contributor.py
mrh4hd/api-endpoints/contributor/routes.py
mrh4hd/api-endpoints/contributor/test_contributor_functions.py
mrh4hd/api-endpoints/contributor/test_contributor_routes.py
mrh4hd/documentation/sprint-1/README.md
mrh4hd/documentation/sprint-2/README.md
mrh4hd/documentation/sprint-3/README.md
mrh4hd/documentation/sprint-4/README.md

PR for Matt Hudson - Group 5 SE F 19 semester project. We focused on developing three new API endpoints in the commits and contributors metric categories. This PR follows the format described by the final exam.

Software Engineering Fall 2019 Group 5 Project - Matt Hudson

---

workers/KIRA009/data_rest.json
workers/KIRA009/gitlab_rest.py

A small script to get commits of a project

[feat] Microtask 0, 1, 2 completed

---

augur/metrics/pull_request/routes.py
test/api/test_pull_request_routes.py
test/metrics/test_pull_request_metrics.py

•Added API tests & Metric tests for _PRs _closed - no merge__ metric.
• fixed the API route in the docs.

Added API tests, Metric tests & Fixed apidoc route

---

notebooks/Akshara-Anomaly Detection.ipynb

As suggested earlier, I have added a chart to give more insight.
I was also wondering if the messages and issues table could be merged by issue id to get more insights..
Please suggest any improvements needed

[GSoC Microtask] Added visualization for previous message anomalies 

---

schema/create_schema.sql

Fix incorrect schema script name

---

augur/routes/manager.py

handle nonexistent groups

---

workers/abhinavbajpai2012/constants.py
workers/abhinavbajpai2012/utils.py
workers/abhinavbajpai2012/worker.py

Adding Gitlab worker which fetches details of each Issue, Branch, Commit and Merge Request for all owned projects and stores them as JSON in directory named after parent project in the 'output' directory.
Signed-off-by: Abhinav <abhinavbajpai2012@gmail.com>

GSoC 2020: Adding Gitlab worker: Microtask-1

---

workers/value_worker/value_worker/__init__.py
workers/value_worker/value_worker/runtime.py
workers/value_worker/value_worker/worker.py

This patch fixes 2 major bugs with the value_worker.
1. The previous version used an old `api/unstable/dosocs/repos` query which
returned all repos in the database, regardless of the repo passed to it. This vastly
increased collection sizes, since we were unaware it was collecting for every
repo, every time.
2. The previous version used the repo_directory setting in the database. This
is not portable, so I've updated the worker to use the value set in the
augur.config.json file.

Refactor value worker

---

augur/cli/configure.py
scripts/install/setup_db.sh

This PR adds the `contributor_worker` section to the worker defaults and updates the default `contributors` job.

Update default configuration values

---

augur/metrics/issue/issue.py
augur/metrics/issue/routes.py
test/api/test_issue_routes.py
test/metrics/test_issue_metrics.py

- Adds metric and API tests for issues with comments metric

Added new metric for issues with comments

---

.github/ISSUE_TEMPLATE/bug_report.md
augur/cli/configure.py
augur/cli/db.py
scripts/install/api_docs.sh

Pre-release v0.12.0 hotfixes
- `~/.pgpass` is now created if it does not exist
- `pull_request_commits` block has been added to the default config
- updated bug report issue template
- update invocation of `apidoc`

Pre-release hotfixes

---

schema/create_schema.sql

Add schema v15 update script to schema install

---

schema/create_schema.sql

Add schema v16 update script to schema install

---

schema/create_schema.sql

Fix typo in schema creation script

---

schema/create_schema.sql

Add v17 update script to schema creation script

---

schema/create_schema.sql
schema/generate/16-schema_update_18.sql

This is the table, foreign key, etc. needed for the release worker.

schema update for PR for release versions data.

---

workers/standard_methods.py

Fixes #742 
Added the kwarg `platform` with default value as `github` & processed the last page link header properly for gitlab
Ex: 
```
'url': 'https://gitlab.com/api/v4/projects/36189/issues?id=36189&order_by=created_at&page=20&per_page=100&scope=all&sort=desc&state=all&with_labels_details=false'
```

Pagination support for Gitlab API resources

---

augur/application.py
augur/config.py
augur/logging.py
conftest.py
tests/test_application.py

Update logging in testing suite

---

scripts/install/api_key.sh
scripts/install/checks.sh
scripts/install/frontend.sh
scripts/install/install.sh

This PR fixes issue #785 and includes some additional output formatting updates.

Update shell scripts

---

scripts/control/clean.sh
scripts/control/rebuild.sh
scripts/install/frontend.sh

Fix logs/ removal bug in scripts/install/rebuild.sh

---

augur/cli/logging.py

This adds `augur logging errors [ |all|WORKER]` command, which outputs
only error logs. It can output augur and housekeeper logs, as well as all
worker logs, or only a specific worker log with
`augur logging errors WORKER`
Related to #738

Add CLI for error logs

---

docs/source/getting-started/installation.rst
scripts/install/checks.sh

Fix scripts/install/frontend.sh logging bug

---

workers/gitlab_issues_worker/gitlab_issues_worker.py
workers/worker_base.py

This PR includes logic pertaining to the data collection for the following models:
1. Issue Labels 
2. Issue Comments 
3. Issue Events
This completes the gitlab issues worker. Post this, I'll be performing a bit of manual testing just to see if everything is working as expected. Following that, I'll be getting upto speed with the worker tests, integration tests & unit tests for throughout Augur!
Also resolves #793

Gitlab Issues Worker - Phase 2 - Implementation for Remaining Models

---

docs/README.md
docs/source/index.rst
schema/create_schema.sql
schema/generate/18-schema_update_20.sql
workers/facade_worker/facade_worker/facade00mainprogram.py
workers/facade_worker/facade_worker/facade01config.py
workers/facade_worker/facade_worker/runtime.py
workers/worker_base.py

This PR
1. merges Gabe's fixes in his branch for the PR and GitHub workers into the `dev` branch.
2. adds indexes and default values aimed at fixing issues with the repo_info and facade workers
3. integrates changes to the facade worker that prevent it from crashing in the new logging format due to missing escape characters in the version info for facade00*.py and facade01*.py.

Gabe Branch PR/Github, Schema, Facade Updates

---

SECURITY.md
augur/cli/util.py
augur/routes/util.py
frontend/src/components/layout/MainFooter/MainFooter.vue
schema/generate/18-schema_update_20.sql
scripts/install/frontend.sh
workers/facade_worker/facade_worker/facade01config.py

Fixing `make install` , `augur util kill`, updating frontend

---

workers/gitlab_merge_request_worker/gitlab_merge_request_worker.py
workers/gitlab_merge_request_worker/runtime.py
workers/gitlab_merge_request_worker/setup.py
workers/worker_base.py

Complete Gitlab Merge Request Worker.
Queries following data-
- contributors
- pull_requests
- pull_request_assignees
- pull_request_events
- pull_request_labels
- pull_request_message_ref
- pull_request_meta
- pull_request_repo
- pull_request_reviewers
- pul_request_comments
- pull_request_commits
- pull_request_files

Gitlab Merge Request Worker

---

workers/gitlab_merge_request_worker/gitlab_merge_request_worker.py
workers/worker_base.py

Bug Fixes: Gitlab Merge Request Worker
Signed-off-by: Abhinav - FOSS <abhinavbajpai2012@gmail.com>

Resolved bugs in the merge request worker

---

workers/release_worker/release_worker.py

Release worker was always printing error messages for missing response
sections

Fix release worker

---

augur/config.py
augur/repos.csv
repos.csv
tests/test_workers/test_gitlab_worker.py
workers/github_worker/github_worker.py
workers/gitlab_issues_worker/gitlab_issues_worker.py

Gitlab Worker Integration Tests
1. Checking data persistence & validity with respect to the API & table values
2. Rate Limit testing
3. I'll also be making a video[Youtube/or any other recommended channel] which would act as a walkthrough for writing other workers 😄

Gitlab Worker Integration Testing 

---

docs/source/development-guide/workers/toc.rst

Gitlab Merge Request Worker Documentation 
Signed-off-by: abhinavbajpai2012 <abhinavbajpai2012@gmail.com>

Adding documentation for the Gitlab Merge Request Worker.

---

docs/source/development-guide/workers/toc.rst

Signed-off-by: mrsaicharan1 <saicharan.reddy1@gmail.com>

Issue Worker Docs Update

---

workers/release_worker/release_worker.py

This change updates the release worker to insert new values when release_id is not
already inserted and to update when a row exists. Includes few tiny fixes
Duplicated #891 but against `sean-dev`

Update release worker

---

docs/source/getting-started/installation.rst
scripts/install/api_key.sh
scripts/install/backend.sh
scripts/install/checks.sh
scripts/install/config.sh
scripts/install/frontend.sh
scripts/install/install.sh

Reverts chaoss/augur#918 which was merged early without the appropriate review.

Revert "Update installation logging for clarity"

---

docs/source/getting-started/installation.rst
scripts/install/api_key.sh
scripts/install/backend.sh
scripts/install/checks.sh
scripts/install/config.sh
scripts/install/frontend.sh
scripts/install/install.sh

This PR:
- updates the installation process to write the all logs (including errors) to both `stdout` and to the `logs/` directory
- hides user input when entering their database password during the installation process
- adds a warning in the documentation to not use `sudo` when running or installing Augur

Installation usability issues

---

docs/source/index.rst
docs/source/library-documentation/toc.rst

Minor updates to the docs landing page.

Update docs landing page

---

metadata.py

Update version to 0.14.0

---

workers/pull_request_worker/pull_request_worker.py

Fixes incorrect additions count in pr files table

pr files model additions count fix

---

schema/generate/25-schema_update_27.sql

Sgoggins patch schema logic

---

augurface/src/store/UtilModule.js
frontend/src/store/modules/common/index.ts
frontend/src/store/modules/compare/index.ts
util/docker/frontend/Dockerfile

When I originally made this change a week or so ago, I forgot to check all
uses of the config file in the frontend. Additionally, I got the new name
wrong in the frontend Dockerfile. This patch fixes both of those errors.

Update frontend config file location

---

workers/worker_base.py

Remove incorrect @staticmethod on check_duplicates

---

schema/create_schema.sql
schema/generate/32-schema_update_34.sql

rolling back foreign key on repo table for PRs until code is pushed

---

schema/generate/32-schema_update_34.sql

Undoing bad choice from last night.

fixing my screw up last night

---

workers/pull_request_worker/pull_request_worker.py

Merging Dev into gsoc-ml

---

augur/routes/contributor_reports.py
augur/routes/pull_request_reports.py

Added logic so that the image api endpoints return an error, if there is no data to display

No Data Fix: Image-Apis

---

schema/create_schema.sql
schema/generate/32-schema_update_34.sql
workers/message_insights_worker/message_sentiment.py

Added inline comments to aid new developers in understanding the message_sentiment worker.

Added inline comments

---

augur/config.py
schema/generate/33-schema_update_35.sql
workers/gitlab_issues_worker/gitlab_issues_worker.py
workers/gitlab_merge_request_worker/__init__.py
workers/gitlab_merge_request_worker/gitlab_merge_request_worker.py
workers/gitlab_merge_request_worker/runtime.py
workers/gitlab_merge_request_worker/setup.py

Merging two GSOC branches, `gitlab-issues+releases-patch` and `gsoc-ml` into a single branch for testing.

Gitlab issues+releases patch

---

workers/github_worker/github_worker.py
workers/worker_base.py

Putting into gsoc-dev branch for testing.

gh worker refactor

---

augur/config.py
augur/housekeeper.py

Revert "Ivanayov/redirects"

---

schema/generate/33-schema_update_35.sql

Added new table to support repo breadth analysis of contributors.

Added Foreign Keys to Support Contributor Worker.

---

augur/cli/backend.py
augur/housekeeper.py
augur/routes/broker.py
workers/worker_base.py

Housekeeper order into pr_worker_redo

---

workers/worker_base.py

Fixing hopefully large PR issue.

large organize needed data merge fix

---

workers/worker_base.py

Fixing comment modifying indentation errors.

Gsoc patch workers

---

Makefile
augur/cli/backend.py
augur/config.py

Fixes issue #1018. Also contains indentation fixes for the default config, and updates some Makefile commands to print the commands they are running for transparency.

Fix hardcoded port logging on startup

---

augur/housekeeper.py
schema/20201025-Release-0.14.0.sql

Revert "sql fix"

---

augur/config.py
schema/20200311-Release-0.15.1.sql
schema/generate/44-schema_update_46.sql
workers/contributor_breadth_worker/__init__.py
workers/contributor_breadth_worker/contributor_breadth_worker.py
workers/contributor_breadth_worker/runtime.py
workers/contributor_breadth_worker/setup.py

Revert "Revert "Contributor breadth worker""

---

schema/generate/43-schema_update_45.sql

fix syntax error in generated schema

---

setup.py
workers/clustering_worker/clustering_worker.py
workers/github_worker/github_worker.py

Updated the topic list parameters because they were low for testing. 
Added comments in the code for the clustering worker.
Added comments in the code for the github worker.

Dev clustering / update params + added comments

---

augur/routes/contributor_reports.py

Issue: Update Visualization Captions and Titles in API : "drive-by" == "fly-by" #1155
I have changed all the frontend part wherever there was a drive by to fly by. So I think visually it shouldn't show drive by anymore . But I Didn't change any other things . If you want them changed or if there is anything wrong with this PR do let me know.

Changed frontend text for drive by to fly by

---

augur/housekeeper.py

This is a follow up of #1056 with a fix for repo_group set to 0,
which means not specified
Signed-off-by: Ivana Atanasova <iyovcheva@iyovcheva-a02.vmware.com>

Fix redirects for repo_group 0

---

workers/clustering_worker/clustering_worker.py

Short  term topic model count optimization

Dev cluster patch 2b

---

augur/housekeeper.py

This change checks if repo url has `.git` suffix and removes it
for the repo redirects update
Signed-off-by: Ivana Atanasova <iyovcheva@iyovcheva-a02.vmware.com>

Add '.git' suffix check for repo redirects

---

augur/routes/contributor_reports.py

regarding issue : #1219
@sgoggins  I am really sorry for leaving out some "drive-by"  in the previous PR , I thought I changed everything but somehow I missed some .
Please Note: Only for visualisation drive by is changed to fly by , But in the code still the contributor_type list has drive_by in it . So basically people on the frontend see things as "fly-by" but in the code part drive_by is the type. Do let me know if you want that to change too

changed drive-by to fly-by

---

workers/gitlab_merge_request_worker/gitlab_merge_request_worker.py

Signed-off-by: Dhruv-Sachdev1313 <dhruvhsachdev@gmail.com>
Many API calls were being wasted as the url wasn't a gitlab url in gitlab_merge_request_worker. So I have added a if condition to check the url . I think this should work , but do go through the changes once please.

Checked if the url is a gitlab url

---

setup.py
workers/contributor_worker/setup.py
workers/discourse_analysis_worker/setup.py
workers/facade_worker/facade_worker/facade05repofetch.py
workers/insight_worker/setup.py
workers/message_insights_worker/setup.py
workers/pull_request_analysis_worker/setup.py

Added code to the commit worker, Facade, to checkout the `main` branch if a repo no longer has a `master` branch.

Branch patch facade + scipy version update

---

augur/housekeeper.py

1. Added a progress bar to show the progress of the housekeeper preparing the jobs, so the user has an idea of how much longer until the housekeeper jobs will be prepared.

Add progress bar for housekeeper job prep

---

workers/github_worker/github_worker.py
workers/gitlab_merge_request_worker/gitlab_merge_request_worker.py
workers/pull_request_worker/pull_request_worker.py
workers/worker_base.py
workers/worker_git_integration.py

Some of the workers threw errors when using base class methods that expected attributes that they never had. This should handle that situation.

Added handling of oauth attribute errors

---

workers/worker_base.py

Separate where parts of the collection method handle exceptions.

Tweak Exception Handling

---

README.md

Signed-off-by: Kushal Kothari <kushalkothari285@gmail.com>

Fixes typos and unnecessary quantifiers.

---

.gitignore

Extremely minor change.
Signed-off-by: isaacmilarky <imilarsky@gmail.com>

Added Visual Studio Code files to gitignore

---

docs/source/development-guide/make/development.rst
docs/source/docker/docker.rst

OSD'21 is round the corner, thought it'd be nice to have these things as part of dev docs for the new contributors to get started with hacking the codebase

chore(docs): Update development docs

---

workers/github_worker/github_worker.py
workers/pull_request_worker/pull_request_worker.py

I implemented the stagger insert for when the github worker paginates issues. This works near identically to how the pull request worker staggers the pull request insertions.

Implemented stagger insert for the github issues

---

docs/source/development-guide/installation.rst

Signed-off-by: Brenda Kamangara <27910629+b-kamangara@users.noreply.github.com>
A small typo correction on the first paragraph - changed "Installiing" to "Installing".

Typo correction on docs/source/development-guide/installation.rst

---

docker-compose.yml
util/docker/backend/entrypoint.sh

this reverts the old changes that came in from master via https://github.com/chaoss/augur/commit/7a22880aad1375504be8143f63ae3ad665488695#diff-e45e45baeda1c1e73482975a664[…]a56f20c03dd9d64a827aba57775bed0d3

fix docker-compose.yml after issues with merge and configure DB Host in entrypoint script

---

augur-pypi installation.md

Create augur-pypi installation.md

---

util/docker/backend/Dockerfile

Signed-off-by: Josh Berkus <josh@agliodbs.com>
Fixes #1354

Add postgresql client to container image so that create-schema works

---

workers/github_worker/github_worker.py
workers/worker_git_integration.py

This error really shouldn't happen so I added more detailed logging. Merge whenever dev is ready to be merged into.

Added logging to github_worker whenever a type error occurs before it tries to handle the error.

---

workers/github_worker/github_worker.py

I implemented the stagger insertion for the issue messages along with some extra error handling if there is not a contributor to insert in some places.

Implement stagger insert for issue messages

---

workers/github_worker/github_worker.py

Added some logging in try/catch blocks

---

workers/worker_git_integration.py

More exception handling

---

workers/github_worker/github_worker.py
workers/pull_request_worker/pull_request_worker.py
workers/worker_git_integration.py

I am continuing to debug Dev. There are more cases where inserts aren't being checked before being sent to enrich_cntrb_id than I thought. I have added checking to all the places that call enrich_cntrb_id.

Fixing of Value Error's Caused by Shared Library

---

workers/pull_request_worker/pull_request_worker.py
workers/worker_git_integration.py
workers/worker_persistance.py

There was some logging left in the pr worker from previous debugging and testing, that was cluttering up the logs and essentially making them impossible to read and navigate so I removed them.

Comment out some logging in pr worker

---

workers/github_worker/github_worker.py
workers/gitlab_issues_worker/gitlab_issues_worker.py
workers/insight_worker/insight_worker.py
workers/linux_badge_worker/linux_badge_worker.py
workers/pull_request_worker/pull_request_worker.py
workers/release_worker/release_worker.py
workers/repo_info_worker/repo_info_worker.py
workers/worker_base.py
workers/worker_git_integration.py
workers/worker_persistance.py

I'm pretty sure this was caused by a merge conflict not getting resolved correctly.

Fixed some issues with WorkerGitInterfacable not being inherited. 

---

workers/clustering_worker/clustering_worker.py
workers/contributor_breadth_worker/contributor_breadth_worker.py
workers/deps_worker/deps_worker.py
workers/discourse_analysis_worker/discourse_analysis_worker.py
workers/gitlab_merge_request_worker/gitlab_merge_request_worker.py
workers/message_insights_worker/message_insights_worker.py
workers/pull_request_analysis_worker/pull_request_analysis_worker.py
workers/value_worker/value_worker.py

Fixed a bug caused by a git merge getting rid of the inheritance that a lot of the workers need.

Fixing Git Merge Inheritance

---

docs/source/docker/docker-compose.rst
docs/source/docker/getting-started.rst
docs/source/docker/quick-start.rst
docs/source/docker/usage.rst

Updated docker docs while I think about how the container will work when it is more usable

Made docker docs more current before I start making QoL improvements

---

workers/deps_libyear_worker/pypi_parser.py

bug fix for poetry parser and added poetry.lock parser.

Fixed poetry parser and added poetry.lock parser 

---

setup.py
workers/deps_libyear_worker/pypi_parser.py
workers/deps_libyear_worker/setup.py

Pip dependencies can be embedded in conda environment files, so added a parser for that
This completes all the parsers for PYPI
This also introduces a new dependency in setup.py - 'pyYaml' to parse conda environment YAML files

Added Conda support for libyear Worker  

---

schema/create_schema.sql
schema/generate/60-schema_update_62.sql
schema/generate/61-schema_update_63.sql
schema/generate/62-schema_update_64.sql
workers/github_worker/github_worker.py
workers/pull_request_worker/pull_request_worker.py
workers/worker_git_integration.py

Handles a number of UNICODE Conversion issues, and adds logging to help make token shortages more visible.

Updates to handle wonky text in old repositories. 

---

augur/metrics/release.py
augur/metrics/repo_meta.py
docs/source/rest-api/spec.yml

Fix more things in the api docs

Api docs fixes

---

augurface/README.md

Notice about status of Augurface directory functions added.

notice added 

---

augur/config.py
augur/housekeeper.py
augur/routes/broker.py
metadata.py
schema/create_schema.sql
schema/generate/05-seed_data.sql
schema/generate/83-schema_update_85.sql
workers/facade_worker/facade_worker/facade05repofetch.py

Schema, configuration, facade worker (commits) and housekeeper updates

---

augur/housekeeper.py
workers/worker_git_integration.py

Updated Housekeeper sleep parameters to limit initial "Augur Surge"

---

augur/housekeeper.py
metadata.py
workers/github_worker/github_worker.py
workers/repo_info_worker/repo_info_worker.py
workers/worker_git_integration.py

Release with Performance Improvements and bug fixes. 

---

workers/worker_base.py

1. Added some doc strings to worker_base.py file

Add doc strings worker_base

---

metadata.py
schema/create_schema.sql
schema/generate/92-schema_update_94.sql

Adds a materialized view for higher performance reporting
Fixes issues with pull requests not being pulled in some cases.

Spg patch aas

---

augur/housekeeper.py
workers/facade_worker/contributor_interfaceable/contributor_interface.py

Spg patch aas: Housekeeper PR ORder fix

---

augurface/public/index.html
augurface/vue.config.js

@sgoggins , I deployed as we discussed last week, but it seems to fail due to path issues.

Fix the file path for production deployment

---

schema/create_schema.sql
schema/generate/94-schema_update_96.sql

Removing bulky, optional indices on commits table.

---

docs/source/development-guide/toc.rst
metadata.py

Development Guide Update

---

docs/source/quick-start.rst

Quickstart documentation update

Quickstart Documentation update.

---

docs/source/quick-start.rst

Added Go installation steps to Augur Quickstart.

Updated quickstart instructions.

---

docs/source/getting-started/toc.rst

Signed-off-by: manishsaini6421 <manishsaini6421@gmail.com>
I have firxed this issue now.

This is my first commit

---

docs/source/getting-started/installation.rst

Signed-off-by: flyagaricdev <83814427+flyagaricdev@users.noreply.github.com>

Fix typos and change case in GS - Installation

---

docs/source/getting-started/command-line-interface/backend.rst

Signed-off-by: flyagaricdev <83814427+flyagaricdev@users.noreply.github.com>
Also in the PR I added whitespace hoping to fix the code-block issue that wasn't showing the code box properly.

Fixed punctuation and code-block in GS-CLI-Backend

---

CONTRIBUTING.md
docs/source/docker/getting-started.rst
docs/source/getting-started/collecting-data.rst
docs/source/getting-started/command-line-interface/backend.rst
docs/source/getting-started/command-line-interface/db.rst
docs/source/getting-started/installation.rst
docs/source/getting-started/toc.rst
metadata.py
schema/create_schema.sql
schema/generate/97-schema_update_99.sql

This PR contains updates to the schema, and Augur documentation.

Updates to Schema and Documentation

---

docs/source/deployment/nginx-configuration.rst

Signed-off-by: Ihuoma <anosikeihuoma21@gmail.com>

Fix Documentation Format

---

CONTRIBUTING.md

Signed-off-by: flyagaricdev <83814427+flyagaricdev@users.noreply.github.com>

Improved CONTRIBUTING.md

---

docs/source/index.rst

Signed-off-by: Priya Srivastava <shivikapriya730@gmail.com>
Changed minor typo from 'i' to 'I'

Minor Typo fix

---

docs/source/quick-start.rst

Signed-off-by: Oma Anosike <71280528+oma131@users.noreply.github.com>

Minor Fix to Quickstart doc

---

docs/source/development-guide/make/installation.rst

Signed-off-by: Oma Anosike <71280528+oma131@users.noreply.github.com>

Documentaion update

---

docs/source/getting-started/command-line-interface/db.rst

Spellings fixed

---

docs/pull_request_template.md

Signed-off-by: Priya Srivastava <shivikapriya730@gmail.com>
Added content for Pull Request Template.

Added PR template content

---

docs/macOS_SetUp.md
docs/macOS_Setup_instructions.md

Added a macOS_Setup_instructions.md file in the docs folder. Do let me know any further changes.

---

metadata.py

version bump

---

schema/create_schema.sql
schema/generate/98-schema_update_100.sql
schema/queries/machine-learning-queries.md
scripts/control/rebuild-backend.sh

NLTK Patch

---

CONTRIBUTING.md
docs/source/development-guide/logging.rst
docs/source/development-guide/workers/clustering_worker.rst

Signed-off-by: Biki-das <bikid475@gmail.com>

Docs:Fixed typos around the docs

---

docs/source/development-guide/toc.rst

Signed-off-by: Biki Das <bikid475@gmail.com>
The contributing.md link was referring to the master branch , which is not the branch that is supposed to be work on , so i changed the link to refer to the main branch

Fix:Changed the contributing md link from master to main

---

docs/source/getting-started/frontend.rst

Signed-off-by: Oma Anosike <71280528+oma131@users.noreply.github.com>

Frontend.rst Documentation update

---

metadata.py

subversion bump

---

.gitignore

- :recycle: Fixed some Typo errors
- :snake: Added some compressed files extensions.
- :heavy_plus_sign: Added some generated files from VCS tot the .gitignore file.

♻️🐍 Fixed typo, added some content to the .gitignore

---

docs/source/development-guide/installation.rst

Signed-off-by: Biki Das <bikid475@gmail.com>
Minor improvement to the installation.rst

doc : Minor improvment to installation rst

---

docs/source/getting-started/collecting-data.rst

Signed-off-by : Oparaure Kindness  <oparauredu@gmail.com>

Fix typo: changed some words on augur documentation 

---

docs/source/docker/docker-compose.rst
docs/source/docker/docker.rst
docs/source/docker/getting-started.rst
docs/source/docker/usage.rst

Signed-off-by: Biki Das <bikid475@gmail.com>
The current docker setup documentation had a few typos and long word explanation which can improved , this PR resolves the same

Doc :Improved the current docker setup guide

---

docs/source/index.rst

Signed-off-by: Biki Das <bikid475@gmail.com>
Minor improvement to the Homepage

Doc :minor improvement to the Homepage

---

docs/source/getting-started/installation.rst
schema/create_schema.sql
schema/generate/100-schema_update_102.sql
schema/generate/99-schema_update_101.sql

Materialized View Updates

---

user-resolution-rate-check.sh

update script on facade user resolution

---

.github/workflows/build_docker.yml
augurface/package.json

- Build the frontend container
So far, that's just here to see where it fail in the CI. We have the same issue on Openshift, so this PR should be merged if the CI is not fixed.

Build the frontend container

---

augur/config.py
augur/housekeeper.py
schema/create_schema.sql
schema/generate/101-schema_update_103.sql
workers/worker_git_integration.py

- Improved management of request timeouts
- Minor schema changes for move to ORM

Improved management of request timeouts

---

schema/create_schema.sql
schema/generate/102-schema_update_104.sql
workers/worker_git_integration.py

- Fix for Issue #1873 
This PR fixes #1873 1873

Fix for Issue #1873

---

docs/source/index.rst

In this PR, I:
- Added the missing link that was raised in Issue #1612 
Signed-off-by: Precious Onyewuchi <uniquep201@gmail.com>
This PR fixes #1612 

Updated the missing link.

---

docs/source/quick-start.rst

In this PR, I:
- Embedded the link to the virtualbox site. 
Signed-off-by: Precious Onyewuchi <uniquep201@gmail.com>

Embed link to virtualbox.

---

schema/create_schema.sql
schema/generate/103-schema_update_105.sql
schema/generate/104-schema_update_106.sql
scripts/install/workers.sh

- Schema, Dependency Evaluation, and Machine Learning Updates.

Schema, Dependency Evaluation, and Machine Learning Updates. 

---

schema/generate/103-schema_update_105.sql

- removed ephemeral user permissions

removed ephemeral user permissions

---

augurface/package.json
util/docker/augurface/Dockerfile
util/docker/frontend/Dockerfile

- Add a separate augurface container, to be used for CI to make sure the augurface code is building fine

WIP: Add a augurface container

---

util/docker/augurface/Dockerfile
util/docker/backend/Dockerfile
util/docker/database/Dockerfile
util/docker/frontend/Dockerfile

dockerfile version updates

---

schema/generate/105-schema_update_107.sql

- Fixes a bug in schema update.

schema patch

---

util/docker/augurface/Dockerfile
util/docker/augurface/nginx.conf

This commit make the augurface container work in production. The frontend nginx configuration wasn't suitable for that js application, as it created endless redirects. 

Fix the augurface container

---

README.md
augur/tasks/github/issue_tasks.py

Updating my own branch of augur new

---

augur/tasks/git/util/contributor_parse.py

Signed-off-by: Isaac Milarsky <krabs@tilde.team>
Three lines

small patch to request_dict_from_endpoint

---

.dockerignore

refresh branch from main. 

---

augur/__init__.py
augur/application/cli/backend.py
augur/application/cli/celery.py
augur/application/cli/redis.py
augur/application/config.py
augur/tasks/git/facade_tasks.py
augur/tasks/github/contributors/tasks.py
augur/tasks/github/events/tasks.py
augur/tasks/github/issues/tasks.py
augur/tasks/github/messages/tasks.py
augur/tasks/github/pull_requests/core.py
augur/tasks/github/pull_requests/tasks.py
augur/tasks/github/util/github_api_key_handler.py
augur/tasks/init/__init__.py
augur/tasks/init/celery_app.py
augur/tasks/init/redis_connection.py
augur/tasks/start_tasks.py

Added the ability to configure redis database so that more than one augur instance can run on the same server

Add ability to configure redis database

---

augur/tasks/start_tasks.py

Revert "Implement augur routine"

---

augur/api/routes/auggie.py
augur/api/routes/batch.py
augur/api/routes/collection_status.py
augur/api/routes/contributor_reports.py
augur/api/routes/manager.py
augur/api/routes/metadata.py
augur/api/routes/nonstandard_metrics.py
augur/api/routes/pull_request_reports.py
augur/api/routes/user.py
augur/api/routes/util.py

The @ symbol was accidentally removed from @server.app.route during a find and replace all. This pr is just adding back all the @'s to the code.

Fix @server.app.route

---

augur/tasks/github/messages/tasks.py

Testing well with only a small set of NoneType Data related errors remaining. 
Facade Testing TBD.

Small update to Isaac/Andrew Merged Branch

---

augur/tasks/github/facade_github/contributor_interfaceable/contributor_interface.py
augur/tasks/github/facade_github/tasks.py

- Add a patch to facade contributor resolution since it didn't get put into the last pr for whatever reason.

Fix borked pr

---

docs/source/schema/regularly_used_data.rst
docs/source/schema/table_data.rst
docs/source/schema/unused_data.rst
docs/source/schema/working_tables.rst

This PR contains: 
- Addition of images to accurately display each data collected 
- Edits to change the 'used_data' file to just 'table_data'

Addition of Images to The Data Tables, etc. 

---

augur/application/db/session.py
tests/test_applicaton/test_db/test_session.py

1. Improve the null character replacement, so it works with the new string that was encountered
2. Split into functionality into 3 different functions. One that removes nulls from a string. One that removes nulls from strings in a dict. One that removes nulls from strings in a list of dicts
3. Add a unit test that tests  the `insert_data` function's ability to handle null data in strings

Fix for null characters in strings of issue data

---

augur/tasks/github/issues/tasks.py
augur/tasks/github/messages/tasks.py
augur/tasks/github/pull_requests/tasks.py

Dev Sync on New Augur for PR/ISSUE patch. 

---

augur/api/routes/collection_status.py
augur/api/routes/config.py
augur/api/routes/user.py

Cherrypick login dev

---

docs/source/schema/regularly_used_data.rst
docs/source/schema/unused_data.rst
docs/source/schema/working_tables.rst

- updated image path in documentation

schema image update

---

CONTRIBUTING.md

I have made changes to  contributing.md  file to give concise instructions on how to contribute to the  source code. These include deletion of unessential lines and renumbering.
The changes made removed redundancy in the file and this makes the instructions clearer
Let’s consider using git checkout -b new-branch-name or    git branch new-branch-name then a  git checkout new-branch-name, 
but not both

Update instruction for contributing to the source code

---

augur/tasks/data_analysis/clustering_worker/tasks.py
augur/tasks/start_tasks.py

updating sean's branch with Andrew's changes

Augur new ml fixes

---

augur/tasks/github/pull_requests/files_model/core.py
augur/tasks/github/util/gh_graphql_entities.py

Updating Sean's test branch with Isaac's changes

Isaac debug

---

augur/tasks/github/pull_requests/commits_model/core.py
augur/tasks/github/pull_requests/commits_model/tasks.py
augur/tasks/github/util/gh_graphql_entities.py
augur/tasks/init/celery_app.py
augur/tasks/start_tasks.py

Augur new dev

---

docs/source/schema/regularly_used_data.rst

Signed-off-by: Trish Nguyen <n.trish00@gmail.com>
- Updating the rst markdown to bolden each command for higher visibility.
This PR fixes #2006

Updating regularly_used_data.rst

---

augur/tasks/data_analysis/discourse_analysis/setup.py
augur/tasks/data_analysis/message_insights/setup.py

ML Updates to dev

---

augur/application/cli/db.py
augur/tasks/data_analysis/discourse_analysis/tasks.py
augur/tasks/data_analysis/pull_request_analysis_worker/tasks.py
metadata.py
tests/test_applicaton/test_repo_load_controller/test_repo_load_controller.py

Augur new dev Release Ready

---

scripts/install/workers.sh

Signed-off-by: meetagrawal09 <agrawalmeet91@gmail.com>
- This PR includes a new path added for "Go" to be checked during augur installation. The path is based on the export command in this document - https://github.com/chaoss/augur/blob/main/docs/new-install.md
- The issue was leading to a break in the installation process

Resolved Go path issue

---

.github/workflows/build_docker.yml

This PR adds explicit [permissions section](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions) to workflows. This is a security best practice because by default workflows run with [extended set of permissions](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token) (except from `on: pull_request` [from external forks](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)). By specifying any permission explicitly all others are set to none. By using the principle of least privilege the damage a compromised workflow can do (because of an [injection](https://securitylab.github.com/research/github-actions-untrusted-input/) or compromised third …

GitHub Workflows security hardening

---

README.md
docs/new-install.md

Update of dev with `main` updates.

Update Dev with PR's directly into `main`

---

augur/tasks/data_analysis/__init__.py
augur/tasks/git/facade_tasks.py
augur/tasks/start_tasks.py

- Fix logic issue with phase schedule where next phase would start after the staging of the previous rather than the actual start of the task
- Fix syntax in generate_contributor_sequence in facade 
- [ X] Yes, I signed my commits.

Fix Issues in Augur's Task Phases

---

augur/application/cli/config.py
augur/application/config.py
augur/tasks/git/facade_tasks.py
augur/tasks/github/detect_move/tasks.py
augur/tasks/github/util/gh_graphql_entities.py
augur/tasks/init/__init__.py
augur/tasks/init/celery_app.py
augur/tasks/start_tasks.py
augur/tasks/util/worker_util.py
scripts/install/config.sh

- Changed Celery broker from Redis to RabbitMQ
- Changed repo_move logic to a pooling structure to scale better
- Re-enable Celery results
- Changed pr-files model to not crash on error when pinging graphql

Pr files fix

---

docs/source/schema/regularly_used_data.rst

Signed-off-by: Glowreeyah <gloriaeskor@gmail.com>
This PR fixes #2014

Improved Documentation Format specifically heading and text structure and text 

---

augur/api/view/augur_view.py
augur/api/view/routes.py
augur/application/db/models/augur_operations.py

Fixes to various frontend issues

---

docker/backend/Dockerfile
scripts/docker/install-workers-deps.sh

While trying to make the container run, I bumped into several missing deps.
This make the container grow to 8G. That's a lot. It could be fixed by cleaning dependencies.

Add missing deps docker

---

setup.py

Needed to fix https://github.com/eventlet/eventlet/issues/781
Signed-off-by: Michael Scherer <misc@redhat.com>

Update eventlet version

---

augur/application/db/util.py
augur/tasks/data_analysis/insight_worker/tasks.py
augur/tasks/git/util/facade_worker/facade_worker/facade01config.py

- Add exponential back-off whenever a database operational error is caught. 

apply exponential backoff to dev

---

augur/tasks/data_analysis/clustering_worker/tasks.py
augur/tasks/data_analysis/contributor_breadth_worker/contributor_breadth_worker.py
augur/tasks/data_analysis/discourse_analysis/tasks.py
augur/tasks/data_analysis/insight_worker/tasks.py
augur/tasks/data_analysis/message_insights/tasks.py
augur/tasks/data_analysis/pull_request_analysis_worker/tasks.py
augur/tasks/git/facade_tasks.py
augur/tasks/github/contributors/tasks.py
augur/tasks/github/detect_move/core.py
augur/tasks/github/detect_move/tasks.py
augur/tasks/github/events/tasks.py
augur/tasks/github/issues/tasks.py
augur/tasks/github/messages/tasks.py
augur/tasks/github/pull_requests/commits_model/core.py
augur/tasks/github/pull_requests/commits_model/tasks.py
augur/tasks/github/pull_requests/core.py
augur/tasks/github/pull_requests/files_model/core.py
augur/tasks/github/pull_requests/files_model/tasks.py
augur/tasks/github/pull_requests/tasks.py
augur/tasks/github/releases/core.py
augur/tasks/github/releases/tasks.py
augur/tasks/github/repo_info/core.py
augur/tasks/github/repo_info/tasks.py
augur/tasks/init/celery_app.py
augur/tasks/start_tasks.py

Signed-off-by: Andrew Brain <andrewbrain2019@gmail.com>
Merging with Facade affiliations patch branch.

Fix machine learnig db connections and fix session passing

---

README.md
docker/augurface/Dockerfile
docker/backend/Dockerfile
docker/database/Dockerfile
docker/frontend/Dockerfile
metadata.py

Updates to the processing of machine learning tasks.

Version 0.44.2 Release

---

augur/application/db/session.py
augur/tasks/data_analysis/clustering_worker/tasks.py
augur/tasks/data_analysis/contributor_breadth_worker/contributor_breadth_worker.py
augur/tasks/data_analysis/discourse_analysis/tasks.py
augur/tasks/data_analysis/insight_worker/tasks.py
augur/tasks/data_analysis/message_insights/tasks.py
augur/tasks/data_analysis/pull_request_analysis_worker/tasks.py
augur/tasks/git/facade_tasks.py
augur/tasks/github/contributors/tasks.py
augur/tasks/github/detect_move/core.py
augur/tasks/github/detect_move/tasks.py
augur/tasks/github/events/tasks.py
augur/tasks/github/issues/tasks.py
augur/tasks/github/messages/tasks.py
augur/tasks/github/pull_requests/commits_model/core.py
augur/tasks/github/pull_requests/commits_model/tasks.py
augur/tasks/github/pull_requests/core.py
augur/tasks/github/pull_requests/files_model/core.py
augur/tasks/github/pull_requests/files_model/tasks.py
augur/tasks/github/pull_requests/tasks.py
augur/tasks/github/releases/core.py
augur/tasks/github/releases/tasks.py
augur/tasks/github/repo_info/core.py
augur/tasks/github/repo_info/tasks.py
augur/tasks/init/celery_app.py
augur/tasks/start_tasks.py

- Fixed machine learning connection leak, and reduced the number of times we are opening sessions so there is a lower chance for one in the future

Fix Machine Learning Db connection leak

---

augur/application/cli/db.py

- Fixes error when using cli to add repos or repo groups

Fix error when using cli to add repos

---

augur/application/schema/alembic/versions/10_unique_constraints_on_dependency_data.py

- Wrong version on alembic revision

alembic syntax

---

augur/api/server.py
augur/application/db/engine.py

- Fixed database errors when accessing the visualization page

Fixed database error when accessing frontend visualizations

---

augur/tasks/git/dependency_libyear_tasks/core.py
augur/tasks/git/dependency_libyear_tasks/tasks.py
augur/tasks/git/dependency_tasks/core.py
augur/tasks/git/dependency_tasks/tasks.py
augur/tasks/github/facade_github/core.py
augur/tasks/github/facade_github/tasks.py
augur/tasks/github/pull_requests/commits_model/tasks.py
augur/tasks/github/pull_requests/files_model/core.py
augur/tasks/github/pull_requests/files_model/tasks.py
augur/tasks/github/releases/tasks.py
augur/tasks/github/repo_info/core.py
augur/tasks/github/repo_info/tasks.py

- Remove unneeded try/excepts 
- Change old entry_info system to more coherent passing
- Slightly better logging
- 

Quality of life changes including removing unneeded try/excepts

---

augur/tasks/start_tasks.py

- Fix issue where facade still logs success even when facade is disabled.

Fix issue with toggling facade in config

---

augur/tasks/git/facade_tasks.py
augur/tasks/git/util/facade_worker/facade_worker/facade02utilitymethods.py

- Defined function that gets the parent commits since this was being done identically in two places
- Defined function that get the existing commits since this was being done identically in two places

Factor out duplicate code into functions

---

augur/tasks/git/dependency_libyear_tasks/core.py
augur/tasks/git/dependency_libyear_tasks/libyear_util/pypi_libyear_util.py
augur/tasks/git/dependency_libyear_tasks/libyear_util/util.py
augur/tasks/git/dependency_tasks/dependency_util/dependency_calculator.py

- Handle edge case where many repos have a package.json file without any devDependencies to analyze.
- Handle edge case where repo's version doesn't have a release associated with it for libyear
- Handle edge case where files are unable to be opened. 

Handle issues in dependency tasks

---

augur/tasks/github/detect_move/core.py

- Change collection to set repo to 'Error' when repo can't be reached by reason of 404

Add logic to handle if repo's host returns 404

---

augur/tasks/git/dependency_libyear_tasks/libyear_util/npm_libyear_utils.py
augur/tasks/git/dependency_libyear_tasks/libyear_util/pypi_parser.py
augur/tasks/git/dependency_libyear_tasks/libyear_util/util.py
augur/tasks/github/repo_info/core.py
augur/tasks/github/util/gh_graphql_entities.py
augur/tasks/github/util/util.py

- Fix issue with dependency tasks not parsing version numbers properly
- Add more handling for if repo is missing key data for libyear and other dependency analysis
- Try to decode in UTF-16 as well as UTF-8 for libyear python logic
- Fix issue with incorrectly logging error status
- Handle issue with blank graphql query return on repo_info tasks

Dev dependency bug fixes

---

augur/tasks/git/dependency_libyear_tasks/libyear_util/util.py

Fix issue when parsing dependencies for some repos where augur would incorrectly handle when information is missing or incorrectly provided. Fix for issue found by sgoggins. 

Dev minor dependency task error patch

---

augur/tasks/git/dependency_libyear_tasks/core.py
augur/tasks/git/dependency_tasks/core.py

Change dependency related tasks to use bulk-upsert transactions instead of executing a statement every iteration. 

Change dependency tasks to bulk transaction

---

augur/tasks/start_tasks.py

- Fix issue where config collection toggles weren't getting checked

Dev toggle fix

---

augur/application/cli/tasks.py
augur/tasks/data_analysis/insight_worker/setup.py
augur/tasks/git/util/facade_worker/facade_worker/facade05repofetch.py
augur/tasks/test.py

- Freeze the numpy dependency for the insight worker
- Don't raise exception when repo directory already exists just return

Changes discussed in meeting

---

augur/tasks/init/celery_app.py
augur/tasks/start_tasks.py

- Fix tasks that are incorrectly routed to the secondary worker

Fix task routing

---

readthedocs.yml

Update from `dev`

---

augur/api/view/routes.py
augur/application/db/models/augur_operations.py
augur/util/repo_load_controller.py

Signed-off-by: Ulincsys <28362836a@gmail.com>
- Update repo counting logic to consider search queries
- Fix conflicting route for collection status page

Sorting Fixes (again)

---

augur/application/util.py

- Add missing kwargs parameter for get repos count

Fix missing kwargs for get repos count

---

augur/api/routes/application.py
augur/api/routes/user.py

Add endpoints for /application/groups/repos

---

augur/tasks/git/util/facade_worker/facade_worker/facade05repofetch.py

- Use autopep8 to format facade05repofetch.py

Fix formatting issue in facade repofetch logic

---

scripts/install/config.sh

This PR fixes a incorrect error message

Fix error message in config.sh

---

augur/api/view/augur_view.py
augur/api/view/routes.py
augur/api/view/utils.py
augur/static/css/stylesheet.css
augur/templates/notice.j2

- Add 500 page with exception info to frontend
This PR closes #2281

Add 500 error page

---

augur/tasks/git/dependency_tasks/dependency_util/dependency_calculator.py
augur/tasks/git/dependency_tasks/dependency_util/go_deps.py
augur/tasks/git/dependency_tasks/dependency_util/kotlin_deps.py
augur/tasks/git/dependency_tasks/dependency_util/rust_deps.py

- Addition of new dependency language parser for Go, Rust and Kotlin.
This PR fixes #2289 

Add new dependency language parsers

---

docker/backend/entrypoint.sh

This PR permit to do the configuration outside of the Docker file setup, which is much simpler for our operational needs.

Do not configure if AUGUR_NO_CONFIG is set

---

augur/api/view/api.py
augur/util/repo_load_controller.py

parse_org_url and parse_repo_url are unused, and the 4 constants are redined in another location and used there.

Remove unused code

---

augur/api/view/api.py
augur/application/db/models/augur_operations.py

Remove_repo do not use its parameter named session, but overload it.

Remove the session parameter, as it is unused

---

augur/application/db/models/augur_operations.py
augur/application/schema/alembic/versions/17_add_collection_status_constraints.py

Fix constraints on the collection_status table to reflect edge cases of collection.

fix constraint issues with secondary and facade collection hooks

---

augur/application/cli/backend.py

- Update repo_reset command to work with new constraints. Now resets everything to the beginning
- Update clean_collection_status to work with new collection_status constraints. Now also updates the proper ids and timestamps when killing/stopping augur. 

Fix earlier queries that did not adhere to new constraints on collection_status

---

augur/api/routes/application.py

- Two of the endpoints only had POST instead of POST and GET as methods. I updated them to GET and POST so they match the pattern of the rest of the repos

Add GET method

---

augur/tasks/github/traffic/tasks.py

- The new github traffic task was importing the celery engine outside of the celery task. This means that the engine that was imported was `None`. So when None was passed to the `GithubTaskSession` class, it created a new engine since it did not get passed one to use. Additionally, the task was using 3 `GithubTaskSessions`, so every time the traffic task was ran it would create 3 engines that were not closed. I changed the task to the new `GithubTaskManifest` class, that imports the engine at the correct time, and ensures all the resources are cleaned up properly.

Fix database connection leak

---

augur/tasks/github/traffic/tasks.py

- Patch the database connection leak in the github traffic task

Database connection leak patch

---

augur/api/routes/application.py

Adds GET method to application route

adds GET http method to /application/groups/names

---

augur/templates/repos-table.j2
augur/templates/user-group-repos-table.j2
augur/util/repo_load_controller.py

- Add regex matching for repo Owner in SQL query
- Add repo Owner column
- Enable sorting by repo Owner
Signed-off-by: Ulincsys <28362836a@gmail.com>

Repo table view updates

---

augur/tasks/util/collection_util.py

Misnamed variable in user collection logic.

syntax error

---

augur/tasks/util/collection_util.py

misnamed bindparam

---

augur/tasks/util/collection_util.py

no alias on distinct

---

augur/api/view/routes.py

- Fix 500 error on user groups page

fix key error on groups view

---

augur/tasks/util/collection_util.py

Distinct sql syntax

---

augur/tasks/util/collection_util.py

missing parameter

---

augur/tasks/start_tasks.py

sql syntax

---

augur/tasks/github/messages/tasks.py

- Fix error in pr and issue message ref

Fix pr and issue message ref

---

augur/tasks/git/util/facade_worker/facade_worker/repofetch.py

Remove unneeded sql statement from facade

---

docs/new-install.rst

Quickstart documentation update

Documentation Update: Quickstart

---

augur/tasks/init/celery_app.py

Update the interval at which repositories have materialized views updated to weekly instead of daily. 

default materialized view refresh for every 7 days

---

augur/application/db/models/augur_operations.py

Fix uncaught indentation error caused by merging github api key changes with dev

Fix merge issue

---

augur/api/routes/application.py
augur/api/routes/user.py
augur/application/cli/user.py
augur/application/db/models/augur_operations.py
tests/test_applicaton/test_repo_load_controller/helper.py

- Changed the hashing algorithm to sha512 so it is less vulnerable to brute force attacks
- Increased the salt length to 32 (it actually was using salt before it was only 8 long though) to add more variability to the hashes
- Defined a standard method to get a password hash, so all the augur code uses the same security parameters

Increase security of password hashing

---

augur/api/view/api.py
augur/application/cli/backend.py
augur/application/db/models/augur_operations.py
augur/tasks/init/celery_app.py

- Defined a task that takes a list of repo and org urls that returns a list of invalid urls, added orgs, and added repos
- This now happens in the background because gunicorn just adds a task to the celery task queue
- Once the task completes all the repos show up in the user's group
- Updated backend.py to start only the frontend worker when collection is disabled

Implement asynchronous processing for adding orgs and repos

---

augur/tasks/frontend.py

- Add missing frontend.py which wasn't added to the commit

Add missing frontend.py file

---

augur/application/cli/user.py

- Add new CLI command to reset a user's password

add password reset command

---

augur/util/repo_load_controller.py

- Make queries paramaterized so they are secure against sql injection

Protect against sql injection

---

conftest.py

- Added pytest fixtures to allow for augur developers to easily create a delete a database when writing tests

Add testing fixtures for easy database creation and deletion

---

augur/application/config.py
docs/source/development-guide/create-a-metric/metrics-steps.rst
docs/source/development-guide/logging.rst
docs/source/development-guide/workers/clustering_worker.rst
docs/source/getting-started/collecting-data.rst
docs/source/schema/overview.rst
docs/source/schema/regularly_used_data.rst
docs/source/schema/working_tables.rst

- Update deprecated documentation having to do with old workers and housekeeper
- Update docs related to the config
- Update facade docs
- Update schema docs
- Replace instances of 'Worker' with 'Task' when appropriate

Update documentation to more closely reflect new celery data collection

---

augur/api/view/api.py
augur/tasks/frontend.py

- Quickly add repos to a group if they already exist in the database rather than waiting for the async job to add them

Quickly add repos to group if they already exist

---

augur/static/css/stylesheet.css

- Fix toast messages appearing behind cards
- Fix contrast issue with toast foregrounds

Fix toast messages visibility

---

augur/static/css/dashboard.css
augur/static/css/stylesheet.css

- Try one *final* time to actually fix the toast visibility

Fix toast messages visibility againgain

---

augur/templates/dei-badging-report.j2

Add jinja example to markdown file

---

augur/api/routes/util.py

Fixes issue: https://github.com/chaoss/augur/issues/2452 #2542 

Dev api performance patch

---

README.md
docker/backend/Dockerfile
docker/database/Dockerfile
metadata.py

Updated the release numbers in dev, preparing for release to main.

updating versions for release

---

augur/application/cli/backend.py
augur/tasks/data_analysis/contributor_breadth_worker/contributor_breadth_worker.py
augur/tasks/init/celery_app.py

Enabling contributor breadth task.

Contributor breadth conversion

---

augur/api/view/utils.py
augur/tasks/github/pull_requests/files_model/core.py

Taking @IsaacMilarky 's fixes for SQLAlchemy and merging them into my versionless library branch to try.

Sql alchemy upgrade

---

README.md
docker/backend/Dockerfile
docker/database/Dockerfile
metadata.py

-- Just updating versions in metadata.

version Updates

---

README.md
docker/backend/Dockerfile
docker/database/Dockerfile
metadata.py

- Just updating version numbers.

version update

---

docs/source/getting-started/dev-osx-install.rst
docs/source/getting-started/new-install.rst
docs/source/index.rst

docs update

---

augur/tasks/github/pull_requests/tasks.py

- Fix issue where all pr reviews in a repo are assigned to the same pull request id

Fix pr reviews issue

---

augur/application/db/models/augur_operations.py

Checking to see if there's anything in dev not in graphql

---

augur/application/db/models/augur_operations.py
augur/static/css/stylesheet.css
augur/tasks/db/refresh_materialized_views.py
augur/tasks/github/events/tasks.py
augur/tasks/github/pull_requests/tasks.py
augur/templates/settings.j2

Updating Graphql API Experiment

---

augur/tasks/github/events/tasks.py
docker/backend/Dockerfile
docker/backend/entrypoint.sh
docker/backend/init.sh

Keeping dev branches current with dev.

Updating data fixer with dev

---

augur/tasks/git/util/facade_worker/facade_worker/analyzecommit.py
augur/tasks/git/util/facade_worker/facade_worker/utilitymethods.py

Fix syntax error in facade changes

---

.readthedocs.yml
readthedocs.yml

- Configuration requirements for readthedocs.io changed
- Updates to `readthedocs.yml` tested on dev.

Readthedocs.io Patch

---

augur/templates/login.j2

This PR fixes https://github.com/chaoss/augur/issues/2403

fixed focus field when 'register' is clicked

---

augur/application/db/models/augur_operations.py

Fix issue when merging repo_load_controller changes and orm warning changes together

---

augur/api/routes/__init__.py
augur/api/routes/complexity.py

Fix complexity endpoints

---

README.md
docker/backend/Dockerfile
docker/database/Dockerfile
docker/rabbitmq/Dockerfile
metadata.py

- Updating version in files where it is declared.

Updating versioning for release publication

---

docker/backend/Dockerfile
docker/database/Dockerfile
docker/rabbitmq/Dockerfile

Updates Key files for versioning.

updated Dockerfile Augur versions

---

augur/tasks/start_tasks.py

- Fix retry repo query string
- 

Fix query string

---

augur/tasks/start_tasks.py

Main into dev

---

.github/workflows/auto_merge.yml

- Added auto_merge.yml
- Added workflow to automatically merge main into dev whenever there are changes to main
- Using [CasperWA/push-protected@v2](https://github.com/CasperWA/push-protected) we are able to push to protected branches as long as we have a privileged token to use. It also doesn't do anything if there are no changes to push. 

Add GitHub Action to Always Keep Dev up to Date with Main

---

README.md
augur/api/routes/pull_request_reports.py
docker/backend/Dockerfile
docker/database/Dockerfile
docker/rabbitmq/Dockerfile
metadata.py

API Patch: Repairs Viz API Issues for PRs on some instances. 

---

.github/workflows/auto_merge.yml

- Fix issue with GitHub not having proper git credentials in action 
- Add timestamp in commit message
Sorry about the repeat PRs it's just hard to test GitHub actions locally. 

Fix Script Lacking Identifier for GH Actions

---

augur/api/routes/complexity.py
docs/source/rest-api/spec.yml

- Add where clause to filter by repo_id to project_lines, comment_lines, and blank_lines endpoints
- Update endpoint documentation to reflect api changes

Add Repository ID Parameters to Line Complexity Endpoints

---

augur/tasks/data_analysis/insight_worker/tasks.py

Fix engine.execute error : Dev update

---

augur/api/metrics/deps.py
augur/api/metrics/pull_request.py
augur/api/metrics/repo_meta.py
augur/api/metrics/toss.py

Dev api fixes

---

augur/templates/settings.j2

- Change name of "Repo Tracker" section in profile page to "My Repos"
- Fix redirect logic so actions bring you back to the correct section
- Modify *issues* link to open in new tab
This PR fixes #2753
This PR fixes #2754

Attempt to clarify profile page terminology, fix redirects

---

.github/workflows/build_docker.yml
scripts/mat_view_explore/materialized_view_pr.sql

update check for pr_file_patch

---

augur/tasks/git/dependency_libyear_tasks/libyear_util/npm_libyear_utils.py

npm dependency patch

---

docs/source/rest-api/spec.yml

- updates  most of  API description URLs 

update most API description URLS

---

scripts/install/config.sh

- Use GNU readline to enable tab-completion of file paths
- Use `realpath` to enable the use of relative paths
- Clarify the prompt structure to make it less confusing

Improve directory selection for facade worker

---

augur/application/config.py

Order settings and sections from config

---

scripts/install/config.sh

Add check to config.sh to see if we can write git credentials and exit if we can't 

Add check to see if git credentials are writable

---

augur/tasks/github/facade_github/tasks.py

Resolve contributor if we find one

---

.pylintrc

Make Pylint Messages Exclusive Not Inclusive

Make Pylint Messages Exclusive Not Inclusive

---

augur/tasks/data_analysis/contributor_breadth_worker/contributor_breadth_worker.py

Handle url not found in contributor breadth worker

---

scripts/install/workers.sh

- Fix scorecard install script issues
- Simplify detecting if `go` is installed

Release 0.76.2 fix install

---

augur/api/view/api.py
augur/application/db/models/augur_data.py
augur/tasks/github/util/util.py
augur/tasks/gitlab/events_task.py
augur/tasks/gitlab/issues_task.py
augur/tasks/gitlab/merge_request_task.py

- Add support for nested gitlab repos like https://gitlab.com/redhat/centos-stream/rpms/kernel

Add support for nested gitlab repos

---

CONTRIBUTING.md

This PR updates the CONTRIBUTING.md file to have better formatting, updated commands and improved readability

update CONTRIBUTING.md file to have a better formatting

---

README.md
docker/backend/Dockerfile
docker/database/Dockerfile
docker/rabbitmq/Dockerfile
metadata.py

- Patches accepted into main moved into dev.

Merge Patches back to Dev

---

augur/application/db/models/augur_data.py

- Make nullable repo_src_id insertion possible
This PR fixes #2963 

hotfix for issue 2963

---

augur/tasks/github/util/populate_repo_src_id.py

Fix issue pr sum error

---

augur/tasks/gitlab/issues_task.py

Fix gitlab reviews syntax error

---

augur/tasks/util/collection_util.py

- When searching for new repos that need to be collected, smaller repos are collected first 

Collect smallest repos first on initial collection 

---

augur/tasks/init/celery_app.py

Comment out update weight task as it is no longer needed

---

README.md
augur/tasks/init/celery_app.py
gsoc-ideas.md
gsoc-interest.md
metadata.py

- hotfix for orphaned jobs
- already merged in `main`

Remove update weight hotfix

---

augur/application/cli/__init__.py

- Print full tracebacks for non-timeout exceptions during network connectivity test
- Pass secondary exceptions (from execution target) transparently
- Use multiline string for error message printing

Logging and logical improvements for test_connection decorator

---

augur/tasks/github/pull_requests/tasks.py

- Fix a logical error where a task might try to subtract from NoneType due to a NULL database column value

Fix comparison with NoneType logical error

---

README.md
augur/tasks/github/augur-notes.code-workspace
docker/backend/Dockerfile
docker/database/Dockerfile
docker/rabbitmq/Dockerfile
metadata.py

Augur v0.85.0 release

---

README.md
docker/backend/Dockerfile
docker/database/Dockerfile
docker/rabbitmq/Dockerfile
metadata.py

version bumpt'y dump

---

augur/tasks/frontend.py

1. Add repo from the frontend
2. Add the org of the repo from the frontend.
3. Ensure the repo is in the org repo group

Move repos to org when repo is added before org

---

docker-compose.yml

This includes a (commented) flower config in the docker compose to make things easier for contributors to enable flower in case it is useful

add flower section to the docker compose

---

keyman/KeyClient.py
keyman/KeyOrchestrationAPI.py
keyman/Orchestrator.py
tests/key_manager.py

- Improve some of the inline documentation 
- Add more precise logging to the orchestration server
- Add key client and orchestration server infrastructure for INVALIDATE commands

Add INVALIDATE command for key orchestration

---

augur/tasks/github/util/github_data_access.py

* Request a new key for all ratelimit exceptions

Request new key for all ratelimit exceptions

---

augur/tasks/github/util/github_data_access.py

update to time.time() not time.now()

---

augur/tasks/git/util/facade_worker/facade_worker/analyzecommit.py
augur/tasks/git/util/facade_worker/facade_worker/utilitymethods.py

- Have more complete log of stderr when calling 'git rev-list' when initializing facade's commit count
- Pipe stderr to capture it for logging

log stderr in called process for facade commit count

---

augur/tasks/github/util/github_data_access.py

- Stop using github api keys when they have 50 requests left

Leave room on github api key rate limit

---

augur/tasks/github/util/github_data_access.py

This PR fixes a syntax error, causing that Augur could not start.

fix syntax error

---

augur/tasks/data_analysis/clustering_worker/setup.py
augur/tasks/data_analysis/contributor_breadth_worker/setup.py
augur/tasks/data_analysis/discourse_analysis/setup.py
augur/tasks/data_analysis/insight_worker/setup.py
augur/tasks/data_analysis/message_insights/setup.py
augur/tasks/data_analysis/pull_request_analysis_worker/setup.py
augur/tasks/git/util/facade_worker/setup.py
docker-compose.yml
setup.py

update version and compose

---

augur/tasks/data_analysis/clustering_worker/setup.py
augur/tasks/data_analysis/contributor_breadth_worker/setup.py
augur/tasks/data_analysis/discourse_analysis/setup.py
augur/tasks/data_analysis/insight_worker/setup.py
augur/tasks/data_analysis/message_insights/setup.py
augur/tasks/data_analysis/pull_request_analysis_worker/setup.py
augur/tasks/git/util/facade_worker/setup.py
docker-compose.yml
docker/backend/Dockerfile
setup.py

This updates 
- the version of psycopg2-binary 
- adds changes to docker compose 
- fixes the scorcard around 
- [ x ] Yes, I signed my commits.
I think? lmk if I need to do anything 
Please test in linux environment and on bare metal before merging

Docker mac fix

---

README.md
augur/application/cli/__init__.py
augur/application/cli/backend.py
augur/application/cli/github.py
augur/tasks/frontend.py
augur/tasks/github/augur-notes.code-workspace
augur/tasks/github/events.py
augur/tasks/github/pull_requests/tasks.py
augur/tasks/github/util/github_api_key_handler.py
augur/tasks/gitlab/gitlab_api_key_handler.py
augur/tasks/init/celery_app.py
augur/tasks/start_tasks.py
augur/util/repo_load_controller.py
docker/backend/Dockerfile
docker/backend/graphical
docker/database/Dockerfile
docker/rabbitmq/Dockerfile
gsoc-ideas.md
gsoc-interest.md
metadata.py
scripts/docker/install-golang-deps.sh
scripts/docker/install-workers-deps.sh
test.md

Fix conflicts and merge main into dev

Merge main into dev

---

augur/tasks/github/events.py

- Not found exceptions were not being handled for github pr events

Catch not found exception for github pr events

---

augur/application/db/lib.py
augur/tasks/github/util/github_data_access.py

- Hotfix #3139 into main ahead of dev release
- Add more verbose logging to GitHub data access

Ratelimit logging improvements + facade timestamp fix

---

augur/application/db/lib.py

This PR fixes #3134 
- Rollback transaction on failure
- Automatically substitute tz for UTC when invalid
- Do not reset date on invalid tz

Fix facade task failure

---

augur/application/cli/backend.py
augur/tasks/github/facade_github/contributor_interfaceable/contributor_interface.py
augur/tasks/github/util/github_data_access.py

- Ensure that the github search ratelimit is respected so we don't just keep using the key

Fix gihtub ratelimit issues in facade contributor resolution

---

README.md
docs/source/docker/docker.rst
docs/source/docker/getting-started.rst
docs/source/docker/quick-start.rst
docs/source/getting-started/dev-osx-install.rst
docs/source/getting-started/using-docker.rst
docs/source/quick-start.rst

This updates the docker start up documentation. I view this as a first round pass and I am sure there will be more context and situations needed. This is for the base case I have hit. 
- [X ] Yes, I signed my commits.

Update documentation to new docker compose 

---

augur/application/schema/alembic/versions/32_update_openssf_deps.py
augur/application/schema/alembic/versions/33_update_openssf_deps.py
augur/tasks/git/dependency_tasks/core.py

- Fixes Issue #3172 
- Keeps a history of OpenSSF Scorecard Runs against a repository.
This PR fixes #3172 
- [X ] Yes, I signed my commits.
<!--
Thank you for contributing to CHAOSS projects!

Scorecard check Fix for Scorecard Collection 

---

augur/application/schema/alembic/versions/32_update_openssf_deps.py
augur/application/schema/alembic/versions/33_update_openssf_deps.py
augur/tasks/git/dependency_tasks/core.py
augur/tasks/github/events.py
augur/tasks/github/messages.py
augur/tasks/github/pull_requests/commits_model/core.py
augur/tasks/github/pull_requests/files_model/core.py
augur/tasks/github/releases/core.py
augur/tasks/github/repo_info/core.py
augur/tasks/github/util/github_data_access.py

Tidy up some items around exception handling and repo_info logic

---

augur/application/schema/alembic/versions/32_update_openssf_deps.py
augur/application/schema/alembic/versions/33_update_openssf_deps.py
augur/tasks/git/dependency_tasks/core.py

- Fixes #3172 
- Fixes Issue where OpenSSF Scorecard history is not kept
This PR fixes #3172

Scorecard check spg1: Fixes Issue with OpenSSF ScoreCard Collection

---

augur/application/schema/alembic/versions/34_pr_files_index.py
augur/tasks/data_analysis/clustering_worker/setup.py
augur/tasks/data_analysis/contributor_breadth_worker/setup.py
augur/tasks/data_analysis/discourse_analysis/setup.py
augur/tasks/data_analysis/insight_worker/setup.py
augur/tasks/data_analysis/message_insights/setup.py
augur/tasks/data_analysis/pull_request_analysis_worker/setup.py
augur/tasks/git/util/facade_worker/setup.py
setup.py

- Latest version of psycopg2-binary includes correct mapping of Postgresql 17 codes. 
- Fixes #3167

Updated psycopg2-binary for Postgresql 17
